### ISSUE TITLE
Document open-source mesh generation workflows

### ISSUE THREAD

**Issue by bgranzow** [SNLComputation/Albany#118]
The open source work-flow 
```
gmsh -> PUMI -> Albany
```
is possible and has been utilized with success. It would be useful to create a wiki page fully detailing this work flow for the sake of potential users and for the circulation of information.

**Comment by JustinClough** [comment]
@bgranzow Are you still working on this? 

I updated the `.msh` file reader in Albany to match the Gmsh 4.2 file formats. I've been using a straight `Gmsh -> Albany` workflow since. I can take this over and write a wiki page on that. Let me know what you think.

**Comment by bartgol** [comment]
+1 for the wiki page.

**Comment by bgranzow** [comment]
I'm not working on it anymore. I'll add a +1 for the wiki page.

**Comment by JustinClough** [comment]
Here's a rough draft, still need to add an example: https://github.com/SNLComputation/Albany/wiki/Using-Gmsh-to-Create-Geometry,-Meshes;-An-Open-Source-Workflow

Let me know if I'm missing anything. Otherwise I'll add the example section and close this issue.

**Comment by bartgol** [comment]
Looks good. Thanks for explaining the meaning of the input flags. Just one question: I looked at the help, but can't find the flag to generate hexa meshes rather than triangle meshes. Is this hidden in the `order` flag (perhaps it's not just the order of the element, but more like an enum of the element type)?

**Comment by JustinClough** [comment]
I added a line about using hex's. There's a parameter to set in the input script. I personally haven't needed or used a hex or quad mesh so there may be a better way. 

I also added content to the example section. I'll go ahead and close this issue. Please re-open it if needed.

I'll update the wiki once I get the multiple element blocks figured out.
