### ISSUE TITLE
Revive QCAD CI, push to Albany repo, and create tests 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#161]
Once this works, tests should be activated in nightly CDash test harness.

**Comment by hsahasra** [comment]
Hello Irina,

Is there an ETA for uploading the CI package?

Thanks!
Harshad

**Comment by ikalash** [comment]
@ibaned , I think you were planning to check in the CI stuff.  Are there any updates on this?  Are we still waiting on a P/T from @enielse ?

**Comment by ibaned** [comment]
I don't think I'll have time for this in FY18

**Comment by ikalash** [comment]
I think this is no longer on the table, as QCAD has been moved to a tag.
