### ISSUE TITLE
Creation of example repository for larger illustrative problems

### ISSUE THREAD

**Issue by jtostie** [SNLComputation/Albany#17]
Longer sets of tests allow more rigorous verification of physics.

**Comment by lxmota** [comment]
This is directly related to #39

**Comment by ibaned** [comment]
As part of #39, the `tests/large/` directory looks like it will be fulfilling this requirement. As we resolve #36 we will move that directory to its own repository.

**Comment by ibaned** [comment]
I'm done with the initial version of `tests/large/`. Waiting on #36.

**Comment by bartgol** [comment]
I think this has been done.
