### ISSUE TITLE
Resolve Trilinos ETI and DTK

### ISSUE THREAD

**Issue by ibaned** [SNLComputation/Albany#214]
@mhoemmen and @mperego use signed integers in their Trilinos packages, while DTK developers use unsigned. Albany sometimes needs both libraries, and we need some kind of resolution. I know there was an effort made by @mhoemmen and @ikalash but I don't think it was fully successful.

What Albany needs is the compile-time benefits of Trilinos ETI, plus the ability to still call DTK.

If someone knows the relevant DTK developers, could you please mention them?

**Comment by aprokop** [comment]
@sslattery, @dalg24 are DTK developers. The issues was discussed at DTK meetings at some point, but I'll let them summarize it.

**Comment by mhoemmen** [comment]
Tpetra developers are moving towards picking a single global index (`GlobalOrdinal`, a.k.a. `global_index_type`) type, rather than having that be a template parameter chosen by users.  If users want a Zoltan-style "global key" type that differs from Tpetra's global index type, my view is that this should be an abstraction above Tpetra's global index type.  That would solve DTK's issue as well as more general issues.

**Comment by mhoemmen** [comment]
I have added a Tpetra issue referencing this issue.  It's important for Tpetra developers to discuss this soon, since we are planning to make the relevant design decisions this FY.

**Comment by ibaned** [comment]
@mhoemmen your comments are even more relevant to our issue #213 

I for one support this direction for Tpetra

**Comment by sslattery** [comment]
In general I would prefer to fix the ordinal types in our implementation and only offer template parameters for `Node` type and `Scalar` type. This would really streamline our own implementations. I think the idea of @mhoemmen is not unreasonable and may fit with our new Kokkos-based design. The DTK developers are meeting tomorrow - we will discuss and update this issue.

@mhoemmen for reference can you point to the new templating scheme for Tpetra regarding which types are templates and which are now pre-defined?

**Comment by mhoemmen** [comment]
@sslattery We're still figuring this out, and thus welcome your input :-) .

One of the proposals is to remove at least the `GlobalOrdinal` template parameter, and possibly also the `LocalOrdinal` template parameter as well.

**Comment by bartgol** [comment]
@mhoemmen  I'm confused: will Tpetra hard code a particular global/local index type, effectively removing the ability to choose it(them)? Or will it just remove it from the template parameters, forcing the whole installation to use a single global/local type, but still allow the user to choose the *single* local/global index type at configure time?

**Comment by mhoemmen** [comment]
@bartgol See my answer here: https://github.com/gahansen/Albany/issues/213#issuecomment-342367212

> will Tpetra hard code a particular global/local index type, effectively removing the ability to choose it(them)?  Or will it just remove it from the template parameters, forcing the whole installation to use a single global/local type, but still allow the user to choose the single local/global index type at configure time?

We're deciding that now.  Consider this: As long as Tpetra uses a sufficiently large global index type, why should apps be constrained to use the same global index type for their meshes, etc., as Tpetra uses for its data structures?

**Comment by ikalash** [comment]
This has been resolved - we can now build DTK with ETI.  The key is to have the following configure options in Trilinos: ```D Tpetra_INST_INT_UNSIGNED_LONG:BOOL=ON ```.

**Comment by mhoemmen** [comment]
@ikalash At some point, I would like to fix DTK so that it just uses any enabled 64-bit Tpetra global ordinal type, instead of forcing use of unsigned in Tpetra.  DTK is rebuilding all of Trilinos just because it insists on that global ordinal type.

**Comment by aprokop** [comment]
DTK switched to using signed integers back in October.

**Comment by ibaned** [comment]
@aprokop really? @ikalash are we just using an old version? If @aprokop is saying what I think he's saying then I think it could resolve this whole issue in the *right* way

**Comment by aprokop** [comment]
https://github.com/ORNL-CEES/DataTransferKit/pull/482

**Comment by ikalash** [comment]
Doh!  We _were_ using an old version, at least I was in my nightlies!  I had forgotten about this - we used the version of the day for awhile, then at some point we switched (perhaps based on a recommendation by Stuart) due to instabilities.  Thanks for bringing this up @aprokop  - things work out of the box now with DTK + ETI w/o any special configure options.

@lxmota : are you using version of the day DTK in your nightlies or an older version like I was?  If you switch to version of the day, you should be able to enable ETI + DTK w/o having the configure option ```-D Tpetra_INST_INT_UNSIGNED_LONG:BOOL=ON```.

**Comment by lxmota** [comment]
@ikalash I'm using the release from DTK's web site. I seem to recall Stuart Slattery (or was is Roger) saying that the VOTD was unstable and that we should use the release.

**Comment by ikalash** [comment]
Yes, exactly, this is what I remember too.  Perhaps @aprokop (or @sslattery or @rppawlo ) can comment on this.  In any case, we need a newer version than the one we were using (v2.0) to get the changes allowing us to use ETI in the most general sense.

**Comment by rppawlo** [comment]
If I recall correctly, at the time, the dev branch was pretty much empty. DTK tagged 2.0 and then started with a clean slate in the dev branch. Maybe I am missing something, but the commt @aprokop pointed to above was for the local ordinal, not the global ordinal. I think albany needs DTK to use a consistent GO type enabled for Tpetra during configure - the ability to use a signed 64 bit integer.

**Comment by ikalash** [comment]
Yeah...  I spoke prematurely.  We get a slew of compilation errors when building Albany against Trilinos with DTK version of the day may be due to not just this issue, but also changes made to DTK after the 2.0 release, e.g. 

```
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/DTK_ClientManager.hpp:105:31: note:   expected a type, got ‘Field’
In file included from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/DTK_STKMeshManager.hpp:50,
                 from /home/ikalash/nightlyCDash/repos/Albany/src/./LCM/evaluators/bc/SchwarzBC.hpp:24,
                 from /home/ikalash/nightlyCDash/repos/Albany/src/./PHAL_FactoryTraits.hpp:25,
                 from /home/ikalash/nightlyCDash/repos/Albany/src/./problems/Albany_AbstractProblem.hpp:43,
                 from /home/ikalash/nightlyCDash/repos/Albany/src/./Albany_Application.hpp:28,
                 from /home/ikalash/nightlyCDash/repos/Albany/src/./Albany_SolverFactory.hpp:10,
                 from /home/ikalash/nightlyCDash/repos/Albany/src/LandIce/interface_with_cism/ali_driver.cpp:42:
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/DTK_FieldMultiVector.hpp:84:47: error: type/value mismatch at argument 1 in template parameter list for ‘template<class T> class Teuchos::RCP’
                       const Teuchos::RCP<Field> &field );
                                               ^
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/DTK_FieldMultiVector.hpp:84:47: note:   expected a type, got ‘Field’
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/DTK_FieldMultiVector.hpp:93:47: error: type/value mismatch at argument 1 in template parameter list for ‘template<class T> class Teuchos::RCP’
     FieldMultiVector( const Teuchos::RCP<Field> &field,
                                               ^
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/DTK_FieldMultiVector.hpp:93:47: note:   expected a type, got ‘Field’
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/include/DTK_FieldMultiVector.hpp:108:23: error: type/value mismatch at argument 1 in template parameter list for ‘template<class T> class Teuchos::RCP’
     Teuchos::RCP<Field> d_field;
```

**Comment by mhoemmen** [comment]
@ikalash It's OK -- I'm just glad to see that DTK has changed.  I worry about Trilinos not testing this use case, that historically (circa 2011) took a bit of effort to fix.  (@maherou and @kddevin, this is an example of the additional complexity and maintenance effort introduced by the GlobalOrdinal template parameter.)

**Comment by ikalash** [comment]
@mhoemmen : I am inclined to keep the old DTK version with the ```-D Tpetra_INST_INT_UNSIGNED_LONG:BOOL=ON``` flag, since this works for us, and I do not have the bandwidth to dive into it anymore.

Regarding testing: you may be interested in the following issue I opened yesterday based on the SART meeting:

https://github.com/SNLComputation/Albany/issues/441

It enumerates the tests we do in Albany and what may be unique about them compared to Trilinos - having DTK on in some of them is one unique thing that is mentioned there.

**Comment by aprokop** [comment]
@ikalash I did not realize you used old 2.0 version. What functionality do you use? We do consider VOTD pretty stable, but only test it against a specific version of Trilinos that we freeze periodically (and could be found in container build instructions).

**Comment by ikalash** [comment]
@aprokop : I'm not opposed to switching to VOTD in theory, except when I tried to build Albany against it yesterday, I got a bunch of compilation errors having to do with Field (I posted the error if you scroll up a bit).  We primarily use DTK to interpolate a solution from a volume onto a boundary that overlaps with the volume in an alternating Schwarz implementation we have - see https://github.com/SNLComputation/Albany/blob/master/src/LCM/evaluators/bc/StrongSchwarzBC_Def.hpp#L346-L551 for details.  We also have some utilities to use DTK to compute relative errors in a solution on one mesh w.r.t. a solution on another mesh.  

I'm guessing some syntax changed in DTK b/w v2.0 and VOTD leading to our compilation errors.  Sadly neither I nor my co-developer of Schwarz @lxmota have the bandwidth to figure out what changed at this point, so we'll probably stick with the old version for some time.  Another reason is stability - Trilinos has been breaking our nightlies a lot recently; I'd be worried that DTK VOTD would be unstable potentially in a similar way.  

@lxmota if you disagree with my statements here, please feel free to chime in.

**Comment by lxmota** [comment]
@ikalash 200% behind you on this.
