### ISSUE TITLE
Neumann boundary conditions act upon nodes or node sets

### ISSUE THREAD

**Issue by hillyuan** [SNLComputation/Albany#299]
This type of boundary condition includes concentrated forces, concentrated heat flux applied to any node or node sets.

**Comment by hillyuan** [comment]
The implementation of Albany is rather uique, which I am not really understand yet. It maybe good at hardware indepenedent parralization, extendability etc. But I don't think it is beneficial for computational efficiency.

Generally, nodal concentrated external loads can be easily implemented by just add up it to relevent rhs of system equation. It is irrelevent to any parrallel computation also. Maybe it is better to avoid those multi-step 'normal' evaluator procedure. As I am not familar to the software design of Albany yet, I am wondering if Albany development team could propose a basic design of its implementation.

**Comment by mperego** [comment]
I totally agree with @bartgol comment and I think that his solution of using distributed parameters and Dirichlet BCs is a good one. It's a bit of a workaround but at least it will be confined to your problem and it won't touch more general parts of Albany.

**Comment by bartgol** [comment]
Closing for lack of response.
