### ISSUE TITLE
Build Albany on Mac OS 10.12.3

### ISSUE THREAD

**Issue by Tdub122984** [SNLComputation/Albany#309]
I am struggling with building Albany on a Mac. I fairly sure that it that it is an easy fix, but after googling for the last two days... Any guidance would greatly be appreciated. 

Found Trilinos!  Here are the details: 
   Trilinos_DIR = /usr/local/lib/cmake/Trilinos
   Trilinos_VERSION = 12.13
   Trilinos_BIN_DIRS = /usr/local/lib/cmake/Trilinos/../../../bin
   Trilinos_TPL_LIST = DLlib;LAPACK;BLAS;MPI;Pthread
   Trilinos_TPL_LIBRARY_DIRS = 
   Trilinos_BUILD_SHARED_LIBS = FALSE
   Trilinos_CXX_COMPILER_FLAGS =  -std=c++11 -O3 -DNDEBUG
End of Trilinos details

CMake Error at CMakeLists.txt:62 (LIST):
  LIST sub-command REVERSE requires list to be present.

CMake Error at CMakeLists.txt:63 (LIST):
  LIST sub-command REMOVE_DUPLICATES requires list to be present.

CMake Error at CMakeLists.txt:64 (LIST):
  LIST sub-command REVERSE requires list to be present.

Setting and checking of compilers:
-- Deprecated code warnings Enabled, compiling with -DALBANY_ENABLE_DEPRECATED
-- The Fortran compiler identification is unknown
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Check for working Fortran compiler: /usr/local/bin/gfortran
-- Check for working Fortran compiler: /usr/local/bin/gfortran  -- broken
CMake Error at /opt/local/share/cmake-3.11/Modules/CMakeTestFortranCompiler.cmake:45 (message):
  The Fortran compiler

    "/usr/local/bin/gfortran"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/ER/Albany/src/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_bc52f/fast"
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_bc52f.dir/build.make CMakeFiles/cmTC_bc52f.dir/build
    Building Fortran object CMakeFiles/cmTC_bc52f.dir/testFortranCompiler.f.o
    /usr/local/bin/gfortran    -c /Users/ER/Albany/src/CMakeFiles/CMakeTmp/testFortranCompiler.f -o CMakeFiles/cmTC_bc52f.dir/testFortranCompiler.f.o
    FATAL:/opt/local/bin/../libexec/as/x86_64/as: I don't understand 'm' flag!
    make[1]: *** [CMakeFiles/cmTC_bc52f.dir/testFortranCompiler.f.o] Error 1
    make: *** [cmTC_bc52f/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:188 (ENABLE_LANGUAGE)

-- Configuring incomplete, errors occurred!
See also "/Users/ER/Albany/src/CMakeFiles/CMakeOutput.log".
See also "/Users/ER/Albany/src/CMakeFiles/CMakeError.log".

**Comment by ikalash** [comment]
Stale issue - closing.
