### ISSUE TITLE
Time Dependent BC that varies in space and time 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#316]
As discussed at the Albany meeting this morning, there is an interest in adding to Albany a time dependent BC (Dirichlet as well as Neumann) where the BC values are spatially and temporally dependent, and not given by an analytical function.  Albany currently has the following capabilities: 

- Set a Dirichlet BC from a field in the mesh named dirichlet_field (allowing a spatially-varying BC that is not given by an analytical function).
- Set a time-dependent BC (Dirichlet, perhaps Neumann too) that is spatially constant on a given nodeset.

The new time dependent BC would combine these two capabilities.  Specifically, we'd need to: 

- Add the capability to read snapshots defining the BC field into dirichlet_field.  Probably we should not store all the snapshots but a couple at a time to avoid running out of memory. 
- Add the capability to interpolate the time-dependent BC values to times where they are needed, in the case where the time-step is different than the times where the snapshots are stored.  This sort of interpolation is done already in TimeDepBC for scalar-valued (in space) BCs.  This interpolation is what will require at least 2 BC snapshots to be stored at a time. 

Any volunteers to help with this task?  The new BC is of interest to the Tsunami work, as well as the RPI folks; perhaps others are interested in this too?

**Comment by ikalash** [comment]
@jfike : It occurred to me the MOR stuff is likely reading in a time-dependent snapshot file.  Is this done all at once, or several snapshots at a time?  I'm wondering if some of the MOR logic might be possible to hijack to facilitate the implementation of this BC.

**Comment by jfike** [comment]
Yes, there is probably a lot of overlap with the MOR stuff.  The basis file that we read in is essentially an exodus file with multiple snapshots.  It just depends on whether you interpret the snapshots as modes or time steps.

I believe we have a loop m=1 to M, where we read the mth snapshot from the exodus file and store it in the mth column of a multivector.  You could probably adapt it to read in some chunk of snapshots.

**Comment by ikalash** [comment]
Not pursuing this at this time, therefore closing.
