### ISSUE TITLE
Replacing Epetra dgdp in PHAL::Workset with Tpetra dgdpT throughout Albany

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#32]
I have been making an effort to remove Epetra member variables in PHAL::Workset, as a part of the conversion of ATO to Tpetra/Thyra.  This includes in particular responses and their derivatives (workset.g, workset.dgdp, and workset.overlapped_dgdp).  I was able to successfully remove the Epetra versions of g and overlapped_dgdp in PHAL::Workset and replace them with Tpetra analogs throughout Albany.  I am having issues with workset.dgdp, however.  The only place where workset.dgdp appears is: 

src/evaluators/PHAL_SeparableScatterScalarResponse_Def.hpp
responses/Albany_FieldManagerScalarResponseFunction.cpp

The switch from workset.dgdp to workset.dgdpT should be trivial.  However, when I make the change, the ATO::Constraint2D_adj test fails.  @mperego, can you please have a look at this, as the author of distributed responses?

**Comment by mperego** [comment]
I'll have a look at that.

**Comment by ikalash** [comment]
Thanks, Mauro!

**Comment by mperego** [comment]
Removed workset.dgdp and converted evaluateDistParamDeriv functions to Tpetra. See 424ec1d548b5435.

**Comment by bartgol** [comment]
Closing, since #454 eliminated *petra from the `Workset` class (except for eigen-related stuff, which we are still working on).
