### ISSUE TITLE
LCM: is Schwarz_Boundary just a Null operator?

### ISSUE THREAD

**Issue by bartgol** [SNLComputation/Albany#340]
While propagating some changes during the thyra refactor, I stumbled upon this class. It appears to me to be just a null operator. Is there a plan to extend it in the future or is it always going to stay like that?

If I understand correctly, this class is used for the off-diagonal blocks of the coupled Schwarz jacobian. I am assumin only additive Schwarz is implemented, so that they are all zero. Perhaps in the future there will be a multiplicative Schwarz and some of those blocks will be nonzero? Otherwise, we may as well replace the off-diagonal blocks with Thyra::DefaultZeroLinearOp (I'm talking already in Thyra language).

**Comment by lxmota** [comment]
There are no plans to extend this operator, as we have moved to use a truly alternating version of the Schwarz method. It is there just in case we want to revisit this old implementation, but more likely than not, I think it will be removed at some point.
