### ISSUE TITLE
Move to an Organization

### ISSUE THREAD

**Issue by ibaned** [SNLComputation/Albany#36]
At the Albany Users Meeting there was some discussion of moving this repository to a GitHub Organization. The major benefit would be the existence of teams and the related permissions hierarchy. Unfortunately the user @albany exists meaning we cannot create an Organization by that name. Other names considered:

 - AlbanySandia
 - AlbanyMultiphysics
 - trilinos

That last one is the idea of moving the Albany repository under the existing trilinos Organization.
According to [this page](https://help.github.com/articles/repository-permission-levels-for-an-organization/), we would still have decent autonomy within the Albany repository. However, two down sides of being under trilinos are that new members can only be [added by trilinos owners](https://help.github.com/articles/permission-levels-for-an-organization/) and that teams would show up as `trilinos/LCM` instead of something like `AlbanySandia/LCM`.

If you have an opinion on this, please post it here.
@agsalin @gahansen

**Comment by bartgol** [comment]
I personally don't like the idea of using trilinos as organization, for the down sides you mentioned. I think a name of the form AlbanyXYZ is more appropriate. Perhaps AlbanyMultiphysics has the advantage of making immediately clear that Albany can handle multiphysics problems.

**Comment by ibaned** [comment]
Another choice I forgot to mention is "AlbanyCode", which has the benefit of being fewer characters (I'm pretty lazy when typing).

**Comment by ikalash** [comment]
I personally like AlbanyCode; but the other AlbanyXYZ names are fine too.

**Comment by bartgol** [comment]
If you like brevity, AlbanyLib is even fewer characters then... And it it more common to have libraries called XYZLib than XYZCode...

**Comment by ibaned** [comment]
I suppose that begs the question of whether Albany is more of a library than an application.

**Comment by ibaned** [comment]
and in turn suggests AlbanyApp as an option, although that sounds like something for a mobile phone.

**Comment by bartgol** [comment]
You're right, Albany is more of an application than a library.

As long as it's not iAlbany, an app-sounding name is not bad.

**Comment by agsalin** [comment]
AlbanySandia is my top choice so far. I am under the impression that SCOREC teammates don't mind it being associated as a Sandia code, removing my main concern about this name in that it is not inclusive to all contributors. I like it because people will instantly know they found the right repo if they are searching for it.

**Comment by ibaned** [comment]
I'm fine with that. I guess I'll try to start a vote using the thumbs-up reaction.

**Comment by albany** [comment]
Where is Albany? Is it a place in america?

**Comment by djlittl** [comment]
I believe It's a suburb of Troy, NY.

**Comment by ibaned** [comment]
[Albany, New York](https://en.wikipedia.org/wiki/Albany,_New_York) is a city in the United States. @agsalin named this scientific simulation code after that city. @djlittl made a joke, which I found pretty funny.

**Comment by gahansen** [comment]
There may be some issues with using "AlbanySandia." Our second choice appears to be "AlbanyMultiphysics" from the list above. Thoughts on "AlbanyMultiphysics?" Does anyone see any concerns or issues?

**Comment by mperego** [comment]
I like AlbanyMultiphysics. Should we make clear in the name that it is mainly a finite element code?

**Comment by bartgol** [comment]
I think the name becomes less clearer with FE in it.

**Comment by ibaned** [comment]
AlbanyMultiphysics is long to type out, but I could live with it. I agree with @bartgol to avoid acronyms/abbreviations. What about AlbanyCode as @ikalash posted ?

**Comment by mperego** [comment]
I don't have a strong opinion on this, but I prefer AlbanyMultiphysics, if we do not want to use acronyms.

**Comment by ibaned** [comment]
Okay, AlbanyMultiphysics has support from multiple people, so unless someone objects soon lets go ahead and accept that as our new choice. @gahansen, please let us know if/when we have a green light on AlbanyMultiphysics.

**Comment by gahansen** [comment]
I'll add some energy to this issue and see if we can get the ball rolling.

**Comment by bartgol** [comment]
@ibaned @gahansen @agsalin pinging you guys, to check if there's been any development on this issue.

**Comment by ibaned** [comment]
We have an organization here: https://github.com/SNLComputation

Probably the only/most tricky thing about the move will be modifying the history, if we still want to do that, to remove large files and test history. I had found a good tool for this and confirmed that it worked, you can see that research in #39 . Either myself or someone else will have to find cycles to do this cleanup. We also need to create a team and add everyone to it. I guess we can start with the team.

**Comment by bartgol** [comment]
Nice! The history can be rewritten in a second phase, right? We could set a date well in advance, and everyone should be aware of that modification.

The other question I have regards Sandia: do we have to do anything for copyright reasons in order to move to SNLComputation? If not, and all lights are green, could we set a date for this move in the _near_ future?

Perhaps we could chat about this at the telecon on Monday I will be in DC for a project meeting, but if the rest of the Albany folks have no objection, we could schedule this move in the next few weeks.

**Comment by ikalash** [comment]
Awesome, finally!!!!

**Comment by gahansen** [comment]
We just moved Albany to SNLComputation earlier today. I'll link to the announcement issue in a few minutes.

**Comment by gahansen** [comment]
Done - please see issue #415
