### ISSUE TITLE
Finite element assembly performance degradation on GPUs

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#366]
I've noticed there's been some finite element assembly performance degradation on GPUs so I wanted to document it. Here's a summary of results that I tested for ALI (GIS, 1505790 elements or 293964 nodes):

<pre>
<b>Ride, openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44, May-10-2018, w/ CUDA-Aware MPI:</b>
Full assembly-Residual: 1.816s
Albany assembly-Residual: 0.8103s
Difference: 1.01s
Full assembly-Jacobian: 23.08s
Albany assembly-Jacobian: 6.648s
Difference: 16.432

<b>White, openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88, latest, w/o CUDA-Aware MPI:</b>
Full assembly-Residual: 11.5245s
Albany assembly-Residual: 1.26301s
Difference: 10.26s
Full assembly-Jacobian: 78.336s
Albany assembly-Jacobian: 4.48413s
Difference: 73.9s

<b>White, openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88, latest, w/ CUDA-Aware MPI:</b>
Full assembly-Residual: 4.61118s
Albany assembly-Residual: 1.26241s
Difference: 3.34877s
Full assembly-Jacobian: 78.8642s
Albany assembly-Jacobian: 4.69334s
Difference: 74.2s

<b>White, openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88, old Albany, old Trilinos, w/ CUDA-Aware MPI:</b>
Full assembly-Residual: 4.878s
Albany assembly-Residual: 1.283s
Difference: 3.6s
Full assembly-Jacobian: 28.44s
Albany assembly-Jacobian: 6.735s
Difference: 21.7s

<b>White, openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88, latest Albany, old Trilinos, w/ CUDA-Aware MPI:</b>
Full assembly-Residual: 5.639s
Albany assembly-Residual: 1.406s
Difference: 4.2s
Full assembly-Jacobian: 26.84s
Albany assembly-Jacobian: 4.84s
Difference: 22.0s 
</pre>

The "Difference" in the timers is mostly Tpetra Import/Export (I'd have to run it through a profiler to make sure). You can see the assembly of the residual vector benefits from CUDA-Aware MPI but not the Jacobian because we haven't shifted to "Type 3" yet. Based on these results, it seems like I can recover the Jacobian assembly performance if I use an old Trilinos (commit trilinos/Trilinos@6b0f5572d18b7836f37a3df1cc9c2acbb512c2ac) but not the residual assembly. It's possible this won't matter too much in the future since we will probably switch to Type 3 assembly.

**Comment by bartgol** [comment]
What is 'Type 3' assembly?

**Comment by jewatkins** [comment]
From what I can tell, 'Type 3' means filling ghost elements locally on each processor to avoid performing an export of a "shared" matrix. Per our discussion with Tpetra, it may be the only way we can get better performance on the GPU.

**Comment by bartgol** [comment]
IIRC, the reason why the FE crs is not implemented, is because you don't know how much space to allocate on GPU. But wouldn't a static-graph solve this issue? Anyhow, your timings suggest the issue is indeed with import/export. I guess we just have to keep in touch with them, and see what direction they are taking.

**Comment by jewatkins** [comment]
If we don't do this already, I think we will have to move to a static graph to perform any sort of optimizations. I'm assuming they will probably make it a requirement. As you mentioned, I think all we can do is wait right now and try to keep up with changes.

**Comment by jewatkins** [comment]
Update:
<pre>
<b>Ride, openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88, latest, w/ CUDA-Aware MPI:</b>
Full assembly-Residual: 4.91614s
Albany assembly-Residual: 1.25335s
Difference: 3.7s
Full assembly-Jacobian: 71.8081s
Albany assembly-Jacobian: 4.56018s
Difference: 67.2s
</pre>

Results are pretty much the same on ride.

**Comment by bartgol** [comment]
So there was a slight improvement on Tpetra's side?

**Comment by jewatkins** [comment]
Yeah it looks like the results are a bit better. There's are large variation between ranks on the Jacobian export though:
`Albany Fill: Jacobian Export: 51.0152 - 71.0438% [100] {min=45.4449, max=63.1595, std dev=8.16875}`
so it could just be by chance.

**Comment by bartgol** [comment]
How many ranks was this run? And what test case was it?

**Comment by jewatkins** [comment]
4 ranks, GIS tets, 1505790 elements/293964 nodes, 100 residual/Jacobian evaluations

**Comment by bartgol** [comment]
That's a lot of imbalance for 4 ranks...

**Comment by jewatkins** [comment]
yeah I'm not sure what causes it but that issue has been there for some time. It was there before but less pronounced. I don't think it's load balancing because I've seen similar situations with uniform meshes with perfect load balancing.

**Comment by bartgol** [comment]
It would be interesting to see how the mesh is partitioned though. I am not sure if this can happen, but if rank 0 has to communicate only with rank 1, while rank 1 has to communicate with both 0 and 2, then it may happen that rank 0 is done much faster than rank 1...

**Comment by jewatkins** [comment]
I agree, now that I look at the CPU runs, there's a variation there too in the Jacobian export. I didn't see that in the uniform meshes so it definitely could be a load balancing issue.

**Comment by ikalash** [comment]
@jewatkins : if you load the mesh into CUBIT you should be able to easily visualize the decomposition (just load each *exo file separately and CUBIT will make it a different color; then you can export a screenshot).  The decomposition should (will) be 2D (2D mesh is partitioned before it is extruded in the z-direction) so I don't think the decomposition can be too crazy.

**Comment by jewatkins** [comment]
Doesn't look like the best partition to me but I suppose what matters is the shared node graph.
<img width="198" alt="partition" src="https://user-images.githubusercontent.com/6015007/47463878-5eca8200-d79c-11e8-9f92-b4b2e40de12f.PNG">

**Comment by ikalash** [comment]
That's interesting that there are some green elements in the yellow and pink, and some pink ones in the blue.  I assume you are using the "decomp" utility to partition the mesh?  decomp has a variety of options:
```
ikalash@camobap DTE]$ decomp --help
Usage:  decomp [-h] --processors <processor count> [-n <nemslice options>]
               [--root <root directory>] [--subdir <sub directory]
               [--multikl] [--spectral] [--inertial] [--linear]
               [--rcb] [--rcb_ignore_z] [--rib] [--hsfc] [--random] [--scattered]
               [...others...] meshfile.ext

Decomposition methods: [0..3] = speed ranking 0=fastest
              (See chaco and/or zoltan documentation for more details)
 --multikl:   [3] Multilevel KL. Gives high quality partitions.
                  Slow, high memory use.
 --spectral:  [2] use eigenvectors of a matrix constructed from the 
                  graph to partition the graph.
 --hsfc       [?] Hilbert Space-Filling Curve (uses Zoltan)
 --rib:       [?] Recursive Inertial Bisection (uses Zoltan)
 --rcb:       [?] Recursive Coordinate Bisection (uses Zoltan)
 --rcb_ignore_z:       [?] Recursive Coordinate Bisection (uses Zoltan), ignoring the z dimension coordinates
 --inertial:  [1] (default) vertices divided into sets of equal mass by planes
                  orthogonal to the principle axis. Good, fast, medium memory
 --linear:    [0] vertices in order first n/p to proc 0, next to proc 1. 
                  (fast and sometimes good).
 --random:    [0] vertices are assigned randomly to sets in a way that 
                  preserves balance.
 --scattered: [0] vertices are handed out in order with the next vertex 
                  going to whichever set is smallest.
 --brick      [-] special decomposition method; not useful for general use.
 --zpinch     [-] special decomposition method; not useful for general use.
```
You could try playing around with different decomposition methods (the options are those listed above).  It's not clear from the above (and I can't recall) what is the default.

**Comment by bartgol** [comment]
@jewatkins the blue rank only needs one set of send/recv, while the pink rank has to talk to 3 ranks. This could explain at least part of the issue. Maybe.

**Comment by jewatkins** [comment]
The colors aren't mixed in, I think the picture is just a bit too low res. It looks like the default is inertial, which is what I used (default settings). It seems there's some room to investigate what the best partitioning strategy is. Not sure if we want to spend too much time exploring it though.

**Comment by jewatkins** [comment]
@bartgol yup, it's definitely something to keep in mind at least.

**Comment by ikalash** [comment]
ah OK, I see.  I thought at first it was just the resolution but erroneously convinced myself otherwise while staring at it.

**Comment by bartgol** [comment]
@jewatkins what's the status of this?

**Comment by jewatkins** [comment]
I think I've pretty much accepted the fact that there was some performance degradation associated with the transition to a higher gcc/openmpi/cuda + other cluster changes and the Tpetra CrsMatrix export routine that was never meant to run on the GPU in the first place. I think the best path forward will be to start from a clean slate w/ the FECrsMatrix and see what happens.
