### ISSUE TITLE
Rename or remove evaluators/problems/responses whose name starts with a package name

### ISSUE THREAD

**Issue by bartgol** [SNLComputation/Albany#368]
E.g., there are a bunch of evaluators in `evaluators/*/` that are called `QCAD_*`. There are two options:

1) these files are (were) used only by QCAD. In this case, remove them (as all the QCAD code has been moved to a tag).
2) these files are used by packages other than QCAD (and at least one of them is still maintained). In this case, rename the files `PHAL_*` or `Albany_*`.

Furthermore, pay attention to conflicts. E.g., there is a `PHAL_ResponseFieldIntegral` evaluator, as well as a `QCAD_ResponseFieldIntegral` one, and they appear to do different things. If we keep the latter, we need to give it a new name, or incorporate its functionalities in the existing one.

**Comment by ikalash** [comment]
You must mean this problem: 
```
small/CoupledReactor/input_domain_coupled.xml
```
When I do git blame on it, it seems Eric Phipps is the author of the test.  Perhaps @etphipp can comment on whether that response is really needed.  My guess is the test is obsolete for the most part and there's no reason to keep the QCAD version of the field integral response.

**Comment by bartgol** [comment]
Yes, that's the test using it.

**Comment by etphipp** [comment]
This test was for some UQ research on multiphysics coupling.  I'm not sure if the coupling capabilities still exist in Albany, but if they do, you can probably remove them since they were most useful for the embedded UQ stuff (which was removed).  I have no idea if the QCAD response is used by anything else.

**Comment by bartgol** [comment]
Thanks Eric.

I'm going to try to remove them at some point, and see what happens.

**Comment by bartgol** [comment]
I think this is done. There still is a `PNP_` evaluator, but it is in `evaluators/pde`, but it is used by `Albany_PNPProblem.hpp`, and pde is a more 'relaxed' folder. Closing.
