### ISSUE TITLE
Remove STK Adapt & Rebalance (percept)

### ISSUE THREAD

**Issue by ibaned** [SNLComputation/Albany#37]
There is code in Albany to use STK Adapt and Rebalance, and it would simplify Albany if we removed it. If we instead choose to keep it, then we need to bring it up to date and start testing it because it likely does not work like it used to.

This issue is to gather opinions from Albany users, in particular if you object to its removal. Although we don't have a specific date, it is likely that within the next month a decision will be made based on feedback.

**Comment by jtostie** [comment]
There is an option is the Discretization scope, "Use Serial Mesh", that allows us to do a decomposition at runtime. I believe it is a fairly useful feature. I'd vote to keep that, provided it is not an undue burden to support. I can't say much about the stk_adapt functionality.

**Comment by ibaned** [comment]
Thanks for reminding me, I forgot to mention that the "Use Serial Mesh" feature is now supported directly by SEACAS Ioss, and so we should no longer need STK Rebalance in order to support that feature. We're definitely keeping that ability.

**Comment by jtostie** [comment]
Nice. Then I have no objections.

**Comment by bartgol** [comment]
I just ran into this issue when I was about to post another one. I believe some stuff is never going to compile, simply because it's conditional to skt_percept being in the installed trilinos packages...except that stk_percept does not exist in trilinos (anymore), just like stk_adapt.

Should we purge all the stk_percept/stk_adapt dependent stuff?

**Comment by rppawlo** [comment]
FYI - We've been talking with percept team about adding percept back to stk package - its needed by an atdm code. That could be coming soon.

**Comment by gahansen** [comment]
Closing issue, referencing issue #579 that will address this issue.
