### ISSUE TITLE
Add labels to tests

### ISSUE THREAD

**Issue by bartgol** [SNLComputation/Albany#377]
I'm not sure if others had this problem, but I sometimes want to launch only a subset of the albany tests. Typical scenario is to launch only the basic tests, or the tests of a specific package.

While it is possible to selectively launch tests by doing it from a subfolder, it would be much easier to do `ctest -L some_label`. For instance, one could do `ctest -L Analysis', to launch all tests that use AlbanyAnalysis.

I think a good general set of labels for a test could be:
- `${PACKAGE_NAME}` (or Albany, for main tests): do group tests from the same physics set
- `Tpetra` or `Epetra`: to group tests with the same *petra stack
- `Solve` or `Analysis`: to group tests that use the same Piro solve type (solve or analysis)
- `Continuation`, `Steady`, `Unsteady`: to group tests with the same solution method

Other interesting labels suggestions are welcome.

If people agree, I may add labels to the main Albany tests and LandIce tests sometime in the future.

**Comment by bartgol** [comment]
Note: each package can of course use more specific labels. For instance, LCM could have tags like 'Schwarz' or 'Plasticity'. Such labels may be used also by other packages (not likely, but possible), so if one does not want to run other packages tests, maybe could prepend 'LCM_' to the labels. This stems from the fact that ctest does _not_ offer an AND operator for labels (though it _does_ offer an OR operator, via regex).

**Comment by bartgol** [comment]
Note 2: yes, one can use `ctest -R <regex>` to filter tests. However, there are tests that have similar features (maybe features that need to be tested, following a commit), but have very different names. Perhaps I just did a commit that influences continuation problems, and I want to check one of them, without having to think which ones in the testsuite use continuation...

**Comment by ikalash** [comment]
This is a great idea.  In fact, I opened effectively the same issue ~1.5 years ago: https://github.com/gahansen/Albany/issues/114 .

**Comment by bartgol** [comment]
Bringin this back. We need to add Epetra/Tpetra labels to the tests. This allows one to run all the tests for a given linear algebra back end, by simply issuing `ctest -L Epetra` or `ctest -L Tpetra` (assuming Epetra and Tpetra are the two labels). This is extremely useful now that we are abstracting away from the petra objects, in favor of Thyra ones.

**Comment by ikalash** [comment]
This would be a very useful feature!

**Comment by bartgol** [comment]
We are trying to get this into #454, since we are already going through all the CMakeLists files due to the purgin of E/T executable dichotomy...

**Comment by bartgol** [comment]
This has been done in #454 . Of course, more labels can be added, but that PR introduced a reasonable first set of labels. Examples are "Epetra", "Tpetra", "Forward", "Analysis", "Dakota", "Demo", "Serial", "SCOREC", "Basic".
