### ISSUE TITLE
Start using Formatting Tools

### ISSUE THREAD

**Issue by ibaned** [SNLComputation/Albany#38]
I've created a Wiki page here:

https://github.com/gahansen/Albany/wiki/Formatting-Tools

Which describes `clang-format`, a tool to automatically format C++ files, and `xmllint`, a tool which automatically formats XML files.

Based on discussion in the weekly phone call, possible uses of these tools include:

 - Albany developers as a team agree on one or more `clang-format` styles that accurately match our own style(s)
    - certain packages such as LCM may want a different style, this could be supported with a file `src/LCM/.clang-format`
 - when you substantially modify a C++ file, consider using `clang-format` to also clean up the styling of it
 - when you substantially modify an XML file, consider using `xmllint` to clean up its indentation
 - we may want to go through the codebase and apply `clang-format` to most of the source
 - likewise we could apply `xmllint` to most of the `input.xml` files

As always, this issue is here to gather feedback on this. We may start to iterate on a `.clang-format` file in the near future.

**Comment by ibaned** [comment]
@agsalin @gahansen @ikalash

**Comment by ibaned** [comment]
@bgranzow

**Comment by lxmota** [comment]
For LCM we try to follow the Google C++ coding standards. For formatting, I use Eclipse with the BSD-Allman style of formatting. I'll check clang-format to see what id does.

**Comment by ibaned** [comment]
Google is one of its styles, and is the one I base my format on. One thing that might be of use is to choose a representative C++ file and we can look at it under different settings.
