### ISSUE TITLE
Failing Enthalpy test on some platforms

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#392]
It appears the Enthalpy test is failing in some of the nightlies, e.g., 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4098071&build=78620
https://my.cdash.org/testDetails.php?test=43811414&build=1569529

due to a failure to meet dependencies.  @mperego , @bartgol : is this due to some of the recent changes / PRs?

**Comment by bartgol** [comment]
Odd. I have to investigate why it didn't happen on my workstation. Seems like it should be a relatively easy fix though.

**Comment by jewatkins** [comment]
I got similar errors on my LandIce build on my workstation. For example, for the FO_GIS_Gis20km_Tpetra test:
```
 Error: PHX::DagManager::registerEvaluator() - The field "effective_pressure_basal:double:<Cell,Side,QuadPoint>(922,6,4)" that is evaluated by the evaluator named "EffectivePressure<Residual>" is already evaluated by another registered evaluator named "DOFInterpolationSide<Residual>".
```
It looks like multiple evaluators are being registered when they're not supposed to:
```
 Evaluator[27]: Name=DOFInterpolationSide<Residual>
   *Evaluated Fields:
     effective_pressure_basal:double:<Cell,Side,QuadPoint>(922,6,4)
   *Contributed Fields:
   *Dependent Fields:
     effective_pressure_basal:double:<Cell,Side,Node>(922,6,4)
     BF basal:double:<Cell,Side,Node,QuadPoint>(922,6,4,4)
...
 Evaluator[38]: Name=DOFCellToSide (effective_pressure -> effective_pressure_basal)<Residual>
   *Evaluated Fields:
     effective_pressure_basal:double:<Cell,Side,Node>(922,6,4)
   *Contributed Fields:
   *Dependent Fields:
     effective_pressure:double:<Cell,Node>(922,8)
...
 Evaluator[45]: Name=EffectivePressure<Residual>
   *Evaluated Fields:
     effective_pressure_basal:double:<Cell,Side,QuadPoint>(922,6,4)
   *Contributed Fields:
   *Dependent Fields:
     Hydraulic-Over-Hydrostatic Potential Ratio:double:<Dim>(1)
     ice_overburden_basal:double:<Cell,Side,QuadPoint>(922,6,4)
```
Maybe because of line 951 in LandIce_StokesFOBase?
```
if (is_dist_param["effective_pressure"] || !has_ss_input[ssName]["effective_pressure"])
```
I think `count()` is needed to check if a map key exists; otherwise, I think the key may get created. 

The current implementation seems to work with gcc>7 and intel builds but it breaks my gcc 6.1.0 build using sems modules for some reason. @bartgol what compiler are you using?

**Comment by jewatkins** [comment]
Sounds good, thanks. I didn't realize it was because of a recent change in Trilinos.

**Comment by ikalash** [comment]
It looks like this is a separate issue from the rest of the LandIce tests.  Last night I added the configure flag:
```
-D Phalanx_ALLOW_MULTIPLE_EVALUATORS_FOR_SAME_FIELD:BOOL=ON
```
to my Trilinos, and the test still fails.  @bartgol , is the fix in your PR (https://github.com/SNLComputation/Albany/pull/412) ?

**Comment by bartgol** [comment]
With #412 in, I _think_ the test will now pass (it does on my workstation). Reopen if the nightlies disagree.
