### ISSUE TITLE
Failing Peridigm build

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#394]
It looks like the Peridigm build has been failing since it was created on 11/9/18: 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=77971

**Comment by ikalash** [comment]
I'd like to revive this issue, since it is going to be relevant very soon with the refactor @bartgol and I are doing to remove Petra from Albany and replace it with Thyra.  

What are the plans for reviving Peridigm and corresponding timeframe for doing so?  Peridigm has a ton of Petra in it and currently does not compile.  I would not feel comfortable removing Petra from Peridigm knowing that there are issues preventing the code from compiling even with the Petra there.  Perhaps if it isn't clear when Peridigm will be revived, we should discuss moving it to a tag?  Tagging @mperego , @djlittl .

**Comment by djlittl** [comment]
There's really no hope of refactoring the Peridigm coupling anytime soon.  I think moving it to a tag is the best idea.

**Comment by bartgol** [comment]
The question is, when to we tag it? Not current master, obviously, since it's failing. Do we know when it was working?

**Comment by mperego** [comment]
@djlittl can we tag the branch you are working on?

**Comment by ikalash** [comment]
FYI - I turned off this build on the CEE since Peridigm will be moving to a tag soon.

**Comment by ikalash** [comment]
Peridigm is being removed in the unpetrify_branch (moved to a tag) and I've disabled the nightly testing which has been failing for months if not years.  Therefore closing this issue.
