### ISSUE TITLE
Albany moved to the SNLComputation organization today!

### ISSUE THREAD

**Issue by gahansen** [SNLComputation/Albany#415]
Per discussion of issue #36 , we moved Albany from "gahansen" to "SNLComputation" earlier today.

All users need to reset their repos (tests scripts, etc) to reflect the new path. To reset the repo path in git, please use:

`git remote set-url origin git@github.com:SNLComputation/Albany.git`

Please let a team member know if you have any access issues or questions about the move.

**Comment by mperego** [comment]
@gahansen I cannot push to the repo.

**Comment by mperego** [comment]
sorry I'm an idiot.. I misspelled origin and I thought it was an issue with permissions..

**Comment by ikalash** [comment]
No problem, it happens :).  Glad to hear it works now!
