### ISSUE TITLE
FO_GIS_GisCoupledThicknessTpetra  timeout on Ride

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#420]
The test with the name FO_GIS_GisCoupledThicknessTpetra  is timing out on Ride: 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4198727&build=79751

I tried mucking with various things including raising the ctest time to timeout time (up to 4800!) and it still times out.  We cannot increase the workset size, because if we do, there is a memory allocation problem (things don't fit on the GPU).  @jewatkins can you please have a look at this and decide or propose+post here what we can do about this test?  I suppose one option is to turn it off on the GPU; perhaps there are better ones?

**Comment by jewatkins** [comment]
The timer output on waterman shows that a majority of the time is being spent in ThicknessResid. It's pretty substantial on CPU runs too. It' might be because of all the temporary view allocations. It'd probably be best to move those to postRegistrationSetup but I'm not sure. @mperego @bartgol Is the FO_GIS_GisCoupledThicknessTpetra testcase something we want to support for the GPU right now or should we wait until we have a viable strategy for sidesets?

**Comment by jewatkins** [comment]
The timings on CPU, cee compute node, intel build (overall run is 12s):
```
Phalanx: Evaluator 82: [<Residual>] ThicknessResid<Residual>: 1.43381 - 66.8566% [91] {min=1.41021, max=1.4617, std dev=0.0212621}
Phalanx: Evaluator 168: [<Jacobian>] ThicknessResid<Jacobian>: 1.42469 - 20.6387% [70] {min=1.41344, max=1.44652, std dev=0.0148421}
```
on GPU, waterman, gcc build (overall run is 731s):
```
Phalanx: Evaluator 82: [<Residual>] ThicknessResid<Residual>: 274.205 - 94.8779% [91] {min=269.117, max=277.972, std dev=3.90668}
Phalanx: Evaluator 168: [<Jacobian>] ThicknessResid<Jacobian>: 222.834 - 59.785% [70] {min=220.066, max=223.927, std dev=1.8528}
```

**Comment by bartgol** [comment]
Is this still happening?

**Comment by ikalash** [comment]
Yes.  I think Jerry was looking for some feedback from you and Mauro about how to proceed.  The decision could be to deactivate the test on GPUs.

**Comment by bartgol** [comment]
I have to take a look. Hopefully today.

**Comment by ikalash** [comment]
That would be great, thanks Luca!

**Comment by ikalash** [comment]
Are there any plans to resolve this issue?  If not, we should turn off the problematic test on Ride.

**Comment by bartgol** [comment]
I completely forgot about this. I'll try to carve some time this week.

**Comment by ikalash** [comment]
That would be great, thanks Luca!  Could you please also look at the undefined reference issues (#426 and #429 ) with an intel compiler?  I'd like these builds fixed before we merge any more big PRs into the code.

**Comment by bartgol** [comment]
Those I already looked at, and have no idea why we get them. The code looks legit. Would be great if someone else could take a look at that too. Maybe there's something I am missing.

**Comment by ikalash** [comment]
@jewatkins : could you please look into this issue?  It happens on blake (for example) which you are familiar with.

**Comment by jewatkins** [comment]
Yeah I can take a look, what's the path for the Trilinos build on blake?

**Comment by ikalash** [comment]
Thanks @jewatkins .  On ride , the Trilinos builds can be found here: /home/projects/albany/nightlyCDashTrilinosBlake .  The same error was showing up on skybridge, but it looks like last night there was some intel-related licensing issue.

**Comment by ikalash** [comment]
That was supposed to say blake not ride - just corrected.

**Comment by mperego** [comment]
@ikalash I don't have time at the moment to look into that and we are not using that capability. So I'm all for deactivating it on CUDA builds. 
In the next months I'll start working on this and I can look into it. I suspect that it takes so long because in this test the Fad derivatives are large because the DOFs on each ice column are coupled.

**Comment by ikalash** [comment]
That's fine - thanks.  I have been meaning to comment about whether we should deactivate the test.

**Comment by mperego** [comment]
@ikalash thanks!

**Comment by ikalash** [comment]
Seems this has gone away - closing.
