### ISSUE TITLE
Albany build error due to undefined reference in SCOREC namespace

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#421]
It looks like several of the Albany builds are failing due to an undefined reference in a SCOREC library: 
```
repos/Trilinos/SCOREC/apf/apf.cc:287: undefined reference to `apf::MatrixElement::grad(apf::Vector3 const&, apf::Vector<27ul>&)'
```
(http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=80041) .  Could one of the SCOREC guys or @ibaned please have a look and resolve the issue?

**Comment by ikalash** [comment]
@JustinClough if you could have a look at this issue per the discussion at the meeting today, that would be great.

**Comment by ikalash** [comment]
It looks like this issue has cropped up in all the nightlies, increasing the urgency of getting it resolved: 

http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany

I could always turn off SCOREC, but I think we want that tested.

**Comment by JustinClough** [comment]
I commented on the SCOREC version of the issue here: https://github.com/SCOREC/core/issues/206#issuecomment-453314366 

In short, I think Cameron was able to fix the issue.

**Comment by ibaned** [comment]
Confirmed, there are no compile errors on the board this morning.

**Comment by ikalash** [comment]
So, not too fast - I turned off SCOREC in my builds a few days ago.  Let me turn it on and check if the issue is resolved.

**Comment by ikalash** [comment]
So on my Fedora 29 workstation when I turn on SCOREC in Trilinos and Albany, I am still getting the error: 
```
[ 14%] Building CXX object src/ATO/CMakeFiles/ATO.dir/evaluators/ATO_TensorPNormResponse.cpp.o
/usr/bin/ld: /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/install/lib/libapf.so.12.13: undefined reference to `apf::MatrixElement::grad(apf::Vector3 const&, apf::Vector<27ul>&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/LCM/CMakeFiles/utMiniSolversROL.dir/build.make:233: src/LCM/utMiniSolversROL] Error 1
make[1]: *** [CMakeFiles/Makefile2:2101: src/LCM/CMakeFiles/utMiniSolversROL.dir/all] Error 2
```
Could it be that I need to set an extra library path?  It's strange that this would show up on my machine but it has been fixed on the CEE.

**Comment by ibaned** [comment]
Can you check the SHA1 of your `Trilinos/SCOREC` clone?

**Comment by ikalash** [comment]
It is this one: 9e4b9fb76afbcf2e195b6ae2d135287a753adbfe .  My scripts are cloning SCOREC as follows: 
```
git clone git@github.com:SCOREC/core.git SCOREC 
```

**Comment by ibaned** [comment]
@cwsmith @JustinClough it looks like the fix is in SCOREC `develop` but not `master`. Is the automerge system broken again?

**Comment by ikalash** [comment]
Interesting, I didn't realize SCOREC had a develop branch.  I could switch to it in my nightlies if it's fairly stable.

**Comment by ibaned** [comment]
No, I would stick to master. I put in place a system that is supposed to automatically merge develop into master.

**Comment by cwsmith** [comment]
The filesystem we run the nightly test and merge is down (fasttmp).  I'll manually run the test and merge, then move the nightly working directory to a different filesystem.

**Comment by ikalash** [comment]
Thanks for the info.  Any idea when develop will be merged into master?  

BTW, I think the fact that the CEE nightlies are running correctly now means that they use develop SCOREC rather than master.

**Comment by cwsmith** [comment]
It would be done by now...  but our other filesystem is now acting up :1st_place_medal: 

I'll post here when the merge is done; hopefully later tonight or tomorrow morning.

Sticking with `master` as the testing branch is preferred. `develop` is tested post-commit and is more likely to be broken than master.

**Comment by cwsmith** [comment]
develop has been merged into master
https://github.com/SCOREC/core/commits/master

**Comment by ikalash** [comment]
It looks like all is good again on my workstation.  Thanks for resolving the issue!
