### ISSUE TITLE
Undefined reference to LandIce routine

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#426]
Some of the nightly builds failed due to an undefined reference to a LandIce routine:

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=80886

@bartgol , can you please look into / fix this?

**Comment by bartgol** [comment]
This is _very_ odd. I suspect gcc closed an eye and allowed me to do something not strictly standard. However, looking at the Integral1Dw_Z evaluator I do not see why the ETI should now work there. I'll dig a bit.

**Comment by bartgol** [comment]
I can compile both on my workstation with gcc and on skybridge with intel. It is not a compiler problem, I think. I don't have access to that machine. so I can't investigate thoroughly.

**Comment by ikalash** [comment]
@bartgol : do you have access to blake?  The issue shows up there with the intel compiler: https://my.cdash.org/viewSubProjects.php?project=Albany .

**Comment by bartgol** [comment]
I have access to blake. I'll check your folder. Just make sure it's readable for others.

**Comment by ikalash** [comment]
Everything should be accessible by members of the wg-albany metagroup, which you should be a part of.  Please let me know if you are not able to access the directory

**Comment by mperego** [comment]
Although this issue was cause by Luca's push, it seems pretty subtle, and it's not clear how to fix it.
It would be great if somebody experienced with intel compilers (@gahansen @ibaned @ikalash ?) could have a look at this.
It's not high priority.

**Comment by mperego** [comment]
@ikalash what's peculiar about this build? e.g. shared vs static libraries, DFad or SLFad, w/ w/out Epetra, etc. Thanks.

**Comment by ikalash** [comment]
@mperego : I think you correctly identified that the builds with this error (blake, AlbanyIntel, albany_cluster-toss3_skybridge-login5_serial-intel-release) are all using an intel compiler.   

The AlbanyIntel build has FPE checking on and is building static libraries.  Epetra is on.  

albany_cluster-toss3_skybridge-login5_serial-intel-release is building shared libraries.  FPE checking is off.  Epetra is on.  

For the blake builds, we're building static libraries, FPE checking is off, Epeetra is on. 

The default Fad type is used in all the builds.

It seems the only thing they have in common is that they use the Intel compiler.

**Comment by mperego** [comment]
@ikalash Thanks!

**Comment by bartgol** [comment]
I don't think Intel _per se_ is the issue. I compiled on skybridge with 18.0.0 and didn't get the link error.

**Comment by ikalash** [comment]
@jewatkins fixed this with his commit last night.
