### ISSUE TITLE
Issue with Symmetric Dirichlet conditions

### ISSUE THREAD

**Issue by mperego** [SNLComputation/Albany#427]
I was working on implementing the DistParamDeriv specialization for the SDBC conditions, and I encountered an issue with the current implementation of SDBC.
The problem is that the unknown x does not satisfy the boundary conditions during the **first** call of the residual. Normally this is not a big issue because in subsequent Newton iterations x will be set correctly to satisfy the boundary conditions and the problem will converge to the right solution.
However we are "wasting" the first iteration (this explains why linear problems do not converge in one step, as reported in issue #310) and, more importantly, if the problem is homogeneous, and the initial guess is zero (default) then the first residual will be zero and NOX will converge right away to the wrong trivial solution (that does not satisfy Bcs).
This can be tested by taking the test
`vSteadyHeatConstrainedOpt2D_Conductivity_Dist_ParamT`
and converting all the DBC to SDBC.

A possible solution might be to set the x to satisfy the bc condition in a preEvaluate phase, before computing the residual. We usually do not use the `preEvaluate` method of the Phalanx evaluators, but in this case it might save us.
@ikalash would  you mind having a look into this?

**Comment by ikalash** [comment]
@mperego , oh yes, this.  I am aware of the situation you describe.  The double evaluation of the residual occurs in the SDBCImpl routines, e.g., https://github.com/SNLComputation/Albany/blob/master/src/Albany_Application.cpp#L3651 .  

The issue with trying to move the setting of x values corresponding to DBCs to ```preEvaluate``` is that the ```preEvaluate``` would happen for the *local* residual/solution, whereas we would need to apply the BC to the global residual/solution.

**Comment by bartgol** [comment]
@ikalash I don't think Mauro meant to move the code in evaluateFields to preEvaluate. I think he meant this:

1) the pre-evaluate would only take care to set the valule of the solution.
2) the evaluateFields call will take care of setting the residual.

**Comment by ikalash** [comment]
@bartgol : I understand.  preEvaluate operates at the element level, no?  If that’s true I don’t think it’s straightforward to set the solution x there unless there is a homogeneous DBC.

**Comment by bartgol** [comment]
Well, both preEvalute and evaluateFields operate at the _workset_ level. But the workset contains all you need (otherwise you wouldn't be able to set the bc in evaluateFields either).

The idea is to grab x from the ws in preEvaluate, and set the bc. Then in evaluateFields you only operate on f.

**Comment by ikalash** [comment]
I see.  Let me take a look at it when I return to the office on Monday (on a plane right now).  It would be great to clean up the sdbc code in Albany application.

**Comment by mperego** [comment]
Thanks @ikalash and @bartgol for following on. Yes. that's the idea, I hope it works. There is no rush, but as soon as it gets fixed  I'll convert some of the tests to use SDBC, and I'l try to implement the tangent derivatives as well so that we can compute sensitivities of parameters used as dirichlet BCs.

The reason why I started looking into it is that, for symmetric problems, the adjoint is much harder to be solved when we use standard DBCs, and, in particular for the FO solver, the ML preconditioner struggles a lot.

**Comment by ikalash** [comment]
@mperego : I'll look at it next week.  I really hate the way the SDBCs are done now...  Last time I looked at it, I somehow convinced myself that the x needs to be changed at the level of the global system, but I think Luca's right that all the info to get the global values should be accessible from the workset.

**Comment by ikalash** [comment]
I believe I have fixed this issue in commit 861e1edd70f1a17d5681f8592cd1a7fa3f80fc8b to master.  Now the setting of the solution for the SDBCs is handled by a preEvaluate routine.  The new design does not require code repetition within computeGlobalResidualImpl, as we had before.  @mperego please give the new code a try - hopefully it will fix the issues you were having with your DistParamDerivs.

**Comment by mperego** [comment]
Thanks @ikalash! 
Unfortunately I still notice weird behaviors when I use SDBC in the test `SteadyHeatConstrainedOpt2D_Conductivity_Dist_ParamT`.

If you take the input file `input_conductivity_dist_paramT.yaml` and convert the first DBC condition to SDBC, you'll notice that the NOX residual stall at 2.236e+00 after the first iteration.
This has nothing to do with the dist parameters, you can remove the dist parameters from the input file and you'll still have the same behavior.

**Comment by ikalash** [comment]
Hmmm.  By "weird behavior", do you mean just the Newton stalling, or there is something else you have observed?  I can take a look - sorry about that.

**Comment by mperego** [comment]
Yes.. it is also weird because depending on how many boundary conditions you convert to SDBC, you get the test failing or not.

**Comment by ikalash** [comment]
Interesting.  Is the behavior the same as before my changes over the weekend, out of curiosity?  

I'll take a look at this sometime this week.  It's good that the problem uses the STK2d discretization method, since I'll easily be able to make the problem smaller for the purpose of debugging.

**Comment by mperego** [comment]
It changed. Now if you convert all the DBC to SDBC it works (except for sensitivities, but that could be related to dist param deriv). Before, NOX solver would converge to the trivial solution right away.

**Comment by ikalash** [comment]
Ah good, OK.  So it works in the sense that it doesn't just compute ||F||=0 and exit, but it doesn't work in the sense that it doesn't converge - did I get that right?

**Comment by mperego** [comment]
Yeah. Sometimes it even converges.. it depends on how many and which of the 4 DBC you convert to SDBC..

**Comment by ikalash** [comment]
OK, I'll look into it.  Thanks for the info.

**Comment by bartgol** [comment]
Could it be related to a race condition in the SDBCs? I know that test has all Dirichlet BCs, which are not compatible at their interface. Seems weird, but who knows. What happens if you make their values compatible?

**Comment by ikalash** [comment]
Oh yes, it could be something like this!  One issue with the SDBCs which both @lxmota and @tjfulle have encountered is there can be an issue at nodes that belong to more than 1 nodeset.  If the value to be prescribed is the same for both nodesets, the SDBC will work fine.  If not, it will set whatever value it gets during the last call to preEvaluate.  Is it possible that this situation is arising here @mperego ?  You could easily check it I suppose by prescribing compatible BCs and seeing what happens.

**Comment by mperego** [comment]
good catch! Yes, it seems that's the problem. I will modify STK2d MeshStruct so that it generates node sets that do not overlap.
Closing the issue for now. Thanks!

**Comment by ikalash** [comment]
Please keep me posted.  I hope that is the issue!  It would explain why you get good convergence if you don't set SDBC on all the edges.  We should probably have some kind of exception checking probably to prevent the user from specifying non-matching DBCs at a given node, something @tjfulle has brought up too.

**Comment by bartgol** [comment]
I don't know if we should prohibit non-matching Dirichlet bcs. I haven't made up my mind yet on whether prescribing non-matching bcs is ok or not.

/* Thinking out lout */

I think mathematically it makes sense (so long as the overlap of the two boundaries has dimension N-2, with N being the dimension of the mesh). Still, there's something in it that sounds not right. After all, if u is a solution, changing its value on a N-2 dimensional set should still yield a solution that satisfy the boundary value problem.

Given the above, it appears we should be able to select whatever order we want for the dbcs, so long as it is always the same. Changing the order randomly at every iteration (or, worse, having different orders in jacobian and residual, which I think it's what was happening) may lead to oscillatory/stagnating behaviors. If we can come up with a way of 'ordering' dirichlet bcs in the PHX field manager, we could probably allow mismatching DBCs...

**Comment by mperego** [comment]
I think that the issue I was seeing was caused by the fact that SDBC and DBC were trying to modify the same dof of the Residual. The first would put 0 at the residual entry, whereas the second would overwrite it with x-x_d.. and the solver stopped converging.

**Comment by bartgol** [comment]
Ah, that's a good point. I think in general we _should_ prohibit to mix DBC and SDBC. The whole point of SDBC is to get a symmetric pattern; if you mix SDBC with DBC you lose that. So we should definitely prohibit a mix. This should be 'easy' to enforce in the BCUtils class, when we parse the DBCs sublist.
