### ISSUE TITLE
Trilinos failure in nightlies using intel compiler 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#428]
Looks like the intel builds started failing with the following error:
```
CMake Error at /home/projects/x86-64/cmake/3.10.2/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/home/projects/x86-64-skylake/openmpi/2.1.2/intel/18.1.163/bin/mpicc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/projects/albany/nightlyCDashTrilinosBlake/build/TriBuildSerial/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/gmake" "cmTC_6f4a9/fast"
    /usr/bin/gmake -f CMakeFiles/cmTC_6f4a9.dir/build.make CMakeFiles/cmTC_6f4a9.dir/build
    gmake[1]: Entering directory `/home/projects/albany/nightlyCDashTrilinosBlake/build/TriBuildSerial/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_6f4a9.dir/testCCompiler.c.o
    /home/projects/x86-64-skylake/openmpi/2.1.2/intel/18.1.163/bin/mpicc   -mkl    -o CMakeFiles/cmTC_6f4a9.dir/testCCompiler.c.o   -c /home/projects/albany/nightlyCDashTrilinosBlake/build/TriBuildSerial/CMakeFiles/CMakeTmp/testCCompiler.c
    
    Error: A license for Comp-CL is not available now (-15,570,115).
    ```
This seems to affect the blake builds (https://my.cdash.org/viewSubProjects.php?project=Albany&date=2019-02-07), and the skybridge + CEE intel (AlbanyIntel) builds (http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&date=2019-02-07).  Did something change with the modules / compilers?  Need to look into.

**Comment by bartgol** [comment]
Probably one of the two: 1) there was a network problem which prevented icpc to verify the licence on the server where it's stored, or 2) there was an update to filesystem and they forgot to make sure licences were reachable from the new filesystem.

Let's wait another day and see if it continues.

**Comment by ikalash** [comment]
Ah ok thanks for the info.  Yes hopefully the issue will get resolved in its own.
