### ISSUE TITLE
Turn off ceerws1006 nightlies

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#430]
@lxmota can you please deactivate your scripts that were running nightlies on ceerws1006 so that they stop posting to the CDash site?  Currently there are blank entries that look like: 

```
trilinos__ceerws1006_--
albany__ceerws1006_-- 
```
(http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany) .

**Comment by lxmota** [comment]
Deactivated while I investigate why they are failing. It seems that the CEE environment changed significantly.
