### ISSUE TITLE
Switch SCOREC std::mesh::put_field calls to new syntax (old one has been deprecated) 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#438]
Per the discussion in this Trilinos issue: https://github.com/trilinos/Trilinos/issues/4470#issuecomment-466412297 , the STK mesh team have recently depracted the old usage of the ```stk::mesh::put_field``` routine, which appears throughout SCOREC.  This will cause a compilation error unless one adds the following configure line to one's Trilinos: 
```
  -D STK_HIDE_DEPRECATED_CODE:BOOL=OFF \
```
(SCOREC team @maxrpi , @cwsmith , @JustinClough : FYI).  

I think longer-term it makes sense to switch the code to the new syntax.  Here is an example of the sorts of changes that are required:
 ```
-   stk::mesh::put_field( *facesField_ , metaData_->universal_part(), getDimension());
-   stk::mesh::put_field( *processorIdField_ , metaData_->universal_part());
-   stk::mesh::put_field( *loadBalField_ , metaData_->universal_part());
+   stk::mesh::put_field_on_mesh( *facesField_ , metaData_->universal_part(), getDimension(),nullptr);
+   stk::mesh::put_field_on_mesh( *processorIdField_ , metaData_->universal_part(),nullptr);
+   stk::mesh::put_field_on_mesh( *loadBalField_ , metaData_->universal_part(),nullptr);
```
You can find more info in the discussion under the Trilinos issue mentioned above.  Can one of the SCOREC developers (@ibaned perhaps since you are familiar with both SCOREC and STK) switch SCOREC over to the new put_field syntax? 

We had an issue with 4.8 compilers. See commit cf5e5a3 if you need gcc 4.8 in Albany.

**Comment by ibaned** [comment]
https://github.com/SCOREC/core/pull/215

**Comment by ikalash** [comment]
@cwsmith : has this been resolved?  I ended up turning SCOREC off in some of the nightlies.  I will turn it back on once things are compatible with the new stk::mesh syntax.

**Comment by cwsmith** [comment]
@ikalash Yes. I merged Dan's changes.

**Comment by ikalash** [comment]
Nightlies look good, so closing issue.
