### ISSUE TITLE
Errors stemming from merge of PR #396 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#439]
There are a number of issues stemming from merging in this PR: 

```
[ 32%] Building CXX object src/LandIce/CMakeFiles/LandIce.dir/evaluators/LandIce_HydrologyWaterThickness.cpp.o
/.../repos/Albany/src/utility/Albany_EpetraThyraUtils.cpp: In function 'Teuchos::RCP > Albany::createTeuchosComm(const Epetra_Comm&)':

repos/Albany/src/utility/Albany_EpetraThyraUtils.cpp:25:10: error: 'createTeuchosCommFromEpetraComm' was not declared in this scope

   return createTeuchosCommFromEpetraComm(comm);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=81887

```
[  3%] Linking CXX executable utMiniSolvers
/.../repos/Albany/src/LandIce/interface_with_cism/ali_driver.cpp: In function ‘void ali_driver_run(AliToGlimmer*, double&, double)’:

repos/Albany/src/LandIce/interface_with_cism/ali_driver.cpp:879:15: error: ‘printTpetraVector’ is not a member of ‘Albany’

       Albany::printTpetraVector(*out << "\nParameter vector " << i << ":\n",
```
```


repos/Albany/src/LandIce/interface_with_cism/ali_driver.cpp:901:18: error: ‘printTpetraVector’ is not a member of ‘Albany’

          Albany::printTpetraVector(*out << "\nResponse vector " << i << ":\n", g);
                  ^~~~~~~~~~~~~~~~~
```
Can you please look at these @bartgol?  The second set of issues seems to be due to new routines having not been propagated into the CISM-Albany interface file ali_interface.cpp.  The first one is general to all the builds.

**Comment by bartgol** [comment]
I think I know what's the issue. Was the build a Tpetra-only build? I think I forgot to guard all the utils to check for Epetra before trying to call all the epetra stuff. That's why the `createTeuchosCommFromEpetraComm` is not seen in `Albany_Utils.hpp`. I'll push a ninja fix straight to master, if that's ok.

**Comment by bartgol** [comment]
BTW, if you use Epetra, now you also need `-D Trilinos_ENABLE_ThyraEpetraAdapters:BOOL=ON`, or else you're gonna get compiler errors... Switching to Thyra comes at this (small) price: the adapters for your backend must be enabled.

**Comment by ikalash** [comment]
@bartgol: The Tpetra-only build should be good now (after my push just now to fix the CISM interface) but I'm still getting undefined references in the Tpetra + Epetra build on my machine:
```
[ 96%] Linking CXX executable Albany
/usr/bin/ld: warning: libmpi.so.12, needed by /usr/local/netcdf/lib/libnetcdf.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::getConstEpetraMultiVector(Teuchos::RCP<Thyra::MultiVectorBase<double> const>, bool)'
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::getEpetraMap(Teuchos::RCP<Thyra::VectorSpaceBase<double> const>, bool)'
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::getConstEpetraVector(Teuchos::RCP<Thyra::VectorBase<double> const>, bool)'
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::getConstEpetraMatrix(Teuchos::RCP<Thyra::LinearOpBase<double> const>, bool)'
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::createTeuchosComm(Epetra_Comm const&)'
collect2: error: ld returned 1 exit status
/usr/bin/ld: warning: libmpi.so.12, needed by /usr/local/netcdf/lib/libnetcdf.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::getConstEpetraMultiVector(Teuchos::RCP<Thyra::MultiVectorBase<double> const>, bool)'
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::getEpetraMap(Teuchos::RCP<Thyra::VectorSpaceBase<double> const>, bool)'
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::getConstEpetraVector(Teuchos::RCP<Thyra::VectorBase<double> const>, bool)'
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::getConstEpetraMatrix(Teuchos::RCP<Thyra::LinearOpBase<double> const>, bool)'
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::createTeuchosComm(Epetra_Comm const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/LCM/CMakeFiles/NodeUpdate.dir/build.make:256: src/LCM/NodeUpdate] Error 1
make[1]: *** [CMakeFiles/Makefile2:2955: src/LCM/CMakeFiles/NodeUpdate.dir/all] Error 2
make[2]: *** [src/LCM/CMakeFiles/BoundarySurfaceOutput.dir/build.make:256: src/LCM/BoundarySurfaceOutput] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2330: src/LCM/CMakeFiles/BoundarySurfaceOutput.dir/all] Error 2
/usr/bin/ld: warning: libmpi.so.12, needed by /usr/local/netcdf/lib/libnetcdf.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::getConstEpetraMultiVector(Teuchos::RCP<Thyra::MultiVectorBase<double> const>, bool)'
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::getEpetraMap(Teuchos::RCP<Thyra::VectorSpaceBase<double> const>, bool)'
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::getConstEpetraVector(Teuchos::RCP<Thyra::VectorBase<double> const>, bool)'
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::getConstEpetraMatrix(Teuchos::RCP<Thyra::LinearOpBase<double> const>, bool)'
/usr/bin/ld: ../libalbanyLib.so: undefined reference to `Albany::createTeuchosComm(Epetra_Comm const&)
```

**Comment by ikalash** [comment]
Here's a summary of what's still broken in the nightlies due to this problem by build: 

IKTAlbanyFunctorOpenMP, albany_Fedora_proxima.ca.sandia.gov_serial-gcc-release, albany_Fedora_algol.ca.sandia.gov_serial-clang-release, albany_cluster-toss3_skybridge-login5_serial-intel-release, IKTAlbanyFPECheckDbg: 
```
/usr/bin/ld: libalbanyLib.a(Albany_ThyraUtils.cpp.o): in function `void Albany::writeMatrixMarket const>(Teuchos::RCP const> const&, std::__cxx11::basic_string, std::allocator > const&, int)':

Albany_ThyraUtils.cpp:(.text+0x20dd): undefined reference to `Albany::getConstEpetraVector(Teuchos::RCP const>, bool)'

Albany64BitDbg:
```
[ 34%] Building CXX object src/LCM/CMakeFiles/LCM.dir/evaluators/surface-element/SurfaceScalarGradientOperator.cpp.o
/.../repos/Albany/src/utility/Albany_EpetraThyraUtils.cpp: In function 'Teuchos::RCP > Albany::createTeuchosComm(const Epetra_Comm&)':

repos/Albany/src/utility/Albany_EpetraThyraUtils.cpp:25:10: error: 'createTeuchosCommFromEpetraComm' was not declared in this scope
```

NERSC, blake (would we get this error if the ThyraEpetra/Tpetra adapters are off?  that might be the problem for the NERSC/blake nightlies):
```

/usr/bin/ld: Albany_ThyraUtils.cpp:(.text+0x470f): undefined reference to `Albany::createTeuchosComm(Epetra_Comm const&)'            

  /usr/bin/ld: libalbanyLib.a(Albany_ThyraUtils.cpp.o): in function `void Albany::writeMatrixMarket<Thyra::VectorSpaceBase<double> const>(Teuchos::RCP<Thyra::VectorSpaceBase<double> const> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
--
```
@bartgol : can you please have a look at these issues?

**Comment by bartgol** [comment]
I'll work on that later today.

**Comment by ikalash** [comment]
Thanks, @bartgol .  I'm happy to test your fix again when it's ready.  You may need to edit the include or link lines for some of the specialized LCM executables which encounter the undefined ref error in the output I posted earlier to include the relevant files in the src/utility directory.  That might not be the only problem, but that was something that occurred to me when I was looking at it.  Perhaps you didn't encounter the problem b/c you weren't building those exes.

**Comment by ikalash** [comment]
I think I resolved this last night even though some of the nightlies were messed up.  I will reopen if that's not the case based on tomorrow's nightlies.
