### ISSUE TITLE
Summarize Albany builds/configurations to Trilinos development team towards augmenting Trilinos nightly testing

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#441]
At the SART meeting this morning, there was a request by @jwillenbring and @maherou to summarize the Albany nightly testing that is currently done, in particular the compilers used and any special options.  I have gone through our nightly CDash sites (https://my.cdash.org/viewSubProjects.php?project=Albany and  http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany ) and compiled such as summary.  

Here it is - in particular, I list which compilers we use on different testbed in our nightly testing, as well as some of the unique testing options in each build.

CEE:
- AlbanyIntel build (cee-compute018): Intel 18.0.3.20180410, Serial KokkosNode, static libs, FPE checking enabled, with SCOREC 
- Albany64Bit (cee-compute013): GNU 8.1.0, Serial KokkosNode, static libs, FPE checking enabled, with SCOREC
- Albany64BitClang (cee-compute016): Clang 7.0.0, Serial KokkosNode, static libs, FPE checking enabled
- Albany64BitDbg (cee-compute020): GNU 8.1.0, Serial KokkosNode, static libs, all-debug build, FPE checking enabled, with SCOREC
- Albany64BitClangDbg (cee-compute012): Clang 7.0.0, Serial KokkosNode, static libs, all-debug build, FPE checking enabled 

Fedora: 
- IKTAlbany (camobap.ca.sandia.gov):  GNU 8.2.1, Serial KokkosNode, shared libs, with SCOREC, with DTK
- IKTAlbanyNoEpetra (camobap.ca.sandia.gov):  GNU 8.2.1, Serial KokkosNode, shared libs, with SCOREC, with DTK
- IKTAlbanyFunctorOpenMP (camobap.ca.sandia.gov): GNU 8.2.1, OpenMP KokkosNode, shared libs
- IKTAlbanyFPECheckDbg (camobap.ca.sandia.gov):  GNU 8.2.1, Serial KokkosNode, shared libs, all-debug build, FPE checking enabled, with SCOREC, with DTK
- albany_Fedora_proxima.ca.sandia.gov_serial-gcc-release (proxima.ca.sandia.gov): GNU 8.2.1, Serial KokkosNode, shared libs, with DTK
- albany_Fedora_algol.ca.sandia.gov_serial-clang-release (algol.ca.sandia.gov): Clang 7.0.1, Serial KokkosNode, shared libs, with DTK

Skybridge: 
- albany_cluster-toss3_skybridge-login5_serial-intel-release (skybridge-login5): Intel 17.0.4.20170411, Serial KokkosNode, shared libs 

GPU testbeds:
- IKTRideAlbanyCUDA (ride - P100 GPUs: Power8, Pascal 60): GNU 7.2.0, CUDA 9.2.88, CUDA KokkosNode, static libs 
- IKTWatermanAlbanyCUDA (waterman - Volta GPUs: Power9, Volta 70): GNU 7.2.0, CUDA 9.2.88, CUDA KokkosNode, static libs 

Blake (skylake):
- IKTBlakeAlbanySerial (blake): Intel 18.0.1.20171018, Serial KokkosNode, static libs
- IKTBlakeAlbanyOpenMP (blake): Intel 18.0.1.20171018, OpenMP KokkosNode, static libs 

NERSC:
- EdisonAlbanyFELIX (edison.nersc.gov): GNU 7.3.0, 2.5.15 C, Serial KokkosNode, static libs 
- CoriAlbanyFELIX (cori.nersc.gov): GNU 7.3.0, 2.5.15 C, Serial KokkosNode, static libs 

Mayer (ARM):
- IKTMayerARMTrilinos (mayer2): GNU 7.2.0, Serial KokkosNode, static libs 

NOTE: the builds with DTK enabled need to have ```-D Tpetra_INST_INT_UNSIGNED_LONG:BOOL=ON``` to enable a build with ETI ON.

Albany developers: please comment if I missed or mis-represented something.  I do not believe there are any crazy Trilinos options on in any of the builds beyond what is mentioned, but it could be I am unaware of some of them. 

I am very interested how the Albany list compares with the settings with which Trilinos is tested nightly.  I know you do not test with Clang, and used to not test with FPE exception checking.  It sounds like you don't test on waterman, mayer or blake.  Do you test with an OpenMP KokkosNode on any platforms? 

For Albany developers such as @mperego , @lxmota , @bartgol, @gahansen  , who have expressed interest in this topic: we can use this list to determine which builds, if any, we want to cut based on the summaries above.

**Comment by ikalash** [comment]
Tagging @kddevin and @bartlettroscoe who may also be interested in this discussion.

**Comment by lxmota** [comment]
@ikalash Thanks for compiling this comprehensive list. The only other test that I will be interested in is Albany/LCM on CEE. I used to have that, but recently there were changes to the CEE modules that broke it, and so I disabled it. I need to revive it, specially since we'll need Albany/LCM on CEE for the Arctic Coastal Erosion project. I just need to find the time to do it sooner rather than later.

**Comment by ikalash** [comment]
@lxmota , oh yes, thank you for reminding me.  My question is: how was that build different than the existing CEE builds (summarized in this issue)?  The current CEE builds have LCM on, as well as SCOREC for some of them.  I guess they do not have DTK, but I could add that if we wanted to.  I would probably vote against creating more CEE builds since there are so many already (perhaps too many).

**Comment by lxmota** [comment]
That build is different in that it tests the modules system that Dan and I wrote. Unfortunately, I can't ask some casual user of the ACE project to start fiddling with CMake files. They won't do it, as I found out from other LCM users. So I need to test on CEE whether that modules system works.

**Comment by ikalash** [comment]
@lxmota : I see.  What compilers were used there - gcc?  I wonder if we can switch over one of the existing CEE builds to use those modules to not have a proliferation of tests on the same architecture that are very similar.

**Comment by lxmota** [comment]
They used gcc and intel. I agree that having less tests is better. That is why I killed the Ubuntu build.

**Comment by ikalash** [comment]
@lxmota: In this case, maybe we could switch the AlbanyIntel build on cee-compute018 to use your modules?  It seems to be the most similar one.  We can talk about it when we meet later in the week.

**Comment by lxmota** [comment]
@ikalash Sounds like a plan.

**Comment by mhoemmen** [comment]
> NOTE: the builds with DTK enabled need to have `-D Tpetra_INST_INT_UNSIGNED_LONG:BOOL=ON` to enable a build with ETI ON.

This needs to be on for DTK regardless.  It's not correct to use a GlobalOrdinal type if it's not enabled, regardless of whether ETI is enabled.  For example, solver factories use the list of enabled Tpetra type combinations to register solvers.  If a type combination wasn't registered, then the solver factory won't be able to create the corresponding solvers.

**Comment by ikalash** [comment]
To follow up on the discussion today at the SART meeting, I think the most sensitive builds for Albany (builds where issues show up that don't show up in other builds are): 

- clang builds
- builds with FPE checking
- debug builds
- it would be good to have a build with DTK and SCOREC - sometimes those get broken (usually by stk)
