### ISSUE TITLE
New failing LandIce tests

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#443]
Looks like some new tests were added yesterday, and fail:

```
FO_MMS_FO_GLF_QUAD 
FO_MMS_FO_GLF_TRI 
FO_MMS_FO_GLF_TRI_CORNER_CASE 
FO_MMS_FO_GLF_TRI_NONCONST_VELOCITY 
```
The error is as follows:
```
p=0: *** Caught standard std::exception of type 'std::logic_error' :

 /home/ikalash/nightlyCDash/repos/Albany/src/disc/stk/Albany_GenericSTKMeshStruct.cpp:1655:
 
 Throw number = 1
 
 Throw test that evaluated to true: true
 
 Error! Cannot read the field from a mathematical expression, since PanzerExprEval package was not found in Trilinos.
 ```
http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=82197

@mperego , I believe you checked in some stuff to LandIce yesterday.  Can you please have a look?

**Comment by mperego** [comment]
@ikalash Oh, right. We have to enable PanzerExprEval in Trilinos build. I'll also #ifdef guard those tests.

**Comment by ikalash** [comment]
What is the precise configure line that needs to be added to the Trilinos build script?  I can add it for the nightlies.

**Comment by mperego** [comment]
-D Trilinos_ENABLE_PanzerExprEval:BOOL=ON \
we need Pamgen as well, but I guess it's already enabled
-D Trilinos_ENABLE_Pamgen:BOOL=ON \

Thanks for doing that!!

**Comment by mperego** [comment]
OK, it should be fixed now. (commits 7a05ecad3e118f859 and 07a5559647009757f). Thanks @ikalash .
