### ISSUE TITLE
Albany compilation error due to Albany_GmshSTKMeshStruct with intel compiler

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#444]
@JustinClough : I think some of your changes yesterday to the GmshSTKMeshStruct broke our intel builds.  Here is the error: 

```
[ 15%] Building CXX object src/adapt/CMakeFiles/albanyAdapt.dir/AAdapt_AdaptiveModelFactory.cpp.o
/.../Albany/src/disc/stk/Albany_GmshSTKMeshStruct.cpp(1223): error: function "std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const std::basic_ifstream> &) [with _CharT=char, _Traits=std::char_traits]" (declared implicitly) cannot be referenced -- it is a deleted function
```

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=82209 (you won't be able to access this URL, Justin, since you're off the Sandia network). 

Can you please have a look at / fix the problem?

**Comment by bartgol** [comment]
I believe this may be the problem:

```
+std::ifstream Albany::GmshSTKMeshStruct::open_fname()
+{
+  std::ifstream ifile;
+  ifile.open(fname.c_str());
+  if (!ifile.is_open()) 
+  {
+      TEUCHOS_TEST_FOR_EXCEPTION(true, std::runtime_error, "Error! Cannot open mesh file '" << fname << "'.\n");
+  }
+  
+  return ifile;
+}
```
There is a copy performed here. A solution could be to accept the ifstream as an argument by reference in the `open_fname` routine.

**Comment by JustinClough** [comment]
Working on this now. I didn't get any errors yesterday when I compiled so I figured everything was okay.

I cleaned out my build dir and am recompiling. If everything looks good, then I'll push the fix.

**Comment by bartgol** [comment]
They may have deleted the copy constructor only in a recent standard. You may have compiled with "old" std flags. That's the only explanation I see...

**Comment by JustinClough** [comment]
Just pushed a hopeful fix. I'll hold off on closing the issue to see what the nightlies say. Thanks for the help @bartgol!

**Comment by ikalash** [comment]
Looks like this issue has been resolved.  Thanks, Justin!
