### ISSUE TITLE
Failing hydrology tests 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#446]
Looks like there are some new hydrology tests and they are failing across all the platforms:

Hydrology_steady 
Hydrology_unsteady 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4374010&build=82242

The issue is an invalid parameter name:
```
 Error, the parameter {name="DBC on NS BoundaryNodeSet1 for DOF water_pressure",type="double",value="0"}
 in the parameter (sub)list "Albany Parameters->Problem->Dirichlet BCs"
 was not found in the list of valid parameters!
 ```
@bartgol , @mperego : can you please look into / fix this?

**Comment by bartgol** [comment]
Uh, odd, they pass on my machine. I am working remotely today (and all of next week), so I won't be able to access cdash (still have to set up the vpn). Can you tell me what arch/compiler this build is?

**Comment by ikalash** [comment]
It happens on all the platforms where we run tests and LandIce is on.  If you want an SON one, take blake for example:

https://my.cdash.org/testDetails.php?test=45765422&build=1618515

Looking at the error in more detail, it seems the problem is that a nodeset with the name BoundaryNodeSet1 doesn't exist in the input exo file.  Is it possible you have an exo file that has that nodeset locally on your machine, hence you are not encountering the error?  If that's the case, the solution would be to check in the right exo input file.

**Comment by bartgol** [comment]
Ah, no, wait. That test should be using Gmsh meshes. @JustinClough did you change the naming convention for the gmsh mesh struct nodesets/sidesets?

**Comment by JustinClough** [comment]
The naming convention is the same. I think the issue is that any process that isn't 0 doesn't know the full list of node and side sets. This is the commit that's causing the issue: 6f44fa4c359383093bcd1b9116e911e4a5b00af5

I'm not sure what exactly is wrong since its the same code but moved into a function. Any advice here?

**Comment by bartgol** [comment]
Could it be that the test on the version being 2.2 fails for some reason? Probably it's not the culprit, but worth to check.

Btw, I think an enum there would be safer/cleaner. Something like

`enum class GmshVersion {
   V2_2,
   V4_1
};
GmshVersion version;
`

**Comment by JustinClough** [comment]
The issue was that only process 0 knew the mesh version. Commit ca26c2ceed9cd578fc87942a4dcbd1430ea810b0 should work; it solves the issue on my machine.

I also switched to using an enum version in the commits after that one. Thanks for the help!

**Comment by ikalash** [comment]
Thanks!  I'll close this issue tomorrow morning provided the nightlies confirm that everything is back to normal.

**Comment by ikalash** [comment]
Nightlies confirm that this issue has been resolved.  Thanks!
