### ISSUE TITLE
FO_MMS_FO_GLF_TRI_CORNER_CASE failing in CUDA builds (Ride, Waterman) and on Blake

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#447]
The recently added FO_MMS_FO_GLF_TRI_CORNER_CASE test is failing in the CUDA builds (Ride, Waterman) due to a failed comparison:

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4373104&build=82230

```
Response vector 0: {Grounding Line Flux}

                    -6.826348899312e+08
Response Test 0: -6.826348899312e+08 != -7.016100000000e+08 (rel 1.000000000000e-04 abs 1.000000000000e-08)

CheckTestResults: Number of Comparisons Attempted = 1

Main_Solve: MeanValue of final solution 5.000000000000e-01

Number of Failed Comparisons: 1
```
@mperego I think you are the author of this test - can you please have a look?

**Comment by ikalash** [comment]
Looks like it's failing on Blake as well, with both Serial and OpenMP node; so it must not be just a CUDA thing: 

https://my.cdash.org/testDetails.php?test=45765375&build=1618515

**Comment by mperego** [comment]
@ikalash Thanks. I just requested access to Blake on WebCARS. As soon as I have access I'll start debugging there.

**Comment by ikalash** [comment]
Ok sounds good.  If you have access to waterman/ride, you could start looking there - but I could see that maybe you prefer not to start there since these are GPU systems and have their own challenges/nuances.

**Comment by mperego** [comment]
Yeah, exactly. I'm hoping to get this fixed on a Serial system. I can turn off the test if you prefer in the meantime.

**Comment by ikalash** [comment]
I understand, it is what I would do too.  If you think the tests will be failing for awhile it's best to turn them off, but if you think you can fix it soon (e.g., first part of next week) I'm OK with keeping them failing for now.

**Comment by ikalash** [comment]
Seems this problem has been resolved on blake/waterman but the tests is failing in a different way in some of the debug builds e.g. 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4389568&build=82370

Here is the error: 

```
p=0: *** Caught standard std::exception of type 'std::runtime_error' :

 DynRankView bounds error of view H ( 2 < 2 )
 Traceback functionality not available
 
```

**Comment by mperego** [comment]
Just fixed that! I'm confident that my last commit will fix the issue (finger crossed). Closing.
