### ISSUE TITLE
Create branch / tag to archive EigenData usage in ATO prior to merging in unpetrify_branch 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#451]
Request by @jrobbin .  Creating issue so we do not forget!

**Comment by ikalash** [comment]
@bartgol : I think you did this, no?  If so we should close this issue.

**Comment by bartgol** [comment]
Actually, the eigen data stuff is still there. I'm not sure how tested/supported it is though. I fear that there are no tests using them. We could check by putting a throw statement inside a key function, and see if any test fails.

**Comment by ikalash** [comment]
QCAD was using it.  I thought ATO was too, or that usage has been removed from ATO?  I don't think any other physics in Albany would be using it right now.

**Comment by bartgol** [comment]
I think so too. We need to purge this feature, before it creates more headaches in future developments.
