### ISSUE TITLE
Change default input file to input.yaml

### ISSUE THREAD

**Issue by bartgol** [SNLComputation/Albany#453]
Most of Albany has moved to yaml from xml. The default name for input files should move to yaml as well.

**Comment by ikalash** [comment]
I think you mean that if you run AlbanyT w/o an argument, it should search for input.yaml, not input.xml; correct?  I've encountered that before, and thought that what you propose in the issue would be a good idea, but I did not do it.  I can make the change.

**Comment by ikalash** [comment]
We should also probably have the code look for inputT.yaml if running with AlbanyT.  I think now it looks for input.xml regarding the executable (caveat: I say that w/o the code in front of me).

**Comment by bartgol** [comment]
Yeah, that's what I meant. Since we are using xml less and less frequently, it makes sense to search for yaml as a default. The tpetra main, can search for inputT.yaml, if we think it's more reasonable. Though soon enough, we should be able to have a single executable, and select the backend linear algebra from input file, so that's less important, I think.

**Comment by ikalash** [comment]
@bartgol I agree.
