### ISSUE TITLE
Status of moertel utils in Albany?

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#458]
I am in the process of refactoring LCM to use Thyra in place of Tpetra, and I have come across the Albany/src/LCM/utils/mortar directory, which I believe is an interface to moertel to do contact.  @gahansen I think you are the owner/creator of this code.  A question comes up about what we want to do with it as we switch things over from Epetra/Tpetra to Thyra.  What is the status of the moertel stuff?  We need to decide how to proceed with it in the refactor.  I worry about functionality if it hasn't been tested for awhile.

**Comment by gahansen** [comment]
I think we could tag and eliminate this directory. There is also an ALBANY_CONTACT build option, and a couple of ifdefs in LCM/problems/MechanicsProblem_Def.hpp that could go into the tag and be removed. We had hopes of doing contact with moertel at one point but a path to accomplish that at this point is not pretty unclear.

**Comment by ikalash** [comment]
Thanks @gahansen , we will move it to a tag.  Does the same go for Catalyst (see issue #158)?
