### ISSUE TITLE
Compilation errors due to libma.a

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#459]
It seems in the past few days, compilations errors due to routines in the libma.a libray have crept in: 
```
[ 97%] Built target BifurcationTest
Scanning dependencies of target MeshComponents

[ 97%] Building CXX object src/LCM/CMakeFiles/MeshComponents.dir/test/utils/MeshComponents.cpp.o
/.../test/TrilinosInstall/lib/libma.a(maShape.cc.o): In function `ma::fixLargeAngleTets(ma::Adapt*)':

maShape.cc:(.text+0x1476): undefined reference to `ma::SingleSplitCollapse::SingleSplitCollapse(ma::Adapt*)'
```
Does anyone know what is this library so we can assign this issue to the right person?

**Comment by ikalash** [comment]
Looking more at the errors I think the issue is stemming from SCOREC:
```
[100%] Building CXX object src/LCM/CMakeFiles/Subdivision.dir/test/utils/Subdivision.cpp.o
/.../test/TrilinosDbg/lib/libma.a(maShape.cc.o): In function `ma::SingleSplitCollapse::IgnoringCollapse::~IgnoringCollapse()':

repos/Trilinos/SCOREC/ma/maSingleSplitCollapse.h:20: undefined reference to `vtable for ma::SingleSplitCollapse::IgnoringCollapse'

/.../test/TrilinosDbg/lib/libma.a(maShape.cc.o): In function `ma::EdgeVertFixer::EdgeVertFixer(ma::Adapt*)':
```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=82935
@ibaned , @cwsmith , can you please have a look?

**Comment by bartgol** [comment]
I found the culprit. I'm going to issue a PR in the SCOREC repo.

**Comment by ikalash** [comment]
Looks like the problem persists: 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=82972

@ibaned , should we open a SCOREC issue?

**Comment by cwsmith** [comment]
@ikalash What is the git hash of core the last failed build used?

**Comment by ikalash** [comment]
@cwsmith : 448b5f0548c8f9d63b6c499b65ef55c5e4bc034c

**Comment by cwsmith** [comment]
Thank you.  That hash is from two days ago (26th) and does not include Luca's fix:
https://github.com/SCOREC/core/commits/master

**Comment by ikalash** [comment]
Hmmm, that's odd.  My nightly scripts are supposed to check out SCOREC VOTD.  Let me try executing them again.

**Comment by ikalash** [comment]
I tests again and it seems fine.  Not sure what happened - maybe my nightlies cloned before the issue was fixed.  Anyway, thanks @cwsmith and @bartgol .
