### ISSUE TITLE
Failing Tempus tests on waterman

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#460]
The following tests are failing on waterman w/ floating point exceptions:
```
Serial_Dynamic_Cubes_NewmarkImplicitAForm_Tempus | Failed | 290ms | Completed (Failed)
Parallel_Dynamic_Cubes_NewmarkImplicitAForm_Tempus | Failed | 340ms | Completed (Failed)
Parallel_Dynamic_Cubes_NewmarkExplicitAForm_LumpedMass_Tempus | Failed | 410ms | Completed (Failed)
Dynamic_Torsion_NewmarkImplicitAForm_Tempus | Failed | 440ms | Completed (Failed)
Dynamic_Torsion_NewmarkExplicitAForm_Tempus | Failed | 430ms | Completed (Failed)
```
@ikalash Any idea what the issue is? The tests seemed to pass on ride.

**Comment by ikalash** [comment]
This is the same as issue #461  - sorry I didn't see your issue when I opened it.  I'm working on a PR to fix the issue on the Tempus side.  I'll close this issue and keep #461 open until the PR is merged in.
