### ISSUE TITLE
How to combine decomposed smb files into a single one? 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#464]
Question for the PUMI/SCOREC folks: is there a utility to combine a set of decomposed *.smb files into a single one (something like epu for Exodus)?  

This would be quite helpful for some debugging I'm doing of the SCOREC tests in the unpetrify_branch of Albany.

Tagging those who might know: @ibaned , @cwsmith , @bgranzow , @maxrpi .

**Comment by maxrpi** [comment]
When you build SCOREC core, you build a slew of utilities. Among them are generate, split, uniform, repartition, and, important to you in this case, "collapse". Collapse will allow you to decrease the number of partitions by an integer factor.

mpirun -n 32 /foo/bin/collapse model 32part_inmesh 8part_outmesh 4

will collapse a 32 part mesh into a 32/4 = 8 part mesh.

IIRC there's a passably informative usage string for all of those utilities.

________________________________

**Comment by ikalash** [comment]
Thanks for the reply @maxrpi.  Where would the collapse routine be found?  I looked in my Trilinos/build/install/bin directory and also Trilinos/build/SCOREC, and am not finding it.  My Trilinos had SCOREC enabled: `-D Trilinos_ENABLE_SCOREC:BOOL=ON `.  Do I need to enable something else perhaps to get the utilities?

**Comment by maxrpi** [comment]
You can either compile piecemeal from the sources found in tests/src or if you do a cmake driven build of core, make then make install to put them in the install_dir/bin directory.On Apr 4, 2019 11:10 AM, "Irina K. Tezaur" <notifications@github.com> wrote:Thanks for the reply @maxrpi.  Where would the collapse routine be found?  I looked in my Trilinos/build/install/bin directory and also Trilinos/build/SCOREC, and am not finding it.  My Trilinos had SCOREC enabled: -D Trilinos_ENABLE_SCOREC:BOOL=ON .  Do I need to enable something else perhaps to get the utilities?

**Comment by ikalash** [comment]
So I take it I need to build SCOREC separately with the utils enabled - I can't use the build I have that is a part of Trilinos.  When I try to do this, I get the following error:

```
[ 17%] Building CXX object apf/CMakeFiles/apf.dir/apfFieldData.cc.o
In file included from /usr/include/openmpi-x86_64/openmpi/ompi/mpi/cxx/mpicxx.h:283,
                 from /usr/include/openmpi-x86_64/mpi.h:2704,
                 from /home/ikalash/unpetrify/SCOREC/core/pcu/PCU.h:16,
                 from /home/ikalash/unpetrify/SCOREC/core/apf/apfMesh.cc:8:
/usr/include/openmpi-x86_64/openmpi/ompi/mpi/cxx/op_inln.h: In member function ‘virtual void MPI::Op::Init(void (*)(const void*, void*, int, const MPI::Datatype&), bool)’:
/usr/include/openmpi-x86_64/openmpi/ompi/mpi/cxx/op_inln.h:121:46: error: cast between incompatible function types from ‘void (*)(void*, void*, int*, ompi_datatype_t**, void (*)(void*, void*, int*, ompi_datatype_t**))’ to ‘void (*)(void*, void*, int*, ompi_datatype_t**)’ [-Werror=cast-function-type]
     (void)MPI_Op_create((MPI_User_function*) ompi_mpi_cxx_op_intercept,
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openmpi-x86_64/openmpi/ompi/mpi/cxx/op_inln.h:123:59: error: cast between incompatible function types from ‘void (*)(const void*, void*, int, const MPI::Datatype&)’ to ‘void (*)(void*, void*, int*, ompi_datatype_t**)’ [-Werror=cast-function-type]
     ompi_op_set_cxx_callback(mpi_op, (MPI_User_function*) func);
                                                           ^~~~
```
Have you seen this issue, @maxrpi ?  Base on googling, it could be that my compiler is too new (gcc-8.3.1).

**Comment by ikalash** [comment]
@maxrpi : I got it to work on my other workstation, which has gcc-6.1, so the error _is_ a compiler issue.  Not sure if the SCOREC folks are aware of it or not.  Anyway, I was able to do what I wanted to do, so I will close this issue.
