### ISSUE TITLE
Switch mayer nightlies to use ARM compiler and run on mayer instead of mayer2

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#468]
@jewatkins has figured out the environment/modules/configure script updates to get this to work.  I have been wanting to switch the Mayer tests to use the ARM compiler for awhile on that platform.

**Comment by ikalash** [comment]
@jewatkins : I just tried to build on mayer with your new modules (with one change: I had to also load openblas: module load openblas/0.3.4).

I get the following compilation error:
```
[ 41%] Building CXX object packages/seacas/libraries/ioss/src/CMakeFiles/Ioss.dir/Ioss_Node.C.o
[ 41%] Linking CXX executable nem_slice
Scanning dependencies of target mapvar
[ 41%] Building Fortran object packages/seacas/applications/mapvar/CMakeFiles/mapvar.dir/getbnd.f.o
[ 41%] Building Fortran object packages/seacas/applications/mapvar/CMakeFiles/mapvar.dir/mapvar.f.o
F90-S-0029-Illegal hexadecimal constant: Seehttps://github.com/gsjaardema/seacas/packages (/mscratch/albany/mayer/nightlyCDashTrilinos/repos/Trilinos/packages/seacas/applications/mapvar/mapvar.f: 417)
F90-S-0034-Syntax error at or near non-decimal constant 0 (/mscratch/albany/mayer/nightlyCDashTrilinos/repos/Trilinos/packages/seacas/applications/mapvar/mapvar.f: 417)
F90-S-0029-Illegal hexadecimal constant: Seehttps://github.com/gsjaardema/seacas/packages (/mscratch/albany/mayer/nightlyCDashTrilinos/repos/Trilinos/packages/seacas/applications/mapvar/mapvar.f: 428)
F90-S-0034-Syntax error at or near non-decimal constant 0 (/mscratch/albany/mayer/nightlyCDashTrilinos/repos/Trilinos/packages/seacas/applications/mapvar/mapvar.f: 428)
  0 inform,   0 warnings,   4 severes, 0 fatal for mapvar
[ 41%] Building Fortran object packages/seacas/applications/mapvar/CMakeFiles/mapvar.dir/mklstv.f.o
[ 41%] Built target nem_slice
[ 41%] Building Fortran object packages/seacas/applications/mapvar/CMakeFiles/mapvar.dir/mkrnk.f.o
[ 41%] Building Fortran object packages/seacas/applications/mapvar/CMakeFiles/mapvar.dir/rank.f.o
[ 41%] Building Fortran object packages/seacas/applications/mapvar/CMakeFiles/mapvar.dir/srchge.f.o
[ 41%] Building Fortran object packages/seacas/applications/mapvar/CMakeFiles/mapvar.dir/srchgt.f.o
Scanning dependencies of target mapvar-kd
[ 41%] Building Fortran object packages/seacas/applications/mapvar-kd/CMakeFiles/mapvar-kd.dir/mapvar-kd.f.o
F90-S-0029-Illegal hexadecimal constant: Seehttps://github.com/gsjaardema/seacas/packages (/mscratch/albany/mayer/nightlyCDashTrilinos/repos/Trilinos/packages/seacas/applications/mapvar-kd/mapvar-kd.f: 285)
F90-S-0034-Syntax error at or near non-decimal constant 0 (/mscratch/albany/mayer/nightlyCDashTrilinos/repos/Trilinos/packages/seacas/applications/mapvar-kd/mapvar-kd.f: 285)
```
Do you?  I wonder if this is something that crept in recently; or perhaps you didn't build the seacas tools, so you didn't see it?

**Comment by jewatkins** [comment]
The configuration file I used is `doc/dashboards/mayer.sandia.gov/do-cmake-trilinos-arm-serial` and it looks like I used seacas. I didn't change the configuration file too much, you could see the changes here: https://github.com/SNLComputation/Albany/commit/0d8b3764bfc6e6310fc7f4b29302bf72d04e5da7
You shouldn't have to load openblas unless you're using gcc, that's what the ARM performance library is for (similar to intel mkl).

**Comment by jewatkins** [comment]
Let me try building again with a new trilinos and see if I get your error.

**Comment by ikalash** [comment]
I just went straight with ctest_nightly.cmake.frag to try to build, since it looked like you had updated that file (though it needed some fixes to the paths).  I was setting blas there, so I figured we still needed it.  Let me try with your input file.  If it works, it's just a matter of translating your input file into ctest_nightly.cmake.frag .

**Comment by jewatkins** [comment]
Okay sounds good. Yeah I might have missed some things in `ctest_nightly.cmake.frag`.

**Comment by ikalash** [comment]
I get the same error with your configure script @jewatkins .  This must be a new issue then.  When did you last test the build?  Sorry that it took me so long to start on converting this to a nightly... in any case we would have had to deal with this error sadly...

**Comment by jewatkins** [comment]
Yeah I see it too. It looks like the last time I built it was 4/9/19.

**Comment by ikalash** [comment]
I just opened a Trilinos issue on this and tagged you in it too: https://github.com/trilinos/Trilinos/issues/4973 .

**Comment by jewatkins** [comment]
The trilinos repo version that I used was: trilinos/Trilinos@5247911bd3 and seacas was updated shortly after: trilinos/Trilinos#4820

**Comment by ikalash** [comment]
I just resolved this issue.  I'd still like to switch the mayer nightlies to run on a compute node rather than a login node, but it appears the necessary modules aren't available on the compute nodes.
