### ISSUE TITLE
Failing Hydrology_unsteady test 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#469]
The Hydrology_unsteady test started failing today:

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4475202&build=83560

There is a failed comparison:

```
Response vector 0:
                    3.241297833084e+02
Response Test 0: 3.241297833084e+02 != 3.254630000000e+02 (rel 1.000000000000e-04 abs 1.000000000000e-04)
```
I suspect it's due to changes to the Tempus package in Trilinos, since there haven't been any commits on the Albany side.  It seems there is a minor difference relative to before.  @bartgol , @mperego could you have a look?

**Comment by bartgol** [comment]
Do you know what changed in Tempus that could have affected the result? I believe this test used adaptive time stepping. Perhaps the adaptivity criteria changed, resulting in different time steps taken by the solver?

**Comment by ikalash** [comment]
I haven't been following it recently but there was a fair amount of activity in the past few weeks.  Pinging @ccober6 and @sconde, who may have some ideas.  Just for the record, this isn't a result of the changes I made to Piro to make it possible to call Time Step control from Albany in a different way (https://github.com/trilinos/Trilinos/pull/4822 ) - this PR was merged way before the issues started, and shouldn't have any effect on Albany tests using Tempus's Time Step Control sublist.

**Comment by ccober6** [comment]
Yeah, there has been some activity recently.  Do you know when (which commit) the problem started?

The changes did not effect Tempus testing, but the coverage is thin.  If you suspect the TimeStepControl, there are probably one likely candidate  

> Tempus: improve interval output setup #4837

This changed the interval output algorithm.  Previously it put all the interval output times into the same vector specified output times, and then sorted it.  However the EMPIRE folks can have millions of timesteps with >10,000 interval output times.  The sorting of the vector of output times was very expensive, so I reworked it to calculate the interval output times on the fly to reduce the sort time.

This could slightly change the interval output times, and cause the timesteps to slightly change.  So this is a possible source of your diff.

**Comment by ccober6** [comment]
FYI, this commit 163c9c5ce7afe76b3ef35d300788126af8ef099f went in on 2019-04-08 21:53:40.

**Comment by bartgol** [comment]
If that's what changed, then I suspect the test is still ok. I will look at the solution plots, and if they look similar, I think we can simply bless the new output as new reference value. Thanks!

**Comment by ikalash** [comment]
Thanks @ccober6 !  I figured it was likely a change that affected in a minor way the time-step control behavior, and that we can just rebaseline, but wanted to double check first.
