### ISSUE TITLE
LCM FPEs on skybridge build with Intel

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#470]
The following tests started failing in the skybridge intel build yesterday: 

MechanicsPorePressureSimple_Serial
MechanicsPorePressureLocalized_Serial 
MechanicsPorePressureParallelFlow_Serial 

due to FPEs, e.g. http://cdash.sandia.gov/CDash-2-3-0/testSummary.php?project=10&name=MechanicsPorePressureSimple_Serial&date=2019-04-24 .   @lxmota , could this be related to your check ins yesterday?

**Comment by ikalash** [comment]
Seems this issue went away on its own.

**Comment by lxmota** [comment]
I changed some of the LCM module files here 128eaf25d881fba3f232babd913af1a7ba0140fb to disable FPE trapping and denormalized number trapping on clang and intel. That’s very likely what fixed it.
