### ISSUE TITLE
Networks and Albany_Coupled

### ISSUE THREAD

**Issue by bartgol** [SNLComputation/Albany#472]
The classes in Albany_Networks.hpp depend on the AbstractNetworkModel in Piro::Epetra. Now that we are switching to only thyra stack, Piro::Epetra stuff is off the table. Unfortunately, there's no equivalent of Piro::Epetra::AbstractNetworkModel for the Thyra stack.

The question then is: what should we do with that functionality (which ends up in Main_Coupled.cpp)? @ikalash and I are keen to remove it, since we are not sure if it's still used.

Please, drop a line here to let us know what's your take on the issue. PR #454 is in its last stage (adjusting tests folder), and we would like to merge it in next week.

Thanks

**Comment by mperego** [comment]
I'm fine dropping it if nobody is currently using it.

**Comment by ikalash** [comment]
@etphipp I think you were the one who created these files.  Are you ok removing them?

**Comment by etphipp** [comment]
If no one is still using it, that seems fine to me.
