### ISSUE TITLE
Field data and discretization functions

### ISSUE THREAD

**Issue by RuixiongHu** [SNLComputation/Albany#473]
Hello Sandia experts,

May I ask some questions on the state variable field and some functions under `/src/disc/`?

I've finished some level set sort of method and would like to implement it in Albany. What the method does is, based on the calculated state variable value on the mesh,  finding the locations of any given critical value, and use these location to update the material parameters and etc. This could be used in laser melting simulation to differentiate the boundary of solid and liquid, and could do a series of calculation to account for the behavior due to phase change.  

I proposed this idea in previous Albany phone call and was advised to extract the state variable field from Albany, assign those data onto the mesh (PUMI for my case), and after doing all the calculations on the mesh field, give back Albany whatever new material value it needs to know, and then proceed the calculation. And I was pointed to look at functions under /src/disc. I figured out for each type of discretization they have the same function but just adapted for their own structure, so advice on any type of mesh will be appreciated!

While I'm trying to figure out how to implement it in Albany I got little confused and would like to ask some questions:

1. How Albany save field (state variable/solution) during simulation? For my understanding it saves all those in a vectors, and those storage has nothing to do with the mesh anymore after information has been imported from the mesh at initialization. Is this correct?  

2. For what I would like to do (assign calculated field values into my mesh), I think I should be calling getField() under /src/disc/pumi to extract field into a Tpetra vector, and use corresponding mapping to assign them in to the mesh. Is this correct? Or should I do it reversely using setField() to set a Tpetra vector into the mesh already loaded? I would like to make sure which is the correct function to call for extracting a vector that stores my state variable field. 

3. For those get/set field functions under /src/disc, it's all under a class called APFDiscretization, can I know how to initialize those objects or get a correct pointer to it, so that I could call its member functions? I don’t see a direct initialization of such objects but do see examples going from getMeshStruct->getField container.

4. Can I ask what’s the difference between a `Tpetra` vector and a `ST*`? I see them sometimes used together.

I'm really spending time on figuring out things myself but still confused sometimes. So I’ll really appreciate any help or hint on those questions, or any examples in STK mesh that uses similar functions so that I could look into it. 

Thanks and have a nice day,
Ruixiong

**Comment by bartgol** [comment]
Hi Ruixiong,

Yes, the storage of Thyra object is separate from the storage of mesh objects. To save fields in the mesh, you indeed need to use the setField method in the discretization. What this method does is to copy the values of the Thyra into the array of the mesh.

Your confusion may come from the fact that the pumi discretizations have another setField method, which has nothing to do with Thyra vectors. Moreover, the setField method that takes a Thyra vector is not implemented in the pumi discretization. This is unfortunate, and probably not necessary (I think pumi should be able to store data from Thyra objects).

Unfortunately, I do not use pumi discretizations in my Albany work, so I can't take the time to implement those functionalities, but perhaps you could do it. I believe that one could override the setField method in the pumi discretization that accepts a Thyra vector, to do the following: 1) extract the local data from the thyra vector (with getLocalData); 2) call the setField method in the pumi disc that accepts a `ST*`, passing the local data extracted at point 1.

> Can I ask what’s the difference between a Tpetra vector and a ST*? I see them sometimes used together.

They are quite different. Tpetra vector is a class that handles a distributed vector; it takes care of allocating a local vector (which, at the end of the day, consists in a ST*, yes), but it also handles communication, and information related to the distribution of the vector. In general, you can get a `ST*` from a Tpetra vector, but you can't build a Tpetra vector from just a ST*; to build a Tpetra vector you would also need a Tpetra map, which is the object that knows how the vector entries are distributed across the mpi processes.

**Comment by RuixiongHu** [comment]
Hi Luca,

Thanks a lot for the explanation over the concept and steps. 
To implement it, can I ask some little questions on the data structures that Trillinos use and some Albany function details? I understand pretty much of PUMI but do not have too much experience in Trillinos so I would like to learn those powerful Trillinos tools.

1. I see in LCM there are some BC files they call 
```
Teuchos::RCP<const Thyra_Vector> x = dirichletWorkset.x;
Teuchos::ArrayRCP<const ST> x_constView    = Albany::getLocalData(x)
```
Is this the similar type of getLocalData I should implement? Can I know how to construct the Thyra_Vector from the correct state variable in current workset, since so far I don’t see how to check what field each workset stores and how those field are named in the workset object.
There’re lines in my code doing ` t = workset.current_time`  and   `Albany::MDArray phi1_old = (*workset.stateArrayPtr)[phi1_Name_];`  I would like to get some hint on how to adapt it to the Thyra_Vector above. 

2. Can I ask how to get to the correct class object to call the setFIeld() functions? Since there’s no explicit APFDiscretization object called in other problems, but the setField() function clearly needs to know which meshStruct to operate on, I mean I need an object to call setField() method.

I’ll really appreciate your hint, and it could also be helpful to see any similar examples in STK mesh.

Thanks!
Ruixiong

**Comment by bartgol** [comment]
Ok,

1) The getLocalData function takes a Thyra_Vector and returns an ArrayRCP to its data. Basically, a pointer to the stored data (calling getRawPtr on the ArrayRCP returns just that). You do not need to reimplement such function, simply use that one to get the ptr out of the Thyra vector.
2) there are 2 setField here: the one that takes a Thyra vector (which is in AbstractDiscretization) and the one that takes ST* (which is only in the pumi discretization). If you need the former, simply get the discretization from the workset. For the latter, you must cast the discretization down to the pumi one. With RCP's you need to do
`
   auto my_ptr = Teuchos::rcp_dynamic_cast<TheTypeCastingTo>(inputPtr);`

**Comment by RuixiongHu** [comment]
Good morning!

I was working around with some Albany functions over the weekend, can I ask some extra questions over them?

1. Can I know, inside evaluators, **what’s the function to extract the specific state variable field into a Thyra_Vector?** So that I could call `getLocalData()` later.

From my past work I only get calculated field by` setFieldData()` or use `MDArray`. I checked other problems, while they only get Thyra_Vector from already existed private variable (such as x, xdot etc with a predefined name), but there’s no similar work getting a calculated field (which can be named variously) inside evaluators. 

2. Where do all the discretization function happens? For example if I’m working with AMP then under AMP directory it only deals with problem specified issue (bcs and evaluators). All discretization level of work is done prior to it steps into the AMP folder. 

However, I’m trying to get Discretization object or the meshStruct object and use their member functions inside evaluators, **so is there anyway I could pass those Discretization or meshStruct object into my evaluators?** So that I could retrieve discretization information, get access to the mesh, or maybe do down cast to use appropriate functions. 

Thanks and hope you have a nice day,
Ruixiong

**Comment by bartgol** [comment]
Hi Ruixiong,

1. Inside evaluator you do not have access to general Thyra fields. This is because evaluators are meant to do local work (over the elements in the workset), so in general they do not need a Thyra vector (which holds the data over the whole mpi domain). Now, there are exceptions, like gather and scatter evaluators, which get/set data from/into the Thyra vectors. The vectors these special evaluators operate on are however 'special', so we store a ptr to them in the Workset: x, xdot, xdotdot, f (residual), and parameters.
That said, you 'can' get a hold to the Thyra vector of any field that is registered in the mesh (but do so wisely, don't overdo it). To do this, you need to get the discretization from the workset, then get the field from the discretization. Something like

```
auto vector_space = workset.disc->getVectorSpace(field_name);
Teuchos::RCP<Thyra_Vector> my_field = Thyra::createMember(vector_space);
workset.disc->getField(my_field,field_name);
```
The first two steps are not needed in case the vector was already created.

2.The discretization should be inside the workset. From there, you can access everything you need about the mesh. Notice though that the workset only stores a _abstract_  classes (e.g., `AbstractDiscretization`), which in turn store only abstract subobjects. So you can only use features of the abstract discretization/mesh objects. If those are not enough, you need to cast down to the concrete type, but you must know for sure what the concrete type is.

**Comment by RuixiongHu** [comment]
Thanks a lot for the explaination!

I've implemented them and most of the works, except for 

`workset.disc->getField(my_field,field_name);`

I figured out in AbstractDiscretization it does not have the `getField()`, but instead there is `getFieldT( Tpetra_Vector, string)`.  But when I call it, this takes a Tpetra_Vector, not a Thyra_Vector. And there's no other getField() to get Thyra_Vector under the entire disc category.

Are these two vectors somewhat interchangeable? Or should I be calling some other functions and then convert it to get to the correct ST* object?

Thanks

**Comment by bartgol** [comment]
Well, you can get the ST* pointer from a Tpetra vector too. However, the `getField` functionality _is_ in master. Have you checked that your master is up to date?

**Comment by RuixiongHu** [comment]
Morning,

Thanks for letting me know, and I just locally updated the `getField()` and will update the entire Albany maybe later today.

However, I figured out it still calls the `getFieldT()`, and when it redirect to the `APFDisctretization::getFieldT()`, this Tpetra function for pumi is left blank and not implemented. There
s only a `getField( char* name, ST* data, bool overlapped, int offset, bool neq_sized) ` in the pumi discretization. Is there any extra step I should be taking?

In addition, I'm still little bit confused about the storage of mesh and the calculated field. As explained the calculated field should be stored independently as a vector, and only assign back to mesh when writing visualization files. But since I'm doing `getField()` and then `setField()`, I feel like these two are just oppose to each other. I also checked the stk version of `getFieldT()`, it feels like I'm extracting field from the mesh and simply set it back, which means the field is already stored in whatever structure that specific mesh uses? But in that case doesn't it mean that I could directly access to the field value from the mesh? Instead of setting any new value to the mesh?

Thanks I'll really appreciate any help!
Ruixiong

**Comment by bartgol** [comment]
You're right, get/setFieldT are not implemented in PUMI. I think it should be relatively easy to implement though. My guess is that you should probably use the `getField( char* name, ST* data, bool overlapped, int offset, bool neq_sized)` method inside the implementation.

That said, if you want, you can access directly the mesh field, if you know the exact type of mesh you have. It is not very elegant, since you need to cast down the hierarchy to get the pumi mesh, but it should work.

**Comment by bartgol** [comment]
Hi Ruixiong,

Can we close this issue or do you need more help?

**Comment by RuixiongHu** [comment]
Hi Luca,

Do you mind if I keep this open for a little more days? I'm on a trip now so I can't do any implementation but I'll be back to work next week and might want to continue this issue if something's not working.

But I can also close this one and reopen another when needed, so please go ahead and close this if this is preferred.

I'll keep in mind closing issues when everything's good.

Thanks and hope you have a nice day,
Ruixiong

**Comment by bartgol** [comment]
That's fine. I just wanted to make sure this didn't stay open forever. Take your time, and yes, when you feel this can be closed, please, go ahead and do so.

**Comment by RuixiongHu** [comment]
Good morning,

Can I ask a question over mesh and its field stored during simulation?

I've successfully got to the mesh and its functions. However, inside evaluators, while I try to check all fields stored in the mesh, it only shows nodal fields (residuals, solutions, etc).

It does not show any integration point field (those initialized as state variable). But those state variable fields are indeed output to the visualization files together with those nodal fields finally. 

So I would like to know if I was missing something? Or there's extra steps to take in order to work with state variable storage than nodal field? I guess these steps should be conceptually the same for different meshes.

Thanks!
Ruixiong

**Comment by bartgol** [comment]
How do you get the fields from the mesh?

**Comment by RuixiongHu** [comment]
After getting access to the mesh by down casting it to pumi discretization, I used function within pumi that can check how many fields are there on the mesh object and what are they. It does show all nodal field, which can be validated from the output file.

I think I'm confused by the fact that when writing output file it does output all those IP fields, which means right before writing output, all fields are stored in the mesh. So I suppose there're steps that set those state variable fields onto the mesh? 

I see StateArrays is vector of length num worksets of a map from field name to shards array, can I know a little bit more about it? Like where can I find its implementation so that I could know how to access to the statearrays of my interest.

Thanks!

**Comment by bartgol** [comment]
The `StateArrays` struct is defined in `Albany_StateInfoStruct.hpp`. As you already figured out, it's a simple struct, containing a `StateArrayVec` structure, which is just an alias to an std::vector of `StateArray`, which is just an std::map from the state name to a shards::Array (with Fortran ordering, which shards calls NaturalOrder). You can inspect those vectors/maps manually, if you want, and you can see how to access shards arrays in `PHAL_SaveStateField_Def.hpp`, for instance. Morally, a shards::Array with NaturalOrder is very similar to a Kokkos::View with LayoutLeft (of course, without all the memory space/access meta level).

**Comment by RuixiongHu** [comment]
Thanks a lot for the help! This specific part is done but I might open another issue for another topic. Thanks!
