### ISSUE TITLE
Remove tests depending on deprecated trilinos packages

### ISSUE THREAD

**Issue by bartgol** [SNLComputation/Albany#477]
In today's Trilinos digest there was an announcement that a few packages in Trilinos are deprecated: OptiPack, GlobiPack, Trios, Claps. There's at least a couple of tests depending on OptiPack (I haven't checked the whole tests nor the other packages). We should purge them (unless someone has spare time to change them to a different analogous package).

**Comment by ikalash** [comment]
Are there actually tests that use these packages?  I would be surprised if there are but I could be wrong.

**Comment by bartgol** [comment]
I found at least one using OptiPack while working on #454.

**Comment by ikalash** [comment]
I just removed the last OptiPack test, so I think we can close this issue.
