### ISSUE TITLE
Numerous failing tests in Albany nightlies due to Piro PR on reportFinalPoint last night

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#479]
There are numerous failures in Albany today due to the Piro change you made @bartgol.  Here is the error : 

```
p=0: *** Caught standard std::exception of type 'Teuchos::Exceptions::InvalidParameter' :

 /home/ikalash/nightlyCDash/repos/Albany/src/Albany_ModelEvaluatorT.cpp:551:
 
 Throw number = 1
 
 Throw test that evaluated to true: true
 
 Calling reportFinalPoint in Albany_ModelEvaluatorT.cpp line 296
 ```
Can you please have a look at / fix this?

**Comment by mperego** [comment]
@ikalash. I think we are close to merge the unpetrify branch. Hopefully we can merge it today (I'm working on having it work in MALI now). So I think it does not make sense to spend time on this.

**Comment by ikalash** [comment]
Ah I see - you are saying the error will go away after we merge.  I somehow understood it like the change in Piro should work with both branches.

**Comment by mperego** [comment]
Yeah. Actually I think we only need to remove the TEUCHOS_FOR_EXCEPTION macro here:
https://github.com/SNLComputation/Albany/blob/master/src/Albany_ModelEvaluatorT.cpp#L547

And let the reportFinalPoint function do nothing.
We might fix it as well..

**Comment by bartgol** [comment]
Yeah, sorry guys, I forgot that there was that exception thrown in the Albany ME. The branch is ready for merge though, so we could just go ahead and merge, and avoid the mod in master (which may generate a conflict).

**Comment by mperego** [comment]
I've committed a fix to master. I think it is better in case one wants to go back to the version "before" the unpetryfication, without building an earlier version of Trilinos.

I sorted out some issues in the MPAS interface. I'm now running some tests in MALI, if everything works I'll push my changes and we can merge.

**Comment by bartgol** [comment]
Ok, I'll merge master in the branch, to avoid conflicts when the PR goes in.
