### ISSUE TITLE
Replace [set|get]LCMOnly feature with compile-time logic

### ISSUE THREAD

**Issue by bartgol** [SNLComputation/Albany#481]
@lxmota Your addition to the SolverFactory caused some trouble with ATO, which does not set a problem name in the namelist (it only builds 'subproblems'). For now I fixed it by having 'INVALID' as a default problem name (but any non-LCM problem name would do too).
However, I think this workaround could bite us later on (e.g., someone moves, say, ElasticProblem to the main Albany problem folder, along with all dependent evaluators, and tries to run an Epetra stack, for some reason). I would suggest an alternative way to get Tpetra as a build type without having to modify all your input files. Namely, I would suggest some CPP logic. Two possibilities:

1) Add an 'ALBANY_USE_TPETRA_AS_DEFAULT` configure option. If present, the SolverFactory sets 'Tpetra' as default build type in the valid parameters. You would still need to modify your build script, but it's one script, as opposed to N input files.
2) Check if ALBANY_EPETRA is defined. If it is, keep 'None' as default, otherwise we can safely set 'Tpetra' (since Epetra is not even supported to start with). Since you probably only build LCM for your daily runs and LCM only uses Tpetra, this could be the best solution, with 0 files that you need to modify.

What do you think? I can implement option 1 or 2, while I fix some issues cause by the merge of #454.

**Comment by lxmota** [comment]
Option 2 seems better, as you suggest.

Sorry about the trouble. Yes, I wouldn’t want to modify input files, specially for users. We have many input files lying around that would need the extra option otherwise.

**Comment by bartgol** [comment]
No worries. I figured you had quite a few input files, so finding a workaround seemed reasonable. As you said, option 2 should get us the best of both worlds.

**Comment by ikalash** [comment]
This got broken with your commit @bartgol for some of the LCM tests - they fail with an error message that the BuildType is undefined.  Can you please have a look?

**Comment by bartgol** [comment]
Are you building both Tpetra and Epetra? If so, then unless we update all the input files, the tests will fail. The workaround in 99e8c9d works only if you run LCM in a Tpetra-only build. If you run it in a Tpetra-Epetra build, then the input files need to be updated.

Looks like commit d28285c not only added the trick in SolverFacotry, but it also removed the 'Build Type' line from all the LCM input files. I guess we can decide whether we're ok testing LCM only in a Tpetra-only build, or we want to test it in a full build. If it's the former, nothing to change. If it's the latter, we have to add the 'Build Type' line to all the LCM tests again.

**Comment by ikalash** [comment]
Oh... yes I am.  I have a no-Epetra build as well, but I'd like to keep the Epetra + Tpetra build. 

I guess @lxmota you removed the specification "Build Type" from all the input files?  I had added it earlier.  Can we bring the input files I had before back?

**Comment by bartgol** [comment]
I guess the third option would be to find an alternative solution that still achieves a 'Tpetra' build type without explicitly modifying the input files. One solution could be to indeed always default the build type to Tpetra. However, I think that can lead to hard to debug issues. It took me ~30m to figure out why the ATO tests failed, and I've been involved in the unpetrifying process quite a bit, so it was 'easier' for me to find the culprit. My fear is that one year from now, someone will try to run an Epetra case, without setting it in the input file, and spend a couple of days trying to debug the exception that is thrown down in the solver stack...

**Comment by bartgol** [comment]
@ikalash We can revert that commit. It has a couple of conflicts, but should be doable. I'll go ahead and do it.

**Comment by ikalash** [comment]
Thanks Luca!  I'll test things after  you revert it.

**Comment by bartgol** [comment]
Done!

**Comment by ikalash** [comment]
So these are the only failures on my machine after pulling your changes:
```
The following tests FAILED:
	 15 - SteadyHeat2D_Dakota_list (Failed)
	 16 - SteadyHeat2D_Dakota_uniform (Failed)
	 51 - TransientHeat1D_Dakota_Tpetra (Failed)
	 52 - TransientHeat1D_OptiPack (Failed)
Errors while running CTest
```
Can we remove the OptiPack test?  Seems OptiPack is not supported anymore.  I don't know what's going on with the Dakota tests.  The error is not too helpful: 
```
3: Starting Albany_Dakota!
3:
3: Starting TriKota_Driver!
3: --------------------------------------------------------------------------
3: MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
3: with errorcode -5.
3:
3: NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
3: You may or may not see output from other processes, depending on
3: exactly when Open MPI kills them.
3: --------------------------------------------------------------------------
```
I tried running gdb but it didn't reveal any more info.  Thoughts?  The tests were passing prior to the merge.  Also, not all Dakota tests fail - for instance, SteadyHeat1D runs fine.

**Comment by bartgol** [comment]
Yes, we can remove the optipack, per #477 .

I know nothing about Dakota. I simply converted what was there, to the best of my knowledge. Did you break when `_exit` is called in gdb, to see at what point it craps out?

**Comment by lxmota** [comment]
@ikalash @bartgol I’m strongly against reverting back the removal of what I consider an unnecessary and confusing line to the LCM input files. We need to find a solution for this, specially in light that LCM will not have support for Epetra.

**Comment by ikalash** [comment]
@lxmota : lets talk about this.  Are you able to make it to the Albany meeting tomorrow?  I think the revert at this time was the right thing given that there were numerous failures w/o it.  W/o the revert, a lot of nightlies will be failing while we try to debug lingering errors.  This would make it difficult to debug real errors.

**Comment by mperego** [comment]
I'm on travel and I cannot call in tomorrow. Anyway, I think we could prevent to enable Epetra when LCM is ON during the configuration, and set the default build type to Tpetra when Epetra is not enabled.

**Comment by lxmota** [comment]
Yes, I’ll be at the Albany meeting tomorrow.

**Comment by ikalash** [comment]
@mperego : that's what Alejandro/Luca did originally.  The issue is the LCM tests will fail then if Epetra and Tpetra are on in a given build, which is the case with a lot of the nightlies.

**Comment by bartgol** [comment]
@mperego more precisely, ATO requires LCM, and its solver/problem creation logic clashed with the original idea behind Alejandro's workaround. I think we have a few options, given the adversity to the revert (which I already pushed as a temporary fix, but we can re-revert):

1) Always make Tpetra the default, no matter what. This would make life easy to most of the Albany users, since Tpetra is by far the default. The drawback is a slightly puzzling error you would get deep down in the linear solvers if you try to run an Epetra case without setting the build type in your input file. Not a huge drawback, if we are all aware of that. We could mitigate it by adding a warning at the beginning of the simulation in case no build type is specified, telling the user, if that error occours, how to fix it.

2) Make Tpetra the default for a subset of problem types. This is what Alejandro did originally. The only variation required would be to avoid a valid default name for the problem, so that we don't accidentally make a decision based on a wrong problem type if the problem type is not specified (like it happens for ATO).

3) Make Tpetra the default only if Epetra is not enabled. This would "work" for the daily life of most users, since they are likely to use Tpetra and are likely fine not building Epetra. However, to get our nightlies to pass, we would need to either add the build type in each file, or build a tpetra-only albany when testing LCM. Probably not the best option. But I figured I'd add it to the list, in case others think it's the best.

I think 1 and 2 are equally good. In either case I would add the warning at the beginning if the build type is not specified and we pick a default one (based on whatever criterion).

**Comment by lxmota** [comment]
@bartgol I'm OK with any of the options, 1, 2 or 3.

**Comment by ikalash** [comment]
Can we stuff "Build Type" into some object accessible within each of the problem files, and set it to "Tpetra" for LCM problems if it is not provided within the input file?  ATO is an LCM problem but for that case one would set "Build Type = Epetra" in the input file for the Epetra tests, so that option would be used.  I think that would be a robust solution.

**Comment by mperego** [comment]
I think 2 is best, along with what Irina just said. I would avoid 1. Option 3, which is what I was suggesting, could work without modifying input files if we never build LCM with Epetra enabled, and yes this would mean that we would have to change the nightlies. But yeah, option 2 is better.

**Comment by bartgol** [comment]
@ikalash that would be doable. The problem object is indeed constructed during the initial setup phase of the Application. My only concern would be semantic: is it really responsibility of the problem object to provide information (even if just as a default value) regarding the linear algebra and/or the solvers? I think it is more appropriate to place this kind of information in the SolverFactory (that's what Alejandro's workaround did). To me is a matter of separation of concerns (or even 'single responsibility', to quote OOP principles).

The more I think of it, the more I would go with option 1 in my previous comment. 2 sounds appealing too,  but I get worried about code maintenance related issues (e.g., consequences of a slight change in a problem name).

I guess we can discuss it at the conf call, and make a decision.

**Comment by ikalash** [comment]
I'm fine with 1 or 2.  I think 3 would cause the most confusion.  Most people just build the code and don't think about turning Epetra off.  Then they will run ctest and have all the LCM tests.  Confusing and not nice IMO...

**Comment by mperego** [comment]
That's why I was also suggesting to check at configuration time that Epetra and LCM are not enabled at the same time. Anyway, let's go with option 2 that's OK for everyone :-).
