### ISSUE TITLE
Get skybridge nightlies back up

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#485]
Skybridge recently changed their policy where jobs run using mpirun/mpiexec cannot be run on a login node.  The skybridge nightlies need to change to build on a login node, and run tests on a compute node.  I tried to make the change but encountered some issues with the scripts currently in place for the tests.  I will look at this again in a few weeks when I return from travel.  @lxmota I'll probably bug you some more about the scripts.  If you'd like the nightlies up sooner, you could look at modifying them yourself.

**Comment by ikalash** [comment]
So I am working on this and I am getting a lot of test failures that do not show up with any of the other builds, which I'm somewhat stumped by.  The errors are as follows:

```

returned_val != -1 failed at /ascldap/users/ikalash/LCM/Albany/src/utility/Albany_ThyraUtils.cpp +730
Error: addToLocalRowValues returned -1, meaning linear op is not fillActive 
or does not have an underlying non-null static graph!
```
(http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4660951&build=85974).

I don't get why this would show up only in this build and not the others.  I've verified that Albany and Trilinos are both up-to-date.  

The compilers used here are the ones set by the LCM modules, per @lxmota 's instructions.  In particular, I'm using  Intel 17.0.4.20170411 .  There are other intel builds (CEE, blake) where things are fine.  They do have a newer intel compiler (Intel 18), but I would be surprised if that was the cause of the issue. 

Thoughts?

**Comment by ikalash** [comment]
I should add that this issue occurred 3 weeks ago when I was first trying to re-set up this build.  So it's not something that crept in recently, but rather it likely started with the merging of the PR.  I was hoping it would go away in the past few weeks, but no luck.

**Comment by lxmota** [comment]
@ikalash I wouldn't be too surprised that it actually has something to do with the Intel compiler version. In the past I had instances of weird behavior related to "too  new" Intel compilers.

**Comment by ikalash** [comment]
@lxmota : but in this case it would be too old I think, since CEE and blake run fine with Intel 18. Anyway, I guess I can try intel 18 which appears to be available on skybridge to make it consistent with the other builds to see what happens.

**Comment by ikalash** [comment]
@lxmota : also, question about your scripts to run tests on skybridge.  The way I want to do things now, I want to first build Trilinos on the login node, then build Albany on the login node (w/o running tests), then submit a job to run the tests on a compute node.  I do this as follows: 
```
./clean-config-build-dash.sh trilinos 8
./clean-config-build-dash.sh albany 8
./test-dash.sh albany (this last line is within a batch script)
```
One thing that's not so nice is the second and third steps both produce a file called: albany-serial-intel-release.log.  So what it means is that when the tests are run, the build output gets clobbered.  Is there a way to specify a different name to which the output will be sent either for the second or last steps?

**Comment by lxmota** [comment]
@ikalash Compiler version: OK, hopefully using the same compiler version will fix that Thera issue.

Scripts: You only need to do clean-config-build.sh without the dash word, otherwise the script will send stuff to the cdash site.

Right now the log file name is hard coded. But after compiling Albany it could be renamed to something else to avoid the clobbering.
