### ISSUE TITLE
FPEs in Clang non-debug builds post merge

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#486]
Post merge, there are some FPEs showing up in the clang non-debug nightlies with FPE checking on (-DENABLE_STRONG_FPE_CHECK:BOOL=ON).  Here are the tests that fail.

On CEE (Albany64BitClang on cee-compute016): 

TransientHeat2D 	
ComprNS_2DTaylorGreenVortex_SDBC 	
FO_Test_ConfinedShelf_Epetra 	
FO_Test_ConfinedShelf_DepthIntBC_Epetra 	
FO_GIS_AdjointSensitivity_StiffeningBasalFriction_Epetra 	
Stokes_MMS_Poly_Epetra 	
(http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=85295 )

What is bizarre is that the tests pass in an all-debug build.  @bartgol can you please look into this issue?  The FPEs could be coming from Sacado, like before, but in this case I'm not sure how the refactor would have introduced them.  We should figure out how to proceed with fixing these to get back to an all-green dashboard.

**Comment by ikalash** [comment]
It looks like these tests are still failing.  @bartgol , did you have a chance to look into the issue while I was gone during the past 2 weeks?

**Comment by bartgol** [comment]
@ikalash no, I didn't.

**Comment by ikalash** [comment]
There was some discussion in a github issue (#450) not long ago started about lack of clang testing in Trilinos, specifically here was @bartgol 's comment:

"As I said on another issue (I forgot which one), I am ok keeping Clang builds, but given the lack of support from Trilinos, I don't want Clang builds issues to hold us back. "

I checked with Jim Willenbring and there has been some progress setting up Trilinos clang builds that are run when a Trilinos PR is pushed (https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=Clang&field2=buildstamp&compare2=63&value2=Experimental&field3=site&compare3=61&value3=ascic166 ).  It looks like there are still some kinks to work out with the testing based on this dashboard.  Jim mentioned that the guy working on this was on vacation for a few weeks.  I should have more info next Tuesday after the next SART meeting.
