### ISSUE TITLE
Failing FO_Thermo test on mayer

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#487]
The FO_Thermo test seg faults on mayer: 

https://my.cdash.org/testDetails.php?test=47577599&build=1657335

This could be related to FPEs (issue #486 ), as I made some changes yesterday to fix FPEs that were showing up for this test (FPE checking is not on in the mayer nightlies, so an FPE error would manifest itself differently).  What is somewhat bizarre is that the test runs correctly on all other platforms.  @bartgol , can you look at this too?

**Comment by bartgol** [comment]
This was indeed caused by commit 4ff5a4b. We cannot use `auto` for the return type of an expression, since with Sacado it does _not_ evaluates to a scalar type, but rather to a Sacado expression type, which yields errors when then using std functions on them.
