### ISSUE TITLE
Failing SCOREC tests due to empty state name

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#496]
It looks like in the past couple of weeks while I was away, 2 SCOREC tests got broken:

SCOREC_Elasticity_Necking_Tpetra 
SCOREC_Elasticity_NeckT_SM

Seems there is an empty state name which the code does not like: 

```
stateName != "" failed at /projects/albany/nightlyAlbanyCDash/repos/Albany/src/Albany_StateManager.cpp +192
State Name cannot be the empty string
[cee-compute013:80654] *** Process received signal ***
[cee-compute013:80654] Signal: Aborted (6)
[cee-compute013:80654] Signal code:  (-6)
```

(http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4651386&build=85861) .  Did something change that resulted in the empty state name, or logic was changed to disallow empty state names?

**Comment by bartgol** [comment]
This is actually a good addition by @lxmota . He was having some issues with a (local) test, and we tracked it down to a state having empty name. We decided adding a check in the state manger was a good thing. These tests are probably not using those state variables, which is why things were fine before. To fix them, you can either give a name to the states, or remove their registration.

**Comment by ikalash** [comment]
I just spent some time looking into the issue.  This is the line where a state with an empty name is registered: https://github.com/SNLComputation/Albany/blob/master/src/LCM/problems/MechanicsProblem_Def.hpp#L1174-L1182 .  If you put a print statement right before this line to print cmi.Name(), here is what you get: 
```
Calling MechanicsProblem::buildEvaluators
IKT before registerStateVariable cmi = Cauchy_Stress
IKT before registerStateVariable cmi = logFp
IKT before registerStateVariable cmi = Cauchy_Stress
IKT before registerStateVariable cmi = eqps
IKT before registerStateVariable cmi = logFp
IKT before registerStateVariable cmi = 
```
So after ``logFp", for some reason the ConstitutiveModelInterface has associated with it an empty name.  @lxmota , do you have any ideas for why this may happen?  It only happens for a couple of SCOREC tests, no others.  I'm not sure what is unique about those.

I tried a hacky fix to the problem to make up some alternate name to pass to the registerStateVariable routine, but then I get a seg fault.

If I comment out this assert: 

https://github.com/SNLComputation/Albany/blob/master/src/Albany_StateManager.cpp#L192 

to allow for an empty statename, the problem runs just fine.

Separate question for @ibaned and/or @maxrpi : is there any way I can run these cases in serial?  It looks like the mesh files are decomposed for 4 procs, so I can't run on any other number of procs.  So basically is there a utility like "epu" for the vtk files?  Being able to run on 1 proc would facilitate debugging, e.g. using gdb.

**Comment by ikalash** [comment]
Another symptom: the material model used for these cases is RIHMR.  Grepping through the code reveals that no other problem in Albany uses this material model.  I'm not familiar with this material model.  It seems something is messed up with it, as it tries to register a state w/o a name.

**Comment by ikalash** [comment]
One more thing: it seems the problematic state is isoHardening: https://github.com/SNLComputation/Albany/blob/master/src/LCM/models/RIHMRModel_Def.hpp#L39 .  It seems it's somehow not found in the field_name_map, but I don't know enough about the inner workings of this material to conjecture as to why.  @lxmota , do you have any insight into this? 

I did notice that there seems to be a discrepancy b/w isoHardening and isotropic_hardening in LCM::FieldNameMap: https://github.com/SNLComputation/Albany/blob/master/src/LCM/problems/FieldNameMap.cpp#L32-L33 .  I presume these are supposed to refer to the same field?  I tried to make them consistent but that does not fix the problem.

**Comment by lxmota** [comment]
@ikalash Thanks for all the digging. Yes, you are right about isoHardening. I know what it is. I'm fixing now.

**Comment by lxmota** [comment]
@ikalash Oh I see, you made them the same and that didn't fix the problem? They all should be isotropic_hardening instead of isoHardening.

**Comment by ikalash** [comment]
My bad... I just tried the fix again and this fixed the issue.  Not sure what happened the first time... maybe I mistyped it or something.  Anyway thanks for your help!

**Comment by lxmota** [comment]
@ikalash Great, thanks!

**Comment by ikalash** [comment]
Just fixed the issue.
