### ISSUE TITLE
Failing FO_GIS Adjoint Sensitivity tests

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#497]
There are 2 failing FO_GIS adjoint sensitivity tests:

FO_GIS_AdjointSensitivity_Thickness_Epetra
FO_GIS_AdjointSensitivity_TwoParameters_Epetra 

Here is the error:
```
                    3.859643761066e+01
dgdp != Teuchos::null failed at /projects/albany/nightlyAlbanyCDash/repos/Albany/src/Albany_SolverFactory.cpp +523
There are Sensitivity Tests but the sensitivity vector (0, 0) is null!
dgdp != Teuchos::null failed at /projects/albany/nightlyAlbanyCDash/repos/Albany/src/Albany_SolverFactory.cpp +523
There are Sensitivity Tests but the sensitivity vector (0, 0) is null!
dgdp != Teuchos::null failed at /projects/albany/nightlyAlbanyCDash/repos/Albany/src/Albany_SolverFactory.cpp +523
There are Sensitivity Tests but the sensitivity vector (0, 0) is null!
```  
It's curious that the other adjoint sensitivity tests are OK.  @mperego and/or @bartgol : could you please have a look at this?

**Comment by ikalash** [comment]
Here is a link to the output on the CDash site: http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4654280&build=85867 .  It only happens in the Clang builds, interestingly enough.

**Comment by bartgol** [comment]
Btw, the reason why this was the only build exposing the problem is that this test requires the option `ENABLE_MESH_DEPENDS_ON_PARAMETERS` to be on.
