### ISSUE TITLE
Soliciting feedback on FY20 plan for STK - please comment 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#498]
I received an email today from Alan Williams regarding the FY20 plan for STK.  He is asking in particular if there are certain items beyond what he has in the project plan currently that Albany wishes STK would have.  

@lxmota : one of them was I think improvements for reading/writing multi-dimensional fields for the Cauchy stresses, etc.  I can't quite remember the details of what we wanted...  I think it was to have a proper tensor layout defined at quad points - is that right?  

Here is the list of items that will be considered for FY20 according to Alan: 

- ngp::Mesh work to support Sierra Performance Portability Milestone (not well defined currently, may be request-driven as the milestone activities progress. Will include things like fixing the relationship between stk and ngp objects, and more coherent management of host/gpu syncing as we were discussing in the last NGP review. )
    ngp::Mesh work to support element-death on GPU. (mesh-modification on gpu, including part-membership changes and entity create/delete)
- Rebalancing work to improve performance of MGT
- Stk-simd for ARM and for IBM/Power. Simd-friendly field-data layouts, gather/interleave/scatter utils
- Stk capabilities, maintenance, usability (clean up field template params, boost removal, block-disconnect, etc)
- stk-balance work to fix some deficiencies that cause the partitioning to be inferior to what is produced by yada
- Lingering STK/Fmwk transition issues that make it hard to share code (like line weld generation code) between SD and SM
- Stk work to support the assemblies/hierarchies feature being considered for Exodus/Ioss
- A lightweight uniform-mesh-refinement tool
- Work in Zapotec to enable running some large meshes that Russ Teeter has

@jewatkins , you might have some items to add to the list for some of the performance portability refactors you were looking at within the STK stuff.

**Comment by lxmota** [comment]
@ikalash Yes, that's precisely what we discussed. A proper non-symmetric tensor layout for each quadrature point.

**Comment by jewatkins** [comment]
Unfortunately, I haven't looked at the STK package/Albany STK discretization in that much detail to be able to comment what would be needed.

**Comment by ikalash** [comment]
@jewatkins : that's fine, I wasn't sure how much you dove into it.  It looks like there are some plans for performance portability within STK; not sure if they will help Albany at all. Thanks.

**Comment by ikalash** [comment]
@lxmota : ok that's what I thought - I'll pass that along to Alan.

**Comment by bartgol** [comment]
Do they plan to make the fields store data directly on device? That would be neat.

**Comment by ikalash** [comment]
@bartgol : I've asked Alan and here is his response: 

"Our current approach for GPUs is as follows. We have an ‘ngp::Mesh’ which copies stk-mesh to the device and allows for traversing/accessing the mesh on device. We also have ngp::Field which corresponds to a stk::mesh::Field and copies data for a specific field to the device and allows for accessing it on device. It also has APIs for syncing the data between host and device, similar to the Kokkos::DualView API."

So it sounds like the answer is yes, but it involves copying the fields over to the device.

**Comment by bartgol** [comment]
Well, that's fine, there's really no way around it, since you're reading a file from host. Once the simulation has started, then as long as you keep updating the data on device (from device), then you only need to copy back to host for I/O.

To be clear, they are not using Kokkos for their portability layer, right?
