### ISSUE TITLE
invalid new-expression of abstract class type 'Albany::PUMIDiscretization'

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#500]
Any ideas where this error is coming from:
```
src/disc/Albany_DiscretizationFactory.cpp: In member function 'Teuchos::RCP Albany::DiscretizationFactory::createDiscretizationFromInternalMeshStruct(const std::map > >&, const Teuchos::RCP&)':
Albany/src/disc/Albany_DiscretizationFactory.cpp:475:93: error: invalid new-expression of abstract class type 'Albany::PUMIDiscretization'
```
It seems like the Aeras discretization is affected too. @lxmota is this related to your changes?

**Comment by jewatkins** [comment]
You can get around it by turning off SCOREC and Aeras.

**Comment by lxmota** [comment]
@jewatkins I was looking at this just a few moments ago. I don't see how my changes could have affected this, as I didn't touch either the discretization factory or any PUMI stuff. I changed how I manipulate some fields on the STK discretization, but that is guarded by ALBANY_LCM directives.

But then I don't compile with PUMI. It's conceivable that something I did caused this. I just don't see how.

**Comment by bartgol** [comment]
@lxmota it seems you added a method to the abstract discretization (`getBoundaryIndicator`). Probably you did not propagate it to all the concrete derived classes?

**Comment by lxmota** [comment]
Ah OK, that it's probably it. I'll fix it. Thanks.

**Comment by lxmota** [comment]
This commit 7e6100bd1e4e36b6b24698417c416c8be944fd41 should fix it. Sorry about that.

I'll wait for the nightly tests to verify that everything is OK.

**Comment by pbosler** [comment]
I'm getting similar errors for:
`Albany_MultiSTKFieldContainer` and `Albany_OrdinarySTKFieldContainer`.  Are these related?

**Comment by bartgol** [comment]
Good catch. Let me push a quick fix.

**Comment by lxmota** [comment]
@bartgol Thanks for adding the missing code guards.

**Comment by ikalash** [comment]
Thank you, guys, for opening this issue and resolving it.  I meant to open it but was stuck in meetings most of the day, so you beat me to it.  I pulled the changes and things seem OK on my machine.  Lets see what the nightlies show tomorrow morning, as suggested above.

**Comment by bartgol** [comment]
Still dangling. Pushing a fix now.

**Comment by lxmota** [comment]
@bartgol Thanks again for adding and fixing code guards that I missed.

**Comment by bartgol** [comment]
It seems that this issue is resolved. Closing.
