### ISSUE TITLE
New Albany failures (due to RCP error?).

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#503]
There are a handful of new failures in Albany including: 
```
ContinuationHeat1D_Tpetra
KfieldBC 
KfieldBC_L2Proj
SCOREC_Elasticity_NeckT_SM 
SCOREC_J2Adapt_Tpetra
```
All the errors look like: 
```
terminate called after throwing an instance of 'std::logic_error'
  what():  /projects/albany/nightlyAlbanyCDash/repos/Trilinos/packages/teuchos/core/src/Teuchos_RCPNode.cpp:548:

Throw number = 2

Throw test that evaluated to true: (!rcp_node_exists)
```
http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlydelta&buildid=86512
http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlydelta&buildid=86511

There appears to be an RCP error.  Since there were no changes to Albany in the past few days, some change in Trilinos must have exposed the issue.  The errors only occur in parallel, not serial.   The failures don't happen everywhere, only in the dbg, intel and clang builds (as usual with errors like these).

**Comment by ikalash** [comment]
I ran gdb (in parallel with the help of xterm) on a couple of these in the camobap debug build.  Attached are screenshots showing the backtrace for the ContinuationHeat1D_Tpetra and KfieldBC_L2Proj tests.  It seems both of the tests are having issues due to the map.  For the ContinuationHeat1D_Tpetra, it appears the code dies in the Tpetra Map destructor: https://github.com/trilinos/Trilinos/blob/master/packages/tpetra/core/src/Tpetra_Map_def.hpp#L1189 .  For KfieldBC_L2Proj, the code is dying in the getGlobalLength() call where the Map rcp is queried.  SCOREC_J2Adapt_Tpetra seems to be somewhat of a Heisenbug - sometimes the code dies when run, sometimes it does not.  In my gdb run on camobap, it did not. 

Pinging @mhoemmen: has any change gone into Tpetra that would cause us to get new errors such as the ones described?  I think the issue is on the Albany side and whatever changes were made to Trilinos recently exposed them.  Unfortunately the backtrace points to the generic Piro::PerformSolve call in Albany, which is not particularly helpful in figuring out the cause of the problem on the Albany side.

**Comment by bartgol** [comment]
@ikalash does this show up also with gcc or clang builds? If so, you could try adding the `-fsanitize=address` flag, to get info about potential memory errors. It's basically like valgrind, but without the N>>1 times slowdown...

**Comment by ikalash** [comment]
It shows up in both gcc and clang builds.  That's a good idea, Luca.  I can append ```-fsanitize=address``` to the CXXFLAGS in a couple of the builds and look at the output tomorrow.

**Comment by mhoemmen** [comment]
I don't think anything relevant in Tpetra has changed.  It looks like View's destructor is throwing, so it could be that something in Albany or a solver gave Map's constructor a View that claims to be owning when it's not, or a View with a memory space that doesn't match the memory it was given.  

@trilinos/tpetra

**Comment by ikalash** [comment]
Thanks @mhoemmen .  The thing is nothing in Albany changed, which makes me think something changed on the Trilinos side to perhaps cause an existing Albany issue to come to light.

**Comment by ikalash** [comment]
With the ```-fsanitize=address``` flag, there are a lot of failures, but I'm not sure any of them are real.  Please see: http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&subproject=Albany64BitClang .  I do need to check the specific ones for the problematic tests which I'll do after the Albany meeting.

**Comment by bartgol** [comment]
Yeah, most of them are MPI related, and they are well known. Usually we suppress those in valgrind, I'm not sure how to do that with ASAN. My hope was to see some asan errors in the problematic tests that helped reveal some issues (dangling pointers, r/w out of bounds, and the likes). As Mark said though, it may be a problem of some pair of View's (and/or RCP's) thinking they both own the memory. This is harder to track. I'm wondering if some Teuchos debug trace options for RCPs can help track which RCP is to blame...

**Comment by jfike** [comment]
You can suppress leaks by setting the environment variable 
setenv LSAN_OPTIONS suppressions=/path/to/lsan.supp

where lsan.supp has lines such as:
leak:libmpi
leak:libopen

and others that you want to suppress

**Comment by ikalash** [comment]
I have figured out which commit in Trilinos led to the start of these issues.  It is this one: https://github.com/trilinos/Trilinos/commit/28e210dad658fa157d8559084214745b288c380c 

```
commit 28e210dad658fa157d8559084214745b288c380c (HEAD)
Merge: a6efc7c198 d154fc16ff
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Wed Jul 3 10:36:55 2019 -0600

    Merge Pull Request #5400 from cgcgcg/Trilinos/miniem-pr
    
    Automatically Merged using Trilinos Pull Request AutoTester
    PR Title: Thyra+Tpetra: Inner products on Cuda
    PR Author: cgcgcg
```
If you look at the stack with the -fsanitize=address option for one of the tests (http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4725979&build=86695) you see there are issues precisely in some of the lines that were added in the PR commit above, e.g.: 
```
    #1 0x19b9f5a in Thyra::TpetraVectorSpace<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::createMembersView(RTOpPack::SubMultiVectorView<double> const&) const /projects/albany/nightlyAlbanyCDash/test/TrilinosInstallC11/include/Thyra_TpetraVectorSpace_def.hpp:187
```
So we need to figure out who is doing stuff wrong: us or Trilinos...

**Comment by mhoemmen** [comment]
@cgcgcg Hm, it could be that those RCPs in `set_extra_data` are persisting.

**Comment by ikalash** [comment]
@mhoemmen , @cgcgcg: thanks for looking at it.  It would be helpful to me to have some input from you as to whether some of the code in that PR might be problematic - it is very hard for me to figure out from the backtrace if the problem is in Albany or Trilinos.  I sort of think it's the latter at this point, but I may be wrong.

**Comment by cgcgcg** [comment]
@mhoemmen @ikalash Hm, sounds like I need to have another look at that. It's weird that this is not happening anywhere in Trilinos. But I can definitely run some Trilinos test that will use this functionality through valgrind.

**Comment by ikalash** [comment]
Thanks @cgcgcg .  I’m happy to provide scripts to reproduce the issue she see in Albany if you wanted to look at it there.  It should be pretty easy to build the code with my instructions.

**Comment by cgcgcg** [comment]
@ikalash That'd definitely be helpful! Can you email them to me?

**Comment by ikalash** [comment]
Just following up: @cgcgcg, have you had a chance to look at this issue?

**Comment by cgcgcg** [comment]
I totally forgot about this. I don't think I ever got your build scripts..

**Comment by ikalash** [comment]
Really?  My bad!  I will send them now.

**Comment by ikalash** [comment]
@cgcgcg , I wanted to follow up again: any updates on this?

**Comment by ikalash** [comment]
Been working with Christian Glusa to resolve this.  Fix was pushed to Trilinos earlier today, and I've verified that the tests are fixed.  Dashboard should be all green once more tomorrow!
