### ISSUE TITLE
Issue with ATO problems having distributed parameters / responses run with AlbanyT executable

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#51]
There seems to be one remaining issue in getting ATO ported to Tpetra/Thyra from Epetra/EpetraExt, which affects tests with distributed parameters/responses:

- Constraint_2D_adj
- Constraint_2D_fd
- DistParam_2D
- BodyForce_2D (with NLopt)
- CurrentOpt (with NLopt)
- ResidualStrain (with NLopt)
- VolumeObj_StiffnessCon (with NLopt)
- VolumeObj_StressCon (with NLopt)

When running these problems with the AlbanyT executable, the following exception is thrown: 

p=0: *** Caught standard std::exception of type 'std::logic_error' :

 /home/ikalash/LCM/Trilinos/build-debug-no-dtk-ikt/install/include/Thyra_ModelEvaluatorBase_def.hpp:2102:

 Throw number = 1

 Throw test that evaluated to true: !deriv.isSupportedBy(derivSupport)

 Thyra::ModelEvaluatorBase::OutArgs<Scalar>::assert_supports(OUT_ARG_DgDp,j,l):

 model = 'Piro::NOXSolver<double>':

 Error, The argument DgDp(0,0) = Derivative{derivMultiVec=DerivativeMultiVector{multiVec=Thyra::TpetraMultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >{rangeDim=651,domainDim=1},orientation=DERIV_MV_BY_COL}}
 is not supported!

 The supported types include DerivativeSupport{DERIV_LINEAR_OP}!

The source of the problem is that, in ATOT::Solver, when  

*(ret.responses_outT) = ret.modelT->createOutArgs();

is called in ATOT::Solver::CreateSubSolver, the code does not go into the Albany::ModelEvaluatorT::createOutArgsImpl routine, as it should, so the right supports do not get set.  This is different than the behavior with the EpetraExt model evaluator version of the code. 

After looking at the Thyra::ModelEvaluator class with @agsalin , it seems the issue is that, for the code to go into the Albany::ModelEvaluatorT::createOutArgsImpl routine when createOutArgs is called, the call to createOutArgs needs to happen in ATOT::Solver::evalModelImpl.  

A fix to the issue would be to redesign the ATOT::Solver class so that the code that sets ret.responses_outT and ret.response_inT (lines 1716-1780 in ATOT_Solver.cpp) is called in ATOT::Solver::evalModelImpl rather than ATOT::Solver::CreateSubSolver.  I have asked @jrobbin to look into such a redesign.

**Comment by bartgol** [comment]
Since we no longer have an `AlbanyT` executable, I'm going to close this. If there's some problem with ATO tests, we should open a new up-to-date issue.
