### ISSUE TITLE
Albany User Meeting 2020 - Jan 27-28 in Albuquerque, NM

### ISSUE THREAD

**Issue by bartgol** [SNLComputation/Albany#530]
This "issue" is to reach out to everyone who is interested in the Albany User Meeting. I will post updates as new items come to mind.

Point of Contact: Luca Bertagna (lbertag at sandia dot gov)

**Important notes**

- If you plan to give a presentation, please send me the title and the approximate time you think it would take (not including question/discussion). Don't try to crop it (for now). If later we see we have too many discussions/presentation, we will ask you to cut it down a bit.
- If you would like to have a round table discussion on a particular topic, please send me an email with a tentative topic title.
- If you are a Foreign National, please get in touch with me asap, since we need to get some paperwork done to get you on Sandia's premises.

**Lodging**

Here's a list of hotels in the uptown area, which also offers some nice restaurants/bars for the evening. Uptown is about 10min from the CSRI building, and about 15min from the airport.

Sheraton Albuquerque Uptown
2600 Louisiana Blvd NE
Albuquerque, NM  87110
Reservations – 844-631-0595

Hyatt Place Albuquerque/Uptown
6901 Arvada Ave NE
Albuquerque, NM  87110
Reservations – (505) 872-9000

Homewood Suites by Hilton Albuquerque
7101 Arvada Ave NE
Albuquerque, NM  87110
Phone – (505) 881-7300

Hilton Garden Inn Albuquerque Uptown
6510 Americas Pkwy NE
Albuquerque, NM  87110
Phone – (505) 944-0300

Marriott Albuquerque
2101 Louisiana Blvd NE
Albuquerque, NM  87110
Reservations – 844-631-0595

**Access to Sandia's premises**

If you are not a Sandia employee, we need to submit some paperwork to get access to Sandia's premises. This can take some time for foreign nationals, especially if from "sensitive" countries. Please, send me your email, and I will forward you the form to fill out.

**List of confirmed speakers (please update as needed)**

1. Josh Robbins (@jrobbin): "Albany and Plato Engine: Multi-objective optimization using MPMD"
2. Tim Fuller (@tjfulle ) [tentative; may not be able to travel, so this may be a talk via Skype]: "PFLOTRAN: Implementing an external flow code as an Albany evaluator"
3. Irina Tezaur (@ikalash): "The Schwarz alternating method for continuum-to-continuum multiscale coupling in solid mechanics" 
4. Roger Pawlowski (@rppawlo ) [may not be able to travel, so this may be a talk via Skype]: Sacado hierarchical parallelism / recent Phalanx changes (debugging tools, shared memory features) [title TBD]
5. Jerry Watkins (@jewatkins ): update on performance portability work in Albany [title TBD] 
6. Luca Bertagna (@bartgol ): hydrology for LandIce + recap of thyra refactor 
7. Jacob Pessin () - A Thermal-Mechanical Finite Element Formulation for Simulating Additive and Subtractive Manufacturing
8. Ruixiong Hu (@RuixiongHu)- Finite Element Modeling of Additive and Subtractive Manufacturing accounting for Geometry Evolution
9. Alejandro Mota (@lxmota ): "Strongly-coupled thermo-mechanical model of permafrost for the simulation of Arctic coastal erosion"
10. Mauro Perego (@mperego ): Albany Land-Ice (ALI) and optimization [title TBD] 
11. Justin Clough (@JustinClough ): "Inelastic deformation of a panel subject to hypersonic loads"

**Comment by jewatkins** [comment]
I could probably give an update on performance portability in Albany. I could try to make it short and we could try to have more time dedicated to discussion.

**Comment by jewatkins** [comment]
@SNLComputation/albany

**Comment by RuixiongHu** [comment]
Hello Luca @bartgol,

This is Ruixiong, I'm international student holding F1 visa with citizenship from China. And I think I'll be at the meeting.

So please let me know if there's anything particular I need to do. I'll start them asap.

Thanks and have a nice day,
Ruixiong

**Comment by maxrpi** [comment]
Remind me of the dates for this please?

**Comment by ikalash** [comment]
@maxrpi : Jan. 27-28 in Albuquerque, NM.  I just updated the issue to contain this information.

**Comment by bartgol** [comment]
> Hello Luca @bartgol,
> 
> This is Ruixiong, I'm international student holding F1 visa with citizenship from China. And I think I'll be at the meeting.
> 
> So please let me know if there's anything particular I need to do. I'll start them asap.
> 
> Thanks and have a nice day,
> Ruixiong

Hi Ruixiong, please, see my last edit to the message at the top.

Everyone who is not a SNL employee needs to contact me. If you are a foreign national, it is important we get your paperwork started soon.

**Comment by ikalash** [comment]
I have instructed all the RPI folks who are considering attending to contact you, Luca.  Luca's email is lbertag@sandia.gov .  @maxrpi said there will likely be 1-2 talks from the RPI gang.

**Comment by RuixiongHu** [comment]
> > Hello Luca @bartgol,
> > This is Ruixiong, I'm international student holding F1 visa with citizenship from China. And I think I'll be at the meeting.
> > So please let me know if there's anything particular I need to do. I'll start them asap.
> > Thanks and have a nice day,
> > Ruixiong
> 
> Hi Ruixiong, please, see my last edit to the message at the top.
> 
> Everyone who is not a SNL employee needs to contact me. If you are a foreign national, it is important we get your paperwork started soon.

Hi Luca,

My email is: hur3@rpi.edu.

And I also sent you an email. We'll be thinking about the presentations and will get you back on it later.

Thanks

**Comment by RuixiongHu** [comment]
Hello,

Hope everything goes well.

I just figured out the link to the meeting agenda is somewhat not accessible for now, so I was wondering if it's under edition or something.

https://github.com/SNLComputation/Albany/wiki/2020-Albany-Users-Meeting-(Jan-27-28,-Albuquerque)

The other thing is that we'll be leaving early afternoon on Tuesday but we're really interested in the block discretization and some other topics planned on Tuesday, so I'm just wondering if you guys could push the performance test section later that day?

Thanks and have a good day,
Ruixiong

**Comment by jewatkins** [comment]
Hmm try this link:
https://github.com/SNLComputation/Albany/wiki/2020-Albany-Users-Meeting-(Jan.-27-and-28,-Sandia-National-Laboratories,-Albuquerque,-NM)

**Comment by ikalash** [comment]
It works for me: https://github.com/SNLComputation/Albany/wiki/2020-Albany-Users-Meeting-(Jan.-27-and-28,-Sandia-National-Laboratories,-Albuquerque,-NM).  I think the problem is that I changed slightly the title of the page…  sorry about that. 

Yes we will be sure to discuss the block discretization in the first part of the meeting on Tuesday.

**Comment by bartgol** [comment]
Hi Ruixiong.

Yeah, unfortunately, changing the title of the wiki page also changes the link. Someone (maybe me?) changed the title in the past, and that resulted in a broken link. Jerry's link is the current (and hopefully final) one.

As for Tuesday, we will decide the order of topics discussion on Monday morning (in the logistic intro), so that we can try to accommodate needs such as yours.

**Comment by ikalash** [comment]
SHoot, this is my fault...  I renamed the page...  I will name it back so there is no confusion.

**Comment by bartgol** [comment]
No worries. You can leave it like that if you want. Josh also wrote me about it, and I gave him the new link.

**Comment by ikalash** [comment]
The old one is in the calendar invite I sent so I prefer to keep it.  I did not realize that Wiki does this with page titles...

**Comment by bartgol** [comment]
Sounds good. I created a page with the new (or I guess now it's old?) name, that redirects to the old (new?) one. Either link should now work.

Yeah, this thing that updating the title changes the link is inconvenient (at best). They should just keep a running counter of pages, and just assign the current counter as page id, to be used in the link. Just like it's done for issues/prs...

**Comment by ikalash** [comment]
Thank you to everyone who attended and/or presented at the meeting!  We had some very nice talks and discussion!  I have posted the slides from the talks on the AUM 2020 wiki page: https://github.com/SNLComputation/Albany/wiki/2020-Albany-Users-Meeting-(Jan-27-28,-Albuquerque) .  Some of the slides are missing currently, as I have not received them or they are awaiting Review & Approval.  I will post them as soon as possible.  

I have also posted some notes from the discussion part, and have begun to open issues stemming from the discussions earlier today.  Please feel free to add to these notes if you feel I omitted something.  Also, please feel free to create issues regarding TODOs that stemmed from today's discussion, which I started to do a few minutes ago.  

Safe travels back home, to those who are not local to ABQ!
