### ISSUE TITLE
Add version information to std out

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#535]
I'd like to add version information to std out. In particular, I'd like to print:
1. Trilinos/Albany branch and commit hashes
2. compiler, mpi, tpl versions

at runtime.

Currently, I see two tasks towards implementing this: 
1. Add bash commands to our cmake file and save Trilinos/Albany version information as variables. This has the down side that one has to call cmake to populate the variables which means that information could potentially be out-of-date during runtime. 
2. Run bash commands in a cpp file and get tpl information on the fly.

The end result should be that we dump all this information to std out every time Albany is called. Would this be useful for anyone else? Would everyone be okay with this being on by default? Any suggestions?

@ikalash

**Comment by ikalash** [comment]
I think @lxmota has a way to extract the hashes.  I'd probably vote for 1. to extract compiler version, etc.  All that info should get echoed to the screen when the code is being configured.

**Comment by jewatkins** [comment]
I'd like it during runtime. Would that be too verbose for some?

**Comment by lxmota** [comment]
@ikalash I just use a script to extract the Trilinos and Albany latest commit hashes if the tests succeed. I haven't checked in ages if that is still working ... no, it stoped working about a year ago. Need to check.

@jewatkins Not at all. Fine with me.

**Comment by ikalash** [comment]
Hmmm, OK so I guess you'd have to get the info within the code, and optionally print it in Main.C?  Is that what you had in mind?

**Comment by jewatkins** [comment]
I think the branches/hashes is okay to have as cmake variables (which then become macros). The compiler, tpl versions should probably be extracted at runtime though which means calling bash commands from a cpp file. But I'm open to doing the same thing (i.e. make them cmake variables which are converted to macros).

**Comment by jewatkins** [comment]
I was hoping to not make it an option, just call the function which prints the version info all the time in Main.

**Comment by bartgol** [comment]
I had a similar urge when I opened #490 . However, I realized that Trilinos does not export its sha (sigh).

Extracting triliinos info from the src code is obviously possible, with something like this

```
EXECUTE_PROCESS (COMMAND git rev-parse HEAD
                 WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
                 OUTPUT_VARIABLE LAST_GIT_COMMIT_SHA
                 OUTPUT_STRIP_TRAILING_WHITESPACE)
```

However, this presumes you have access to trilnos src tree, which we don't in general. I'm open to any idea, but I'd like to avoid requesting a trilinos src tree just for the sake of printing a sha.

**Comment by jewatkins** [comment]
I see `TrilinosRepoVersion.txt` in the install directory (which we have a variable for) and it includes a sha. I was hoping to use that. It doesn't have the branch though.

**Comment by bartgol** [comment]
> I was hoping to not make it an option, just call the function which prints the version info all the time in Main.

If you have the sha at config time, you can stuff it in `Albany_config.h`, and then retrieve it with a simple function (without having to do system calls at runtime).

**Comment by bartgol** [comment]
> I see `TrilinosRepoVersion.txt` in the install directory (which we have a variable for) and it includes a sha. I was hoping to use that. It doesn't have the branch though.

SWEEET! I never looked at that file. Silly me! Then I think we can easily do this. I vote for using a cmake snippet like the one I posted to detect the sha at config time, and stuff it in `Albany_config.h`. If the trilinos installation changes for any reason, cmake will run again anyways, updating the sha in `Albany_config.h`

**Comment by jewatkins** [comment]
That's what I had in mind for the shas. But I was thinking system commands for compiler version, etc.

**Comment by bartgol** [comment]
> That's what I had in mind for the shas. But I was thinking system commands for compiler version, etc.

Compiler versions are also detected by CMake at config time. We should be able to store them in a header file, say `Albany_compiler_config.h`. We could even store the compiler flags in there.

**Comment by jewatkins** [comment]
> If the trilinos installation changes for any reason, cmake will run again anyways, updating the sha in `Albany_config.h`

Ah okay that seems safe for the Trilinos sha then. I think the same thing happens if you switch the Albany branch but I'm not sure, just what I've noticed.

**Comment by bartgol** [comment]
>     1. Add bash commands to our cmake file and save Trilinos/Albany version information as variables. This has the down side that one has to call cmake to populate the variables which means that information could potentially be out-of-date during runtime.

The information is config-time information, and cannot be outdated (except for Albany's sha). Trilinos sha, compiler, tpls, and the likes are set once and for all when cmake runs (that's when the paths to compiler. tpls, trilinos, and the likes are set). It cannot get outdated.

As for Albany's sha, if you are doing development, you probably are not interested in Albany's sha. That's more useful for downstream applications using Albany or for nightlies. Either way, the sha should not change from config time to run time.

**Comment by jewatkins** [comment]
Hmm okay it seems reasonable to store at config time then. Let's go with that approach.

**Comment by bartgol** [comment]
> I think the same thing happens if you switch the Albany branch but I'm not sure, just what I've noticed.

I think you're right, since switching branches changes the timestamp of files, including cmake-triggering files.

**Comment by mperego** [comment]
Thanks @jewatkins . This is something I wish we had since long time

**Comment by jewatkins** [comment]
This has been added. The mpi/tpls versions are bit tricky and case dependent so I didn't add those. I might add them in the future if they become relevant.

The header style can be changed if someone prefers a different style.
