### ISSUE TITLE
Slowdown of MueLU AIS test case on waterman 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#538]
The FO_AIS_16km_MueLu test began timing out on 11/14; last successful run was 11/11.  Attached is a screenshot showing CPU times.

http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=91070#

Anyone have idea what happened to cause the slowdown?

![AIS_waterman_time_edited-1](https://user-images.githubusercontent.com/7018124/69265086-93bf2900-0b96-11ea-9e86-44b9c6fd9e32.jpg)

**Comment by bartgol** [comment]
10x slowdown?!? I know they upgraded the default version of cuda to 10, but I don't know if we are loading that in the tests, or whether we were already, or whatnot.

**Comment by ikalash** [comment]
More than 10x...  currently the tests time out so they'd take even longer if allowed to complete!!  It would be good to look at relative timings for other tests now vs. before.   I'll do that when I am at a computer.

**Comment by ikalash** [comment]
I looked at all the test timings on waterman today compared to on 11/20 and ranked them in the ones that had the most substantial slowdown (not including the AIS MueLu case I opened this issue about).   Here they are.  The second column is the time on 11/11; the third one is the time today; the last one is how many times slower today's run is relative to 11/11.  

Heat1DPeriodic_Tpetra | 15.92 | 217.1 | 13.64
TransientHeat1D_Tpetra | 28.31 | 336.97 | 11.9
Heat1DWithSource_Tpetra | 13.46 | 151.36 | 11.25
FO_Test_CircularShelf_Tpetra | 19.95 | 223.51 | 11.2
Aeras_TC5_explicitHV_nu8e15_novort_BackwardEuler | 21.11 | 222.85 | 10.56
Aeras_TC1_SlotCyl_explicitHV_nu1e17_BackwardEuler | 26.34 | 215.66 | 8.188
Aeras_TC1_SlotCyl_implicitHV_nu0_BackwardEuler | 45.99 | 336.5 | 7.317
FO_GIS_SensSMBwrtBeta_Tpetra | 30.6 | 216.81 | 7.085
FO_GIS_Unstructured_Memoization | 12.75 | 90.32 | 7.084
Aeras_TC5_explicitHV_nu8e15_vort_BackwardEuler | 28.26 | 190.41 | 6.738
Heat1DPeriodic_Tpetra | 15.92 | 217.1 | 13.64
TransientHeat1D_Tpetra | 28.31 | 336.97 | 11.9
Heat1DWithSource_Tpetra | 13.46 | 151.36 | 11.25
FO_Test_CircularShelf_Tpetra | 19.95 | 223.51 | 11.2
Aeras_TC5_explicitHV_nu8e15_novort_BackwardEuler | 21.11 | 222.85 | 10.56
Aeras_TC1_SlotCyl_explicitHV_nu1e17_BackwardEuler | 26.34 | 215.66 | 8.188
Aeras_TC1_SlotCyl_implicitHV_nu0_BackwardEuler | 45.99 | 336.5 | 7.317
FO_GIS_SensSMBwrtBeta_Tpetra | 30.6 | 216.81 | 7.085
FO_GIS_Unstructured_Memoization | 12.75 | 90.32 | 7.084
Aeras_TC5_explicitHV_nu8e15_vort_BackwardEuler | 28.26 | 190.41 | 6.738

We should probably contact the waterman sysadmins about this, if the conjecture is that the bad performance is simply due to an environment change.

**Comment by bartgol** [comment]
It is either a different waterman environment or some changes in Trilinos, since I don't think we had potential performance-changing commits in Albany.

**Comment by ikalash** [comment]
Seems running on the 'dev' queue (waterman[9-10]) remedies the problem with both cuda 9 and cuda 10.  These nodes have more recent firmware.  I imagine that the other nodes will be upgraded at some point too with the newer firmware - waiting to hear back from the sysadmins.  

I have changed the nightly job to use the dev queue and also to use cuda10 instead of cuda9, now that cuda10 is available.
