### ISSUE TITLE
LandIce: What exactly does Populate Mesh do and how does it affect performance?

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#540]
I'm curious about this feature because I recently ran a GIS case w/o running `Populate Mesh` first. I assumed that the performance benefit would just be in setup time (i.e. constructing a 3d discretization from a bunch of 2d files) but it seemed to significantly affect finite element assembly and preconditioner construction too:
```
Starting from a single 2D mesh:
Albany: **Total Fill Time**: 8.35927
NOX Total Preconditioner Construction: 3.0477

Starting from distributed 2D populated mesh:
Albany: **Total Fill Time**: 5.6138
NOX Total Preconditioner Construction: 1.39226
```
In finite element assembly, it seems like the performance change is in the export routines. Here's the change I made to the input file:
```
Starting from a single 2D mesh:
        Use Serial Mesh: true
        Exodus Input File Name: mesh/Greenland.exo
*set Field Origin to File for all fields*

Starting from distributed 2D populated mesh:
        Restart Index: 1
        Exodus Input File Name: mesh/gis_basal_populated.exo
*set Field Origin to Mesh for all fields*
```
I highly suspect it has something to do with how the mesh is partitioned but I generated the populated mesh with `Serial Mesh` as well so I would think that it would use the same partitioning. I'm going to try regenerating the populated mesh again just to make sure.

@mperego @bartgol @ikalash Any ideas? Thanks!

**Comment by bartgol** [comment]
Uh, this is interesting. My best guess is a different behavior of stk structures when working on a mesh already partitioned vs when stk partitions a mesh from scratch. There may be some memory optimizations that are not performed, or we may have some memory fragmentation in the latter case that is not there in the former.

**Comment by jewatkins** [comment]
Hmm I could see that. If I start with a single 2D mesh will Albany partition then extrude or extrude then partition? I suppose that could cause a difference too.

**Comment by bartgol** [comment]
Albany partitions the basal mesh, then extrudes. This guarantees that a whole column stays on a single mpi process.

**Comment by jewatkins** [comment]
Okay that's not it then.

**Comment by jewatkins** [comment]
I can confirm that using Populate Mesh first is indeed faster overall. I also tried manually decomposing the mesh first and got an even faster time (even the linear solves converged faster):
```
Single 2D mesh:
Albany: Total Time: 19.7359
Albany: **Total Fill Time**: 8.35927
NOX Total Preconditioner Construction: 3.0477
NOX Total Linear Solve: 2.08549

Decomposed 2D mesh:
Albany: Total Time: 12.893
Albany: **Total Fill Time**: 5.51451
NOX Total Preconditioner Construction: 2.70436
NOX Total Linear Solve: 1.9126

Single 2D mesh to distributed 2D populated mesh:
Albany: Total Time: 13.9908
Albany: **Total Fill Time**: 5.87294
NOX Total Preconditioner Construction: 1.89833
NOX Total Linear Solve: 2.02833

Decomposed 2D mesh to distributed 2D populated mesh:
Albany: Total Time: 9.59667
Albany: **Total Fill Time**: 5.35079
NOX Total Preconditioner Construction: 1.22049
NOX Total Linear Solve: 1.82476
```

**Comment by bartgol** [comment]
This is getting interesting. I think our next step should be running a memory checker, like massif, and see if one of the two is using much more memory. It is possible (though I wouldn't bet too much on it) that some stk stuff is not correctly freed up upon partitioning.

Tell me if I understand well your 3 cases:

1) start from a monolithic mesh, break it online, and load all fields from ascii, and run
2) start from a decomposed mesh, but still load everything from ascii, and run
3) start from a monolithic mesh, load inputs from ascii, break the mesh, save, and exit
4) start from a decomposed mesh, populate it, then exit

Is that correct? So 3/4 only run populate mesh problem, while 1/2 runs whatever landice problem, loading the files too?

**Comment by jewatkins** [comment]
The first two load the files directly and the last two run populate mesh first, save, then run:
1. start from a monolithic mesh, load fields from ascii, break the mesh and run
2. start from a decomposed mesh, load fields from ascii and run
3. start from a monolithic mesh, load fields from ascii, break the mesh, save and exit, run w/ populated mesh
4. start from a decomposed mesh, load fields from ascii, save and exit, run w/ populated mesh

**Comment by ikalash** [comment]
If you run ``decomp --help", here is the output: 

```
[ikalash@camobap von-Neumann-2020]$ decomp --help
Usage:  decomp [-h] --processors <processor count> [-n <nemslice options>]
               [--root <root directory>] [--subdir <sub directory]
               [--multikl] [--spectral] [--inertial] [--linear]
               [--rcb] [--rcb_ignore_z] [--rib] [--hsfc] [--random] [--scattered]
               [...others...] meshfile.ext

Decomposition methods: [0..3] = speed ranking 0=fastest
              (See chaco and/or zoltan documentation for more details)
 --multikl:   [3] Multilevel KL. Gives high quality partitions.
                  Slow, high memory use.
 --spectral:  [2] use eigenvectors of a matrix constructed from the
                  graph to partition the graph.
 --hsfc       [?] Hilbert Space-Filling Curve (uses Zoltan)
 --rib:       [?] Recursive Inertial Bisection (uses Zoltan)
 --rcb:       [?] Recursive Coordinate Bisection (uses Zoltan)
 --rcb_ignore_z:       [?] Recursive Coordinate Bisection (uses Zoltan), ignoring the z dimension coordinates
 --inertial:  [1] (default) vertices divided into sets of equal mass by planes
                  orthogonal to the principle axis. Good, fast, medium memory
 --linear:    [0] vertices in order first n/p to proc 0, next to proc 1.
                  (fast and sometimes good).
 --random:    [0] vertices are assigned randomly to sets in a way that
                  preserves balance.
 --scattered: [0] vertices are handed out in order with the next vertex
                  going to whichever set is smallest.
 --brick      [-] special decomposition method; not useful for general use.
 --zpinch     [-] special decomposition method; not useful for general use.

NOTE: The decomposition options can also be specified as "-l type"
       For example "--multikl" is the same as "-l multikl"

Other options:
--help             Print this message (-h)
--nodal            Nodal Decomposition (-N)
--elemental        Elemental Decomposition (default, -E)
--input            Optional nem_slice input file (-i)
--viz_mesh         Output mesh showing processor distribution of elements. (-V)
--spheres_linear   Decompose sphere elements using linear method (matches old behavior) (-s)
--processors #p    Specify number of processors (-p, -j)
--root root_dir    Root directory to begin the path to on the separate disks (-R)
--subdir sub_dir   Continuation of the path on the separate disks to the files (-S)
--64               Force creation of 64-bit integer decomposed files (-6)

   help-email:  seacas-users@software.sandia.gov
```

I wonder if the stk decompositions are using a different decomposition algorithm than the default one used by decomp (which seems to be --inertial).  One could run decomp with some of the other options to compare the decomposition with the stk one, I suppose, if we really wanted to dig into it (maybe it's not worth it though.,..).

**Comment by jewatkins** [comment]
Probably the next step for the online decomp issue would be to try to compare the different decompositions but yeah I'm not sure if it's worth doing right now. I'm satisfied with manually decomposing.

**Comment by ikalash** [comment]
Right.  And it sounds like there's a bigger problem that is within Albany - we hadn't gotten to that piece of info on the concall when I made the above comment.

**Comment by jewatkins** [comment]
Yeah, without knowing a bit more about the preconditioner used by ml (which seems to be the source of slowdown for the non-populated mesh case), I'm a bit unsure about that too.

**Comment by ikalash** [comment]
We could involve Ray if we want to get into the nitty gritty details of ML; but maybe it makes sense to run the code through valgrind or a memory sanitizer first.

**Comment by jewatkins** [comment]
Probably not worth it right now. As long we run Populate Mesh first, it's not an issue. What may be concerning is when we run mpas. I will probably try the address sanitizer in that case when I have more time.

**Comment by ikalash** [comment]
Fine with me.

**Comment by bartgol** [comment]
I think our testing focused on the approach DecomposeOffline+RunOnDecomposedMesh, so I'm gonna close this for now. @jewatkins feel free to reopen if this is still a topic of discussion.
