### ISSUE TITLE
Spack install fails

### ISSUE THREAD

**Issue by nestordemeure** [SNLComputation/Albany#541]
Albany currently does not compile with Spack (`spack install albany`) due to [issue 5764](https://github.com/trilinos/Trilinos/issues/5764).

This seems to be linked to the fact that the recipe points to [https://github.com/gahansen/Albany](https://github.com/gahansen/Albany) which has not been updated with a fix.

**Comment by ikalash** [comment]
@nestordemeure : Albany moved some time ago to https://github.com/SNLComputation/Albany and the path in the spack build definitely should be updated.  I believe @gahansen is the owner of the spack build - Glen can you please update the path?

**Comment by ikalash** [comment]
@nestordemeure : also, you appear to be a new user of Albany - welcome!  What will you be using Albany for out of curiosity?  Do not hesitate to reach out if you have questions/issues!

**Comment by gahansen** [comment]
Hi Irina,

It would probably be better if I walked someone else through this with Spack. This capability wasn’t used much but I think it is the future, so I would hate to lose it. I probably will not be able to be a very good custodian of it in the future so it is probably better to transition the knowledge to someone else. Not sure who – are you interested?

Thanks!

Glen

--

Glen Hansen
Manager, Computational Multiphysics Dept. (1443)
Sandia National Laboratories
CSRI/168    MS-1321    (505) 845-7193
gahanse@sandia.gov<mailto:gahanse@sandia.gov>

**Comment by ikalash** [comment]
Sure I'd be interested to know how the spack build works.  Maybe we can meet next week while I'm in town for you to walk me through it.  Where would the file that points to the Albany repo when building spack be located?  I grepped the Albany repo and couldn't find it.  I would think resolving the issue for @nestordemeure would be simple - just a matter of fixing the path wherever it is (provided that the spack build still works, which it may not, since not many people use it, as you pointed out).

**Comment by nestordemeure** [comment]
I was able to resolve the issue by changing the path (locally) in the Spack recipe, it should be easy to fix upstream.

Regarding my use case, I want to compare a maximum of numerical solvers on a variety of realistic test cases in order to measure their run times and numerical error (using an instrumented numerical type I designed).
I was pointed to Albany as it is template based (which should make changing the types much easier), based on trilinos (giving me acces to a variety of solvers) and already has a large number of examples that I could hopefully reuse.

I would take any pointer / documentation on running the test cases with a different numerical type and using albany as a library in a pipeline (if it is possible).

**Comment by ikalash** [comment]
@nestordemeure : glad you figured it out - I was going to suggest you do exactly what you did.

The work you describe sounds like it will be very much of interest to many of us!  There are a lot of nice problems in Albany.  I would specifically point you to the LandIce and LCM directories.  The former is for a large project involving land ice modeling, for which Albany is the production code.  We've done some solver work here, in particular, see http://www.sandia.gov/~ikalash/_assets/documents/sisc_amg_ice.pdf .  LCM stands for laboratory for computational mechanics, and it has a lot of solid mechanics problems, some with very sophisticated material models. Here, solvers can be important as well; see this SAND report from awhile ago: http://www.sandia.gov/~ikalash/_assets/documents/kalash_LCM_SAND_june2012.pdf .  Unfortunately there isn't a lot of documentation about the Albany test cases, but when you're ready to run, I could point you to relevant cases (feel free to email me directly at ikalash@sandia.gov ).  Also, note that the tests in the Albany repo by construction are somewhat small, but we do have larger performance tests locally or in other repos - I'm happy to share the input / mesh files for those as well. 

Lastly, we have a weekly conference call on Tuesday at 1PM PST where folks interested in Albany are welcome to call in to ask questions, discuss issues, etc.  This would be somewhat late your time (10PM), but if you're interested, I can forward you the call in information.

Also, we will have an Albany User Meeting the last week of January - please see #530 .  You're welcome to attend (following the approval of some paperwork), but I realize you're in France so it may not be feasible.

**Comment by ikalash** [comment]
@nestordemeure : can you actually clarify what you mean by different numerical type?  Do you mean you are interested in mixed precision algorithms?  The way the code is designed, it is called as needed with different types, specifically double or long to evaluate the residual, and Automatic Differentiation (AD) types to evaluate Jacobian/Tangent.  

You can find slides and a video of a talk I gave at SIAM CSE last year here: 

http://www.sandia.gov/~ikalash/_assets/documents/Tezaur_SIAMCSE2019_Albany_final.pptx 
https://www.youtube.com/watch?v=CVBW8s2vz_8

**Comment by nestordemeure** [comment]
Thank you for the slides! I will read them tomorow and come back to you if I have questions.

Regarding my numerical type (the code is now open but the corresponding paper is awaiting publication), I have overloaded operators in order to measure the numerical accuracy of the instrumented computation (with appropriate traits to be compatible with Trilinos).
In use it is kind of similar to [CADNA](http://cadna.lip6.fr/Examples_Dir/ex3.php) but the underlying method is very different, faster and, in my experiments, more accurate (making it viable for the instrumentation of large application).
Now we would like to instrument numerical solvers in order to see what kind of informations could be obtained (which seem to be the kind of thing Trilinos was designed for seing the work on Sacado and Stokos).

**Comment by ikalash** [comment]
Interesting.  I am not familiar with CADNA.  I just looked at the website, and it appears it keeps track of how round-off propagates and affects computations - I imagine your tool does something similar.  I think analysis along the lines of what you are proposing would be particularly interesting in different operators, where algorithms can have different orders of operations and give rise to non bit-for-bit results.  It may also be useful in trying to understand the effect of reduced and mixed precision algorithms for computations.  Tagging @bartgol and @jewatkins who may be interested in these two topics, in case they want to comment.

I can't say w/o learning more about your tool how it could be integrated into Albany.  We can definitely talk about this when you're ready.  Your paper would be interesting to have a look at once you're comfortable releasing it or it's published.

**Comment by jewatkins** [comment]
This definitely sounds interesting, please keep us posted.

**Comment by ikalash** [comment]
@nestordemeure : FYI, I have a PR to fix this issue pending - https://github.com/spack/spack/pull/14215 .  It looks like there were some invalid Trilinos options as well as the incorrect Albany path.  I also removed some obsolete enables from Albany.  Hopefully the PR will go in soon.  Sorry about the delay!

**Comment by nestordemeure** [comment]
Great, I am currently running benchmarks with Trilinos for my project (Albany is in the backlog, I will contact you has soon as I am blocked or have something that might be of interest).

**Comment by ikalash** [comment]
FYI, since it is proving to be difficult/impossible to push the required changes to the spack master branch, please use the albany branch of this version of spack for Albany: https://github.com/SNLComputation/spack/tree/albany .  The Albany spack wiki instructions have been updated to reflect the change: https://github.com/SNLComputation/Albany/wiki/Building-Albany-using-SPACK.
