### ISSUE TITLE
Fill in Discussion topics on Wiki page for AUM 2020 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#549]
@bartgol : can you please create a Wiki page for AUM 2020?  Things to put there are:

- Agenda with names of speakers/talk titles
- Logistical information (hotel + restaurant info, maps, etc.) 
- Agenda for items to discuss - perhaps you could start this @bartgol , and others can add other topics?  I have a number of topics I'd like to discuss which I can add once we have the site up.

**Everyone:** please check out [the Wiki page](https://github.com/SNLComputation/Albany/wiki/2020-Albany-Users-Meeting-(Jan.-27-and-28,-Sandia-National-Laboratories,-Albuquerque,-NM))  for AUM 2020 that Luca created and fill in topics you would like to discuss during the discussion part of the meeting on Day 2.  We should also think if there is someone from Trilinos we wish to involve (e.g. folks developing performance testing capabilities) in any of the discussions, so we can invite them, if that makes sense.

**Comment by bartgol** [comment]
I did create a page yesterday, with speakers and discussion items. I should probably add logistical info too though.

**Comment by ikalash** [comment]
Ah ok, I see it now.  Putting the link here so others can access it: https://github.com/SNLComputation/Albany/wiki/2020-Albany-Users-Meeting-(Jan-27-28,-Albuquerque) .
