### ISSUE TITLE
FPEs in Enthalpy test on CEE builds 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#551]
Two of the CEE intel builds have FPEs for the Enthalpy tests: 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=5316310&build=92517

```

************************************************************************
-- Nonlinear Solver Step 0 -- 
||F|| = 1.651e-03  step = 0.000e+00  dx = 0.000e+00
************************************************************************

[cee-compute011:03807] *** Process received signal ***
[cee-compute011:03808] *** Process received signal ***
[cee-compute011:03809] *** Process received signal ***
[cee-compute011:03806] *** Process received signal ***
[cee-compute011:03807] Signal: Floating point exception (8)
[cee-compute011:03807] Signal code: Floating point overflow (4)
[cee-compute011:03807] Failing at address: 0x2a09e75
[cee-compute011:03808] Signal: Floating point exception (8)
[cee-compute011:03808] Signal code: Floating point overflow (4)
[cee-compute011:03808] Failing at address: 0x2a09e75
[cee-compute011:03809] Signal: Floating point exception (8)
[cee-compute011:03809] Signal code: Floating point overflow (4)
[cee-compute011:03809] Failing at address: 0x2a09e75
[cee-compute011:03806] Signal: Floating point exception (8)
[cee-compute011:03806] Signal code: Floating point overflow (4)
[cee-compute011:03806] Failing at address: 0x2a09e75
[cee-compute011:03809] [ 0] /lib64/libpthread.so.0(+0xf630)[0x7fed3931f630]
```
One build uses gcc, one uses intel:
http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany

@bartgol : you are the owner of this test I believe - can you please look into this?  

The tests where the issue is showing up were not running for about a month due to cee-compute nodes being down, so it's not clear exactly when the problem started.  Seems things were good on 12/23: http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany&date=2019-12-23 .

**Comment by mperego** [comment]
This should be fixed after issue trilinos/Trilinos#6632 is addressed.

**Comment by mperego** [comment]
@ikalash The new LandIce FO_Thermo tests failing are still related to this issue. I tweaked them a bit yesterday, that's why they started failing only now.

**Comment by ikalash** [comment]
Ah ok I see.  Are there plans to fix this?

**Comment by mperego** [comment]
Yes, I talked to Eric Phipps already.

**Comment by ikalash** [comment]
Great!

**Comment by mperego** [comment]
@ikalash PR https://github.com/trilinos/Trilinos/pull/6645 fixed the issue on my Workstation. Not sure why we still see the error on the cee-compute12. What are the modules loaded there?

**Comment by mperego** [comment]
Actually, this seems to be related to sqrt, just looking at the seg-faul error. I remember there was an issue with sqrt(0), with FadType. Has that been addressed? , Why this error occur only with CLANG?

**Comment by ikalash** [comment]
> I remember there was an issue with sqrt(0), with FadType. Has that been addressed?

I think this is a question for @etphipp .  


> Why does this error occur only with CLANG?

A lot of these issues show up only with clang somehow.  It looks like your fix fixed it in the intel CEE build, just not the clang one.  

One way to avoid the issue w/ sqrt(0) is to have logic to only take the square root for a value > 0, and to return 0 otherwise.  I can put this in if you point me to the line in the code where we have the issue with sqrt(0).

**Comment by mperego** [comment]
Yeah.. I guess we need to put that login in Albany.. after all the derivative in 0 in Infinite.. so not sure Sacado can do anything about it.

I don't know what is the offensive line. I would need to build it on my Workstation. Can you run that test on the cee machine with gdb and see what is the offensive line? Then I can look at the code and try to understand what happens.

**Comment by ikalash** [comment]
So I guess we're not sure it's sqrt(0) that is the culprit then?  Yes, I can run gdb, but let me just look through the code first.  What would be the relevant evaluators to consider (I'm guessing its the temp equation evaluators)?

**Comment by mperego** [comment]
There are many instances of sqrt, and I would like to make sure that it makes sense that we have sqrt(0), assuming this is in fact what's triggering the error. Anyway, yes, any of the entalphy related evaluators could be triggering this.

**Comment by ikalash** [comment]
Ok I'll run through gdb and report back.  It may not be until tomorrow, but stay tuned!

**Comment by mperego** [comment]
Thanks!

**Comment by etphipp** [comment]
There is no reasonable way for Sacado to define the derivative of sqrt(x) for x == 0.  Any definition I gave it would undoubtedly be incorrect for someone's application.  I think it is best to leave it as generating an FPE, which at least gives you the opportunity to find it.  A common solution is to set the result to 0 if x == 0.

**Comment by mperego** [comment]
@ikalash commit e1d29fb4128166e79bb6e91503b468b13582f576 could fix the issue. So hold on until tomorrow before run the code through gdb.

**Comment by ikalash** [comment]
Ok, sure, sounds good.

**Comment by mperego** [comment]
It seems the tests failing have been fixed. Closing the issue

**Comment by ikalash** [comment]
Great, thanks @mperego !
