### ISSUE TITLE
Scope out and create (if not too hard) nightly spack build of Albany

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#553]
Will require creating and merging a fork of spack from github.com/ikalash to github.com/SNLComputation.

**Comment by ikalash** [comment]
I looked at this a bit today, including creating a version of spack that works for Albany in the SNLComputation git space, and verifying that it works (on my Fedora workstation camobap as well as the cori NERSC supercomputer).  On platforms behind firewalls, some care needs to be taken to deal with the proxies/SSL certificates.  I added to the documentation here on how to do this: https://github.com/SNLComputation/Albany/wiki/Building-Albany-using-SPACK .  

I think it would be pretty easy to create a spack nightly build to keep the spack build alive, so to speak.  What would be nontrivial would be posting the results of that build to CDash, which I'm not sure how to do with the spack build system (@gahansen , perhaps you have thoughts on this given your experience with both spack and CDash?).  I would propose given limited time/resources, to just create a nightly build on a selected platform that builds using spack / runs tests but does not post to CDash.  The build would send emails like the original Albany nightlies to notify interested parties about whether anything went wrong.  I would say we (I) do not have the time/resources to figure out how to post this to CDash right now, nor do we know if there is enough interest in the spack build overall to justify using resources to set this up.

**Comment by ikalash** [comment]
I set up some nightly spack builds earlier in the week on my 2 linux workstations.  @mperego: is there any interest in having a spack build somewhere like cori (I'm thinking for Matt, Steve, et al.)?  If they just use our executables there, maybe this is not needed.

**Comment by mperego** [comment]
@ikalash Thanks. Probably it's not needed at the moment, but I'll keep in mind that we have that option!

**Comment by ikalash** [comment]
Thanks @mperego , I figured.
