### ISSUE TITLE
Slowdowns in all tests on Mayer

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#556]
Looks like the Albany tests all got much slower a couple days ago on Mayer (an ARM machine) - see attached plot for example for total run time of one of the LandIce GIS problems (https://my.cdash.org/testDetails.php?test=54096128&build=1770920).

![timings](https://user-images.githubusercontent.com/7018124/74072436-abe75d00-49bb-11ea-860f-7bf2bde5c8db.png)

Could it be due to some of the Kokkos changes discussed yesterday?  Tagging @jewatkins , @bartgol , @ndellingwood .  

This was caught due to several of the longer tests (Aeras) starting to time out, but it looks like all tests are affected across the board.  I spot checked some of our tests on other platforms and am not seeing the same slowdown there.

**Comment by jewatkins** [comment]
It looks like the kokkos configuration options changed so that's probably what's affecting performance (probably on all archs too). Let me see if I can change all the config files.

**Comment by ikalash** [comment]
Thanks Jerry!  I thought it might be some issue like this.  We can see tomorrow if your changes had an impact.

**Comment by ikalash** [comment]
Seems the changes by @jewatkins did not fix the problem.  Per the discussion at the Albany meeting today, the next steps I think are as follows: 

1.) Look at Trilinos config settings before/after the slowdown started (@jewatkins )
2.) Build Trilinos from before slowdown started and run it to check if slowdown is due to environment change on mayer (likely it is not)
3.) Build Trilinos with some tests on, and check if Trilinos tests slowed down too (I suspect they did and the problem is within Trilinos).  If so, open a Trilinos issue to pass this off to the Trilinos team to investigate.

**Comment by jewatkins** [comment]
FYI, still haven't gotten around to this yet

**Comment by ikalash** [comment]
I'm pretty sure the problem is that I am running the tests on the head node.  I should have a fix soon.

**Comment by jewatkins** [comment]
Okay great thanks

**Comment by ikalash** [comment]
My theory was correct.  Issue has been resolved by switching to compute node for running tests.  This should have been done awhile ago but I never got around to it...

Attached is a picture showing that the test times have gone back down.

![Screenshot_2020-02-20 CDash Albany](https://user-images.githubusercontent.com/7018124/74952552-44ff7600-53b5-11ea-9a6a-bab6f228aa2b.png)
