### ISSUE TITLE
How to see which elements are on which processors?

### ISSUE THREAD

**Issue by JustinClough** [SNLComputation/Albany#562]
Is it possible to see which elements or degrees of freedom were handled by which mpi ranks after a parallel solve in Albany? Possibly just an element coloring in paraview?

If it matters, I'm using gmsh 4.1 meshes which are built into the STK reader and then writing the results as exodus files.

**Comment by bartgol** [comment]
The stk mesh should save a `GlobalNodeId` field, as well as a `GlobalElementId`. With N ranks, if you open only the `mesh.exo.N.0` file, you can see the ids of the entities processed by rank 0, and so on.

**Comment by bartgol** [comment]
[](
![stk_id](https://user-images.githubusercontent.com/3226046/74861880-4cb51100-5308-11ea-9e0e-60ff5211af68.png)
)

**Comment by bartgol** [comment]
![stk_id](https://user-images.githubusercontent.com/3226046/74862349-39ef0c00-5309-11ea-9ba3-c097e56c1e54.png)

**Comment by bartgol** [comment]
Uhm, I can't get paraview to open a _single_ exodus file (it always displays the whole mesh), maybe I'm doing something wrong. Anyhow, stk meshes should also export a `proc_rank` field. Unfortunately, it's marked as a `MESH` field, rather than `TRANSIENT`, which I _think_ prevents the field from being displayed in paraview. You can try and hack the `OrdinarySTKFieldContainer` (or the Multi one) to mark the `proc_rank_field` in the output mesh with a `TRANSIENT` role. Perhaps that will write the field to mesh, so that paraview can read it.

Once you have the proc_rank and the global_id fields, even if you can't open the exo output files individually, you can still see what dof belonged to what rank.

**Comment by ikalash** [comment]
I typically display the decomposed files in CUBIT.  I could never figure out how to do it in Paraview.  In CUBIT, you go to File -> Import, I believe, and import your *.g or *.exo (or other) files.  If there is a set of decomposed ones, they will show in different colors by proc.

**Comment by JustinClough** [comment]
Okay, I got the element and node id numbers to show in Paraview like in Luca's picture.

After some playing around, I found the way to open only the N'th part in paraview; you have to either move it (the rank's result file) to its own directory or change the file name. It looks like paraview will always open all `results.exo.N.*` files even if you only specify one of them so long as they share the same file name. 

So,
```
paraview results.exo.N
paraview results.exo.N.* 
```
are equivalent. 

I still haven't figured out coloring by part in one paraview session but I can get N paraview sessions to look at N parts. I think this might be more of a Paraview question than an Albany one. I'll go ahead and close the issue. I'll come back to it if I ever figure out how to color.

**Comment by ikalash** [comment]
Do you have CUBIT, Justin?  You should be able to do what you want in CUBIT.  If this is just for a visualization to put in a talk/paper, I can send you the picture from CUBIT if you send me the *.exo files.

**Comment by JustinClough** [comment]
I don't have CUBIT; I have looked at installing it but I'm not eligible to get a license. 

I originally asked just out of curiosity. I would like (eventually) to show the partition of some mesh in a talk or paper; I'll take you up on the offer then! Thanks for offering!

**Comment by ikalash** [comment]
Oh, right, seems you can only download it if you're at Sandia or a related project: https://cubit.sandia.gov/downloads.html . That's annoying. Feel free to ping me when you need the picture. It would look something like this:

![gis_partition](https://user-images.githubusercontent.com/7018124/74952746-8c860200-53b5-11ea-87df-6e81c1d0f87f.jpg)

(I originally commented on the wrong issue...  sigh...)
