### ISSUE TITLE
TDM: failures in Clang build on CEE

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#566]
It looks like the new TDM tests fail on CEE with a Clang compiler due to NaNs getting into Belos:

```

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start of Continuation Step 0 : Attempting to converge initial guess at initial parameter values.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Warning: NOX::Solver::LineSearchBased::init() - The solution passed into the solver (either through constructor or reset method) is already converged!  The solver wil not attempt to solve this system since status is flagged as converged.

************************************************************************
-- Nonlinear Solver Step 0 -- 
||F|| = 6.075e-16  step = 0.000e+00  dx = 0.000e+00 (Converged!)
************************************************************************

************************************************************************
-- Final Status Test Results --
Converged....OR Combination -> 
  Converged....F-Norm = 1.246e-17 < 5.000e-06
               (Length-Scaled Two-Norm, Absolute Tolerance)
  **...........Number of Iterations = 0 < 20
************************************************************************

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
End of Continuation Step 0 : Parameter: Time = 0.000e+00
--> Step Converged in 0 Nonlinear Solver Iterations!
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

copying nodal Solution to nodal temp_old
APFDiscretization::writeSolution: writing time 0 to index 0 in file ./Bare_plate.vtk

	Calling Predictor with method: Constant

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start of Continuation Step 1 : Parameter: Time = 5.000e+00 from 0.000e+00
Continuation Method: Natural
Current step size  = 5.000e+00   Previous step size = 0.000e+00
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


************************************************************************
-- Nonlinear Solver Step 0 -- 
||F|| =      -nan  step = 0.000e+00  dx = 0.000e+00
************************************************************************


p=0: *** Caught standard std::exception of type 'Thyra::CatastrophicSolveFailure' :

 /projects/albany/nightlyAlbanyCDash/repos/Trilinos/packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolve_def.hpp:662:
 
 Throw number = 3
 
 Throw test that evaluated to true: true
 
 /projects/albany/nightlyAlbanyCDash/test/TrilinosInstallC11/include/BelosStatusTestGenResNorm.hpp:578:
 
 Throw number = 2
 
 Throw test that evaluated to true: true
 ```
http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=93465 

This is similar to #558, and I think it has to do with uninitialized fields being set to NaNs.  I'm somewhat stumped by this issue in general.  It's bizarre to me in particular that it does not happen in the debug build (which is where it should up, according to the discussion in #558).  @bartgol , do you have any insight into the issue based on looking at it before?

Since CEE + Clang is not a targeted platform for TDM, we may want to punt on this...  I think no one has time to debug this right now, and I'm not sure @RuixiongHu has a machine on which he can reproduce the problem.  In this case, I'm inclined to just disable TDM on the problematic build.

**Comment by RuixiongHu** [comment]
Hello, I've never seen similar issues on Linux machines I used previously.
My macbook do use Clang but I don't know if that CEE is a Sandia specific
tool, I could build it on my mac and reproduce the problem, if you think
this is doable.

What's more, someday I'm going to build it on a Power9 machine which is
similar to Summit, and if this is a related issue then I guess I would have
to fix it anyway. Please let me know. Thanks a lot.

**Comment by ikalash** [comment]
Thanks for offering to look at it @RuixiongHu .  Let me spend a little bit of time looking at it myself first.  Seems this issue crops up sporadically as a Heisen-bug in some other tests on certain platforms, e.g. mayer: https://my.cdash.org/testDetails.php?test=54825944&build=1781775. 
 Hopefully in the next couple of days... stay tuned!

**Comment by ikalash** [comment]
@RuixiongHu : I just fixed this.  The issue was you had a duplicate uninitialized local variable, initial_porosity, that conflicted with the member variable porosity.  With clang, the initialized variables seem to be set to nan.  

I have a feature request for TDM.  I noticed you are using tabs in the source code for each line.  Can you please use spaces instead?  Each for loop should have two spaces, e.g. 
```
int a = 0.0; 
for (stuff) {
  for (stuff) {
    for(stuff) {
      stuff 
    } 
 }
}
```
If you could reformat the files to look like this to be consistent with the rest of Albany, that would be great.
