### ISSUE TITLE
Migrate Albany to new sems-supported CDash site

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#568]
Also change format of tests such that they are compatible with scripts written by Ross Bartlett for easy summary of passes/fails/diffs, etc. (single email summarizes entire dashboard compared to dozens of emails).

**Comment by ikalash** [comment]
After almost 6 months, the site finally has been set up and I am able to push to it from SRN machines (some work is required for SON machines)!  Here is the site: https://sems-cdash-son.sandia.gov/cdash/index.php?project=Albany .  I will gradually migrate all the nightlies from our SRN site ( http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany ) and ultimately SON site (https://my.cdash.org/viewSubProjects.php?project=Albany) here, with the exception of the Cori build.  External machines cannot push to this site unfortunately, despite it being on the SON.  I will also work on replacing the current numerous emails with a single one using Ross's scripts.

**Comment by lxmota** [comment]
@ikalash Do we need to just point to the new CDash URL, or is there anything else that we need to do to use the new dashboard?

**Comment by ikalash** [comment]
@lxmota : good question.  The scripts will have to be modified for the new CDash.  One of the things that will need to change is to eliminate the use of subprojects.  The way we are using it currently is wrong apparently (according to Ross) and I actually agree with this.  It doesn't make sense for each build to be its own subproject.  Anyway, I don't intend to take down the old site or anything so feel free to keep using it.  I'm happy to help you transition your nightlies to the new site if you'd like.  It shouldn't be very hard now that we got all the proxy stuff resolved that was causing difficulties for awhile.

**Comment by lxmota** [comment]
@ikalash Ok, that sounds good. I don't want to pile on more work on you, so when you have an example that does no use subprojects, I can give it a try. All that needs to be changed is in the Albany/doc/LCM/build/*.cmake files.

**Comment by ikalash** [comment]
@lxmota OK sounds good.  I will be modifying similar scripts in the LCM_and_LandIce directory in the master branch for the skybridge nightly.  The changes should be pretty much the same for your builds.

**Comment by ikalash** [comment]
@lxmota: I've switched over the skybridge build to push to the new CDash.  To change the proxima/algol builds, the same changes done here need to happen in the LCM directory: https://github.com/SNLComputation/Albany/commit/54a8e98fe93bb9e6f51a84b5b24c74ff55f498a8 .  Are you OK with me making the changes?  It should not take me very long since I know what they are, having just done this for skybridge.

**Comment by lxmota** [comment]
Hi Irina,

Yes, that would be totally fine. Thanks for doing this!

Alejandro

Sent from my iPhone

On Mar 22, 2020, at 11:37, Irina K. Tezaur <notifications@github.com> wrote:

﻿

@lxmota<https://github.com/lxmota>: I've switched over the skybridge build to push to the new CDash. To change the proxima/algol builds, the same changes done here need to happen in the LCM directory: 54a8e98<https://github.com/SNLComputation/Albany/commit/54a8e98fe93bb9e6f51a84b5b24c74ff55f498a8> . Are you OK with me making the changes? It should not take me very long since I know what they are, having just done this for skybridge.

**Comment by ikalash** [comment]
Sure!  I've made the changes and will push them tomorrow.  I'd like to check that the existing builds post correctly before I push new ones.

**Comment by ikalash** [comment]
@lxmota : I just made the chance (in your fork).  I will check tomorrow that things are posting correctly to the new site.

**Comment by ikalash** [comment]
All the nightlies have been moved to the new CDash site https://sems-cdash-son.sandia.gov/cdash/index.php?project=Albany, including Cori.
