### ISSUE TITLE
Implement prototype block discretization class and tests

### ISSUE THREAD

**Issue by gahansen** [SNLComputation/Albany#585]
I am starting to implement a prototype block discretization class in Albany. I am following the path suggested in the wiki:

https://github.com/SNLComputation/Albany/wiki/Blocked-linear-system

specifically the first bullet under the 11/14/18 Updates section. I plan to also leverage some of the points, ideas, and discussion from issues #357, #16, #83, #327, and #198.

I am starting this issue to give us a single spot to discuss this, and to keep the team up to date on progress, and to solicit help on decisions that need to be made.

**Comment by bartgol** [comment]
@gahansen I am quite confident #584 will go in soon. Could you wait to branch off master, so you can benefit from that mini-refactor too?

**Comment by gahansen** [comment]
Will do Luca! Thanks for the heads up.

**Comment by gahansen** [comment]
@bartgol @ikalash @mperego - What should we do with block discretization dependencies and the feature build? I am working on adding the Panzer DOF manager - this will create a required dependency on panzer for this feature. Should I add a build option that defaults to OFF to hide this dependency and the block capability itself in the build as to not disrupt others that do not care about it? Or should Panzer become a required Albany dependency? I suspect the block capability will become pretty intusive over time so it may not make sense for this to be an optional feature in the code.

**Comment by bartgol** [comment]
I was thinking that once the block discretization would be well oiled, we would switch to that altogether, with the DofManager from Panzer being our main way of numbering dofs and handling connectivity.

So, to answer your question, I would make it a required dependency. The DofManager pkg in panzer is not a big one, after all. If one can handle MueLu building, then building DofManager should be a no-op. Especially if you use ninja as a generator, you may even not increase your build time at all (due to compilation scheduling).

**Comment by gahansen** [comment]
I am thinking the same on this Luca. There is very little overhead added and propagating the DOF manager and the interface everywhere will let us simplify things (and make the code more robust) over time. I'll do this of no one has objections or concerns.

**Comment by mperego** [comment]
Hi Geln. Thanks for working on that. I'm fine with having Panzer Dof Manager as a require dependency.  Before you merge this change make sure to let us , and in particular Irina, know so that we can modify all the trilinos installs for the nightly builds. Also, we should be able to detect if the Panzer Dof manager is not present when we configure Albany.

**Comment by gahansen** [comment]
I have the detection logic already in my local work version. Irina, perhaps we should add the option " -DTrilinos_ENABLE_Panzer:BOOL=ON" to the nightlies now in prep for my next push and make sure there are no issues with that step before I do the push later?

**Comment by mperego** [comment]
Thanks @gahansen! When do you plan to have this merged? Irina is on vacation, and also we have a couple of PRs, with significant infrastructure changes, being merged in these days.

**Comment by ikalash** [comment]
Yes, I can add the new enable in the nightlies.  I'm on vacation this week but can do it this evening perhaps.  I will comment here once I've had a chance to do so.

**Comment by gahansen** [comment]
It will be a little while still. probably a couple more weeks. I will wait until the PRs go in and that all stabilizes before I push. My next push will probably only be discretization stuff so it should not have much impact elsewhere.

**Comment by mperego** [comment]
OK, perfect! Thanks.

**Comment by ikalash** [comment]
I see.  I'll do it sooner rather than later so as not to forget.  It should not hurt anything to have Panzer on in Trilinos, right?  Or will it increase the build times substantially?

**Comment by gahansen** [comment]
It built very quickly for me - I did not notice any issues or differences. No hurry though Irina - please enjoy your time away!

**Comment by mperego** [comment]
You shoun't  have to build all Panzer. Only the Dof Manager, and it builds very quickly:
`-D Trilinos_ENABLE_PanzerDofMgr:BOOL=ON \`

@gahansen can you check if this is enough? If you use only the Dof manager it should.

**Comment by gahansen** [comment]
I'm not quite at the point of making sure that this is enough. I guess we should wait until right before I push and then I can try to build with just that option and see if it works.

**Comment by mperego** [comment]
sounds good. So @ikalash don't modify the nightly builds for now. It would be great if we only relied on the DOF Manager.

**Comment by ikalash** [comment]
I am getting errors when I try to build this branch.  Here is how they look like: 

```
[ 66%] Building CXX object src/LandIce/CMakeFiles/LandIce.dir/evaluators/LandIce_Dissipation.cpp.o
/nightlyCDash/repos/Albany/tests/unit/disc/BlockedDOFManagerUnitTester.cpp: In member function ‘virtual void Albany::tBlockedDOFManager_SimpleTests_assortedTests_UnitTest::runUnitTestImpl(Teuchos::FancyOStream&, bool&) const’:
/nightlyCDash/repos/Albany/tests/unit/disc/BlockedDOFManagerUnitTester.cpp:130:58: error: expected type-specifier before ‘Epetra_MpiComm’
  130 |       Teuchos::RCP<Epetra_Comm> eComm = Teuchos::rcp(new Epetra_MpiComm(MPI_COMM_WORLD));
      |                                                          ^~~~~~~~~~~~~~
/nightlyCDash/repos/Albany/tests/unit/disc/BlockedDOFManagerUnitTester.cpp:144:8: error: ‘ConnManager’ was not declared in this scope
  144 |    RCP<ConnManager> connManager = rcp(new unit_test::ConnManager(myRank,numProc));
      |        ^~~~~~~~~~~
/nightlyCDash/repos/Albany/tests/unit/disc/BlockedDOFManagerUnitTester.cpp:144:8: note: suggested alternatives:
In file included from /nightlyAlbanyTests/Results/Trilinos/build/install/include/Panzer_BlockedDOFManager.hpp:56,
                 from /nightlyCDash/repos/Albany/tests/unit/disc/BlockedDOFManagerUnitTester.cpp:17:
/nightlyAlbanyTests/Results/Trilinos/build/install/include/Panzer_ConnManager.hpp:58:9: note:   ‘panzer::ConnManager’
   58 |   class ConnManager {
      |         ^~~~~~~~~~~
In file included from /nightlyCDash/repos/Albany/tests/unit/disc/BlockedDOFManagerUnitTester.cpp:21:
/nightlyCDash/repos/Albany/tests/unit/disc/UnitTest_ConnManager.hpp:86:7: note:   ‘Albany::unit_test::ConnManager’
   86 | class ConnManager : public virtual panzer::ConnManager {
      |       ^~~~~~~~~~~
/nightlyCDash/repos/Albany/tests/unit/disc/BlockedDOFManagerUnitTester.cpp:144:19: error: template argument 1 is invalid
  144 |    RCP<ConnManager> connManager = rcp(new unit_test::ConnManager(myRank,numProc));
      |                   ^
/nightlyCDash/repos/Albany/tests/unit/disc/BlockedDOFManagerUnitTester.cpp:144:38: error: cannot convert ‘Teuchos::RCP<Albany::unit_test::ConnManager>’ to ‘int’ in initialization
  144 |    RCP<ConnManager> connManager = rcp(new unit_test::ConnManager(myRank,numProc));
      |                                   ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      |
      |                                      Teuchos::RCP<Albany::unit_test::ConnManager>
/nightlyCDash/repos/Albany/tests/unit/disc/BlockedDOFManagerUnitTester.cpp:145:4: error: ‘BlockedDOFManager’ was not declared in this scope; did you mean ‘panzer::BlockedDOFManager’?
  145 |    BlockedDOFManager dofManager;
      |    ^~~~~~~~~~~~~~~~~
      |    panzer::BlockedDOFManager
In file included from /nightlyCDash/repos/Albany/tests/unit/disc/BlockedDOFManagerUnitTester.cpp:17:
/nightlyAlbanyTests/Results/Trilinos/build/install/include/Panzer_BlockedDOFManager.hpp:69:7: note: ‘panzer::BlockedDOFManager’ declared here
   69 | class BlockedDOFManager : public GlobalIndexer {
      |       ^~~~~~~~~~~~~~~~~
/nightlyCDash/repos/Albany/tests/unit/disc/BlockedDOFManagerUnitTester.cpp:146:4: error: ‘dofManager’ was not declared in this scope; did you mean ‘connManager’?
  146 |    dofManager.setUseDOFManagerFEI(false);
      |    ^~~~~~~~~~
      |    connManager
```
I added `` -D Trilinos_ENABLE_PanzerDofMgr:BOOL=ON \`` to my Trilinos configuration.  Perhaps something else needs to be added?

**Comment by gahansen** [comment]
Sorry Irina, I was working on the next step in the tester right before I pushed this and I forgot to flip back an #if to false. I'll finish this thought up and force push the next increment and let you know.

**Comment by ikalash** [comment]
@gahansen : ok no problem.  Just let me know when for me to test.

**Comment by bartgol** [comment]
Closing, since the prototype has been implemented.
