### ISSUE TITLE
Switch to FE Crs matrices

### ISSUE THREAD

**Issue by bartgol** [SNLComputation/Albany#586]
Now that the FE Crs matrix in Tpetra is relatively reliable, it's worth it for us to switch to that, and save quite a bit of storage. I think we should also switch MultiVector to FEMultiVector too, for the same reason.

This issue is for tracking purposes. I'm starting to work on it today.

**Comment by bartgol** [comment]
Some updates:

- FE vectors might prove more complicated than the FE matrices, due to the fact that they are usually created within Thyra framework (the VectorSpace createMember(s) methods). FE Vectors require an import/export input, and that's only available when both owned and owned+shared maps are available.

- FE matrices are not so easy either, due to the thyra layer mechanism. In particular, the tpetra adapters store the range/domain of the operator once and for all at init time, which means that when we switch between owned and owned+shared phases, the thyra vector spaces are *not* updated (we need to do it by hand, which is a bit cumbersome, and might have some runtime cost, though I believe that's unavoidable).

- Even with 1 rank, things are not yet working correctly in the Tpetra build (they work with Epetra). In particular, DBCs seem to not get applied. I am trying to figure out why.

- I have not yet started to investigate errors in parallel (with Epetra (the only one 'running' in parallel) the residual grows with each Newton iteration).

**Comment by bartgol** [comment]
Update: right after commenting, I realized that the jacobian wasn't open for filling when DBCs were applied, which caused all the calls to `replaceLocalValues` to have no effect. Unfortunately, we did not raise any error (Tpetra returned an error code which we ignored), so it went under the radar. This will be fixed.

**Comment by bartgol** [comment]
Update:

I think Tpetra's FECrsGraph (and maybe also Epetra's, I haven't checked) needs the owned gids to come first in the overlapped map. That's not necessarily the case given how we build the vector spaces. This is "easy" to fix, we just have to reorder the gids when we create the maps in the discretization.

**Comment by bartgol** [comment]
Update: there are a few things in the FE structures in both Epetra and Tpetra that may end up in bugs. I opened an issue on both packages, and see if they can fix it (fixes are quick, I could even do it myself).

That said, even with the fixes added, I get wrong results in parallel, for both Epetra and Tpetra. I am switching to a manual inspection of the Jacobian on a 1x1 grid problem, to see the difference between a serial and parallel jacobian (if any).

**Comment by mperego** [comment]
I'm sorry this is turning out to be a pain.

**Comment by bartgol** [comment]
Well, as long as it pays out... ;)

**Comment by bartgol** [comment]
I am a bit stuck. I get the same Jacobian in serial and parallel (I printed it), but the iterations are insanely different. I converge to 1e-15 in 5 iterations in serial, while in parallel I'm still at 1e-3 after 10 iterations.

I'm using MueLu with 1 level, with KLU2 on coarse (so basically a direct solver). The muelu output is also the same (setup and stuff). After 1 NOX iteration:

serial:
```
************************************************************************
-- Nonlinear Solver Step 1 -- 
||F|| = 1.253e+00  step = 1.000e+00  dx = 2.261e+00
************************************************************************
```

parallel (`-np 2`):
```
************************************************************************
-- Nonlinear Solver Step 1 -- 
||F|| = 1.606e+00  step = 1.000e+00  dx = 2.261e+00
************************************************************************
```

Any clue what could be wrong?

**Comment by mperego** [comment]
@bartgol wild guess.. Did you check that the maps of the matrix are compatible with the right hand side one?

**Comment by bartgol** [comment]
I haven't, but it's worth a shot.

**Comment by bartgol** [comment]
Update: Most of the work is done. All basic tests pass. There's one DEMO PDE test that fails (NSVortexShedding2D_Steady_Blocked), and plenty of LandIce tests failing (all MMS for GLF and SMB, all ISMIP and FO_Test, and roughly half of the FO_GIS ones).

**Comment by mperego** [comment]
@bartgol Any luck with that? I cannot really see why those tests would fail.. or whether those tests share a common pattern.

**Comment by bartgol** [comment]
I worked on the NSVortexShedding2D test so far. I found a bug, but the jacobian is still singular in that test. I think I will move to LandIce tests now, though, as some of them are smaller and easier to debug. Hopefully fixing those will also fix the NS one.

**Comment by bartgol** [comment]
@mperego 

So, I'm down to 3 tests failing: NSVortexShedding2D and FO_GIS_CoupledThickness (Tpetra and Epetra). For the former, I still don't know what the deal is. For the latter, I do know it, and it is complicated.

In order to use Tpetra's FECrsGraph/Matrix, the overlap map _must_ contain the owned map "at the beginning" (locally fitted, in Tpetra lingo). That means that if process N owns gids 12, 34, 19, 32, then the first GIDs in its overlap map _must_ be 12, 34, 19, 32 (in that same order).

This means that the local id of nodes in the overlapped map may not respect the layered mesh ordering anymore. In particular, if the ordering is layered, we would like all the nodes on level 0 to come before all nodes on level 1, but this is not true, since the 'ghosted' nodes on level 0 cannot come before the owned nodes on level 2.

The good news is that I think in all the places in PHAL were we used a LayeredMeshOrdering<LO>, we could probably use a LayeredMeshOrdering<GO>, since we care about the GID of the node. In this case, LayeredMeshOrdering is _very similar_ to NodalDOFManager (node*stride+comp vs node+comp*stride), and it still works (it's only computing GIDs, not local positions).

I am working on trying to fix this also in LandIce, but things are a bit more complicated. For instance, I'm a bit lost trying to figure out what happens in FluxDivergenceResidual, with `lNodesILP1` and `nodesP1_tmp` and whatnot.

@mperego , do you think you could help me? I might push the branch now, so you can check it out. I left the old mesh numbering structure there, but ideally you should only use `getLayeredMeshGlobalNumbering()` from disc, which returns a LayeredMeshOrdering<GO> object.

**Comment by mperego** [comment]
Good that you are down to only 3 tests failing.

I'm not sure I understand. I thought that the local ordering was set in the extruded mesh, when you create the node map. 
Also, you would have more tests failing if there was an issue with the (local) LayeredMeshOrdering. FluxDivergenceResidual is only used in a FO_Thermo test, not in the FO_GIS_CoupledThickness one.

Are you working today? If so I can give you a call.

**Comment by bartgol** [comment]
Hi Mauro, as you probably figured out, no I wasn't working. =)

Jokes aside, you raise a good point about other tests that should fail if the LMO was the issue. However, I think LMO is an issue, and should be changed. And it might be that for some cases, it still gives the correct result. For instance, with column ordering, the stride is numLayers, which is correct. If one only wants to retrieve the layer of the node, it would  get the correct result. Notice, in fact, that even if the new implementation reorder nodes so that owned nodes come first in the overlapped map, the dofs in a column are still contiguous (with column ordering), so some logic is sitll intact.

Anyhow, maybe I can give you a call later if you're available.

**Comment by mperego** [comment]
yeah, let's chat over the phone
