### ISSUE TITLE
Bad merge in Application::computeGlobalJacobianImpl()

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#589]
I can't really track down what happened but it looks like a bad merge to me:
https://github.com/SNLComputation/Albany/blob/0327f52dc2215e517fafddf0ec634c4ee193f1ca/src/Albany_Application.cpp#L1600
It looks like some code spilled over to Albany namespace and it's been there for a while. Also because the namespace closes, there's a hanging bracket at the end of the file (not sure how that compiles). @ikalash I think it's safe to just pack this code back into the method but just wanted to confirm.

**Comment by mperego** [comment]
@jewatkins I think we need to remove this `}`
https://github.com/SNLComputation/Albany/blob/master/src/Albany_Application.cpp#L1589
(and fix indentation)

**Comment by jewatkins** [comment]
Ah okay that makes me feel better. I'll go ahead and fix that.
