### ISSUE TITLE
Failing LandIce Enthalpy Humboldt tests

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#604]
There are 2 tests failing in the nightlies: Enthalpy_Humbodt and FO_Thermo_Humboldt_fluxDiv (sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3393 ).  Or has this been resolved already in some of the discussion by email this morning?  Tagging @mperego.

**Comment by ikalash** [comment]
Looks like the issue is trying to run the tests w/ the FROSch but FROSch is off.  Ifdef guards need to be added.

**Comment by mperego** [comment]
@ikalash It should be fixes now.

**Comment by ikalash** [comment]
Thanks @mperego .  I believe you so I will close the issue.
