### ISSUE TITLE
Link error related to BlockDiscretization

### ISSUE THREAD

**Issue by bartgol** [SNLComputation/Albany#605]
Is anybody else seeing this?

```
libalbanyLib.so: undefined reference to `Albany::BlockedDiscretization::writeSolutionMVToFile(Thyra::MultiVectorBase<double> const&, double, bool)'
collect2: error: ld returned 1 exit status
```

Obviously, I can fix the problem, but I was wondering why this hasn't showed up in the nightlies yet.

**Comment by ikalash** [comment]
No, nightlies last night were clean: https://sems-cdash-son.sandia.gov/cdash/index.php?project=Albany .  I will check again tomorrow.

**Comment by bartgol** [comment]
I mean, the error _should_ be there, cause there's no definition of some methods.

Are all our nightlies with clang/intel on CPU? Maybe it's gcc that is picking it up...

**Comment by ikalash** [comment]
Oh, I see.  It hasn't shown up.  There are many gcc builds - most of them are gcc builds actually.  No CUDA build now as waterman is down / weaver is not yet fully operational.

**Comment by bartgol** [comment]
Ah, I was only displaying the first 10 items. :D

**Comment by jewatkins** [comment]
Showing up now: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=3456

@gahansen it might be related to your push

**Comment by ikalash** [comment]
A bunch of the nightlies are indeed broken as a result of this issue: https://sems-cdash-son.sandia.gov/cdash/index.php?project=Albany .

**Comment by gahansen** [comment]
It was me. I'll fix the issue and commit the repair.

**Comment by ikalash** [comment]
Thanks Glen!

**Comment by gahansen** [comment]
I wanted to add a link flag to my test builds to catch issues like this. I added "-Wl,--no-undefined -Wl,--no-allow-shlib-undefined" to the build, which (on my reading of the ld man page) should give a link error if an undefined symbol is present. However, this does not work in my build - I link and run successfully.

Does anyone know how to force ld to catch undefined externals in all cases?

**Comment by bartgol** [comment]
I'm not sure. I do get the link error, and this is my link line (stripped of all trilinos and its tpl libs otherwise it'd be too long to parse):

```
Linking CXX executable Albany
cd /home/luca/workdir/albany/albany-build/gcc/debug/master/src && /home/luca/workdir/utils/cmake/cmake-install/bin/cmake -E cmake_link_script CMakeFiles/Albany.dir/link.txt --verbose=ON
/home/luca/workdir/compilers/openmpi/openmpi-install/bin/mpicxx  -Wno-terminate -Wno-literal-suffix -Wno-deprecated   -g -O0  -g  -rdynamic CMakeFiles/Albany.dir/Main_Solve.cpp.o  -o Albany  -L/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop-serial/lib -Wl,-rpath,/home/luca/workdir/trilinos/trilinos-install/marzemino/gcc/debug/develop-serial/lib:/home/luca/workdir/albany/albany-build/gcc/debug/master/src:/home/luca/workdir/libs/netcdf/netcdf-c/netcdf-c-install/lib64:/home/luca/workdir/libs/parmetis/parmetis-4.0.3-install/gcc/lib:/home/luca/workdir/libs/lapack/lapack-3.8.0-install/lib64: libalbanyPDEs.so  /usr/lib64/libdl.so -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lgfortran -lm -lgcc_s -lgcc -lquadmath -lm -lgcc_s -lgcc -lpthread -lc -lgcc_s -lgcc libalbanyLib.so  -lquadmath -lpthread -lc -lm -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lgfortran -lquadmath 
```

You might try comparing it with yours and see if you find the flag that triggers it.

**Comment by gahansen** [comment]
Hi Luca - could you please post the output of what you see for:

/home/luca/workdir/compilers/openmpi/openmpi-install/bin/mpicxx -print-prog-name=ld

**Comment by bartgol** [comment]
It simply returns `ld`.

**Comment by gahansen** [comment]
Could you now please do "ld -V"?

It looks like the nightlies are passing so my commit appears to have fixed the error I introduced. I'll wait for Irina to confirm and close this issue if she agrees.

**Comment by bartgol** [comment]
```
GNU ld version 2.27-43.base.el7_8.1
  Supported emulations:
   elf_x86_64
   elf32_x86_64
   elf_i386
   elf_iamcu
   i386linux
   elf_l1om
   elf_k1om
```

I also tried the current master, and things are now ok.

**Comment by ikalash** [comment]
I think this has been resolved - it has in all my nightlies.  Therefore closing.  @bartgol if you are still experiencing issues, please feel free to reopen.
