### ISSUE TITLE
Failures in OpenMP build on camobap

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#608]
Over the weekend, most of the tests in the OpenMP build on my workstation camobap began failing.  Here is the error: 

```
[camobap.ca.sandia.gov:2629624] PMIX ERROR: NOT-FOUND in file dstore_base.c at line 2866
[camobap.ca.sandia.gov:2629624] PMIX ERROR: NOT-FOUND in file server/pmix_server.c at line 3408
[camobap.ca.sandia.gov:2629628] PMIX ERROR: OUT-OF-RESOURCE in file client/pmix_client.c at line 231
[camobap.ca.sandia.gov:2629628] OPAL ERROR: Error in file ext3x_client.c at line 112
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[camobap.ca.sandia.gov:2629628] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[35506,1],0]
  Exit code:    1
--------------------------------------------------------------------------
[camobap.ca.sandia.gov:2629624] PMIX ERROR: ERROR in file gds_ds21_lock_pthread.c at line 99
[camobap.ca.sandia.gov:2629624] PMIX ERROR: ERROR in file gds_ds21_lock_pthread.c at line 99
```
https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=281935&build=3605

Curiously, it doesn't happen in the blake OpenMP build.  It seems like a machine-specific thing, except I'm a bit stumped as to why this would start now, given that no changes have been made to camobap or its environment.  Does anyone have any ideas?  @bartgol , @jewatkins ?

**Comment by bartgol** [comment]
Sounds like a glitch in the MPI framework. I would give it another day to see if it happens again.

**Comment by jewatkins** [comment]
What version of openmpi is this? You could try `export PMIX_MCA_gds=hash`, that came up as a solution for this issue for version 4+

**Comment by ikalash** [comment]
@bartgol I don't think it's a glitch, been happening for a few days over the weekend. 

@jewatkins : I don't get the error when I add ``export PMIX_MCA_gds=hash" but it seems to hang.  I played around with some things and it seems passing mpiexec '--map-by core' is causing the problem - when I take this out, it goes away.  I think I will go ahead and take this option out for the OpenMP nightly on camobap.  I actually checked what we do in the OpenMP build on blake and we pass '--map-by ppr:1:core:pe=2'.  Is that a more correct option to pass to mpiexec?  I checked and it works just fine on camobap.  We are setting num omp threads = 2 on both machines..

**Comment by jewatkins** [comment]
yeah go ahead and use that if you're setting omp num threads to 2. that should bind those threads to the core. This should do the same if you're not setting these already: `export OMP_PLACES=threads; export OMP_PROC_BIND=spread`.

**Comment by bartgol** [comment]
Ah, I didn't read your message carefully. I thought it was just a one-time thing.

I think the solution you propose (the ppr one) sounds good. I always use `--bind-to core`, but I also always have `OMP_PLACES=threads` and `OMP_PROC_BIND=spread` in my envoronment. Maybe, without those, binding to  core with `OMP_NUM_THREADS=2` might cause issues?

Although, to be fair, the error is caused during MPI_Init (at least that's how it seems from the output), so OMP settings there should not yet be relevant. Unless some rank is already at the Kokkos::initialize stage, while some is still finishing up the MPI_Init call, and they might clash? Not really sure.

**Comment by jewatkins** [comment]
I think openmpi might have its own threaded code and that's why an issue like this might come up. Not sure though.
