### ISSUE TITLE
A couple new failing AIS performance tests

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#616]
Looks like we have a couple new failing performance tests on blake: 

https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=4250 

```
ant-2-20km_ml_ls_np384 
ant-2-20km_mu_dls_np384 
ant-2-20km_mu_ls_np384 
```
Could you please have a look @jewatkins ?

**Comment by jewatkins** [comment]
I hopefully fixed these this morning, we'll see tomorrow. Basically, I ran out of memory when I added the surface velocity mismatch response so I had to reduce the workset size.

**Comment by ikalash** [comment]
Ah ok great.  I will check tomorrow and close the issue if it is indeed resolved.
