### ISSUE TITLE
Build failure in CEE intel nightly

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#617]
The CEE intel nightly build failed with a cryptic error: 

```
/.../repos/Albany/src/Albany_RegressionTests.cpp(215) (col. 18): internal error: 04010026_1450
```

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=4333

I had to change one of the modules over the weekend to use intel-19.0.1 instead of intel-18.0.3, as the latter module went away, apparently.  @gahansen do you think this error could be due to the intel TPLs needing to be rebuilt with the new intel compiler?

**Comment by gahansen** [comment]
Yes, that would be my first thought also. It looks like the CEE folks dropped all the version 18 Intel compilers; we should rebuild those TPLs. I am hesitant to say that given the struggle that we had with gcc - but I'd be glad to give it a shot and document it like I did the others. We might also want to upgrade to the newer mkl while we are at it. I have done that everywhere I am working and it seems stable.

**Comment by ikalash** [comment]
Maybe this is a good time to try to switch the intel nightlies to use sems modules.  I will scope this out.

**Comment by gahansen** [comment]
I did some searching on that error and there have been a few others that have encountered it elsewhere. Is Trilinos testing with that version (19.1-2020.1.217)? We might want to try the previous compiler 19.0-2019.5.281 and see if we get a similar failure. It is still probably a good idea to rebuild those TPLs in any event.

**Comment by ikalash** [comment]
Oh, interesting.  I could switch to the other compiler to see what happens.  

I agree with what Mauro was saying earlier that maybe it's best to not build any TPLs and just try to use the sems modules if possible.  I think this may be a good time to scope that out.

**Comment by gahansen** [comment]
Yes - it is probably better to switch to sems if we can. I don't use the intel tools, so I don't have a personal/"other project" reason to keep them current like I did with clang and gcc.

**Comment by ikalash** [comment]
> I did some searching on that error and there have been a few others that have encountered it elsewhere. Is Trilinos testing with that version (19.1-2020.1.217)? We might want to try the previous compiler 19.0-2019.5.281 and see if we get a similar failure. It is still probably a good idea to rebuild those TPLs in any event.

So actually we are using 19.0 already -  module load sierra-devel/intel-19.0.1-intelmpi-5.1 is the module I am loading.  So I don't think switching the compiler will help.

**Comment by bartgol** [comment]
+1 on using sems modules anywhere they are available.

**Comment by ikalash** [comment]
Closing in favor of spin-up issue #619 .
