### ISSUE TITLE
Albany build error due to Hessian changes on skybridge

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#623]
Looks like the Skybridge build failed due to the Hessian stuff: 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=4704 

```
[  4%] Building CXX object src/CMakeFiles/albanyLib.dir/Albany_RegressionTests.cpp.o [  4%] Building CXX object src/CMakeFiles/albanyLib.dir/Albany_SolverFactory.cpp.o [  5%] Building CXX object src/CMakeFiles/albanyLib.dir/PHAL_Dimension.cpp.o [  5%] Building CXX object src/CMakeFiles/albanyLib.dir/Albany_Utils.cpp.o [  5%] Building CXX object src/CMakeFiles/albanyLib.dir/PHAL_Setup.cpp.o [  6%] Building CXX object src/CMakeFiles/albanyLib.dir/Albany_Application.cpp.o [  6%] Building CXX object src/CMakeFiles/albanyLib.dir/InitialCondition.cpp.o [  6%] Building CXX object src/CMakeFiles/albanyLib.dir/Albany_Memory.cpp.o [  7%] Building CXX object src/CMakeFiles/albanyLib.dir/Albany_ModelEvaluator.cpp.o [  7%] Building CXX object src/CMakeFiles/albanyLib.dir/Albany_NullSpaceUtils.cpp.o /.../Albany/src/Albany_ModelEvaluator.cpp(586): error: class "Thyra::ModelEvaluatorBase::OutArgsSetup<ST={RealType={double}}>" has no member "setHessianSupports"    result.setHessianSupports(true);            ^
--
```
@mperego , @kliegeois : could you please have a look?

**Comment by kliegeois** [comment]
Thanks for reporting the error.
Line 586 of src/Albany_ModelEvaluator.cpp should have been removed from my PR, sorry about that. Nevertheless, this compilation error is strange. Which version of Trilinos is used for this build?

**Comment by mperego** [comment]
@ikalash Any clue of why it started failing today?

**Comment by ikalash** [comment]
No, that is a mystery...  I noticed that I had to change the Trilinos required version in Albany's CMakeLists.txt from 12.13 to 13.1 - most of the nightlies failed b/c of the version mismatch.  I'm not sure why the skybridge one did not, but perhaps this is somehow related to that version number?  Not sure....

This is Trilinos develop branch.  The Trilinos sha used in the nightlies on skybridge is this one: 7533f4e9cb0ce80cc00e6887f98bf0e6193fa9a5
 .

**Comment by mperego** [comment]
OK, thanks. I'll try t have a look at it today.

**Comment by ikalash** [comment]
Seems this issue has gone away - closing.

**Comment by mperego** [comment]
O great! Sometime being less responsive does pay off! It's still a bit mysterious.. if it happens again we'll dig into it.
