### ISSUE TITLE
Trouble finding/linking KokkosCore

### ISSUE THREAD

**Issue by Tread84** [SNLComputation/Albany#629]
I am trying to install Albany and while doing so I received the following error about liking KokkosCore. I know that I install Kokkos in Trilinos, but it is one of the few libraries that I never really use. Looking on guidance to solve the problem. Any help would be appreciated.

cmake       -D ALBANY_TRILINOS_DIR:FILEPATH=/home/tad/trash/Trilinos/build ..
CMake Warning at /home/tad/trash/Trilinos/build/TrilinosConfig.cmake:44 (MESSAGE):
  TrilinosConfig.cmake has moved.  It now exists at a location under the
  installation prefix where the find_package command looks by default
  (<prefix>/lib/cmake/Trilinos).  This compatibility file exists at the old
  location (<prefix>/include) to present this message and load the file from
  its new location.

  The find_package() call that loaded this file did so because its cached
  result variable, Trilinos_DIR, is set to

    /home/tad/trash/Trilinos/build

  I'm locally setting Trilinos_DIR to

    /home/tad/trash/Trilinos/lib/cmake/Trilinos

  and loading TrilinosConfig.cmake from its new location.  One may suppress
  this warning by setting the above value in the cache.  However, the
  application needs modification permanently fix the issue.  The
  find_package() call that loaded this file may have the form

    find_package(Trilinos REQUIRED PATHS ${Trilinos_PATH}/include)

  Change it to the form

    set(CMAKE_PREFIX_PATH ${Trilinos_PATH} ${CMAKE_PREFIX_PATH})
    find_package(Trilinos REQUIRED)

  to find TrilinosConfig.cmake in its new location in future builds while
  still honoring the Trilinos_PATH option for this application.
Call Stack (most recent call first):
  CMakeLists.txt:35 (FIND_PACKAGE)

CMake Error at /home/tad/trash/Trilinos/build/TrilinosConfig.cmake:66 (INCLUDE):
  INCLUDE could not find load file:

    /home/tad/trash/Trilinos/lib/cmake/Trilinos/TrilinosConfig.cmake
Call Stack (most recent call first):
  CMakeLists.txt:35 (FIND_PACKAGE)

Found Trilinos!  Here are the details: 
-- Trilinos_DIR = /home/tad/trash/Trilinos/lib/cmake/Trilinos
-- Trilinos_VERSION = 13.1
-- Trilinos_GIT_COMMIT_ID = 
-- Trilinos_BIN_DIRS = /home/tad/trash/Trilinos/lib/cmake/Trilinos/../../../bin
-- Trilinos_TPL_LIST = 
-- Trilinos_LIBRARY_DIRS = 
-- Trilinos_TPL_LIBRARY_DIRS = 
-- Trilinos_BUILD_SHARED_LIBS = 
-- Trilinos_CXX_COMPILER_FLAGS = 
End of Trilinos details

Albany version details:
-- ALBANY_GIT_BRANCH = master
-- ALBANY_GIT_COMMIT_ID = 3f37f98fb
End of Albany version details

Setting and checking of compilers:
-- Deprecated code warnings Enabled
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ALBANY_CXX_COMPILER_ID = GNU
-- ALBANY_CXX_COMPILER_VERSION = 7.5.0
CMake Error at CMakeLists.txt:233 (MESSAGE):
  

  Error: /KokkosCore_config.h not found!

-- Configuring incomplete, errors occurred!

**Comment by bartgol** [comment]
The error message makes it seem as there is an empty CMake variable. More precisely (checking the offending CMake line), it appears that `Trilinos_INCLUDE_DIRS` is empty or not defined. Since that's a variable shipped by Trilinos CMake machinery, the only explanation is that your `Trilinos_DIR` is not properly set. This is also confirmed by the fact that the stuff printed after `Found Trilinos! Here are the details:` is mostly empyt (the only two non-empty are manually set in Albany from the `Trilinos_DIR` variable).

I'm also puzzled by your trilinos tree structure. You mentioned `Trilinos/build` and `Trilinos/lib`. Did you mix build and install directory? I think it's best to not do that. Keep the build and install tree separated, and both of them separated from the src tree as well, if possible.

**Comment by jewatkins** [comment]
`-D ALBANY_TRILINOS_DIR:FILEPATH=` needs to point to your trilinos install directory. It looks like that might be `/home/tad/trash/Trilinos` if that's where you have `lib`.

**Comment by Tread84** [comment]
@bartgol @jewatkins  It was a mental error on my part, that problem is current fixed. However, I did notice that I get some interesting warnings when I try and make Albany about linkage to header files within Trilinos. The make goes past these warnings and crashes trying to create an output. I have attached the screen outputs. Thank you in advance for any help that you can provide!
[Albany Make Screen Output.txt](https://github.com/SNLComputation/Albany/files/5131252/Albany.Make.Screen.Output.txt)

**Comment by jewatkins** [comment]
Hmm I haven't seen those errors before so I'm not sure. You could try comparing your trilinos configuration with our nightly configure script to see if there's anything you might be missing:
https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/cee-compute011.sandia.gov/do-cmake-trilinos-mpi-sems-gcc

**Comment by bartgol** [comment]
Closing for lack of response.
