### ISSUE TITLE
Question about performance of MPI parallel calculation

### ISSUE THREAD

**Issue by hillyuan** [SNLComputation/Albany#631]
I've just tested performance of MPI parallel calculation of Albany by using test case in /tests/small/HeatQuadTri. I know those test cases are too small to test MPI but the results is awfully bad. 
    

> The Albany Total Time of serial calculation is 0.112733    (with OMP_NUM_THREADS=1)

    

> The Albany Total Time of 4 MPi parallel calculation is 25.3133.   (with OMP_NUM_THREADS=1)

Below I attached the output of these two calculation. Do I do anything wrong?

[mpi.txt](https://github.com/SNLComputation/Albany/files/5183221/mpi.txt)
[serial.txt](https://github.com/SNLComputation/Albany/files/5183223/serial.txt)

**Comment by bartgol** [comment]
Something that looks funky to me is the workset size: it is 921 in serial, and 660 in parallel. With 4 ranks, that 660 seems like an odd number to me.

That said, my first guess is that your mpi ranks are not pinned to a core. I usually add this line to my config script:

```
D ALBANY_MPI_EXEC_TRAILING_OPTIONS:STRING="--bind-to core"
```
If the ranks are not pinned to a core, they end up all floating to the same core, and that cause a ton of cache trashing, and CPU overload.

**Comment by hillyuan** [comment]
Thanks @bartgol . It seems that IT IS the problem. If I call mpirun like
--------
mpirun -np 4 --bind-to none -x OMP_NUM_THREADS=1
--------
Albany Total Time becomes 0.250631, I think it is reasonable considering the problem's scale.

By the way, I did nothing about workset size. 660 seems like the elements number on process, which  was set automatically by Albany.

**Comment by bartgol** [comment]
> Thanks @bartgol . It seems that IT IS the problem. If I call mpirun like
> 
> mpirun -np 4 --bind-to none -x OMP_NUM_THREADS=1
> 
> Albany Total Time becomes 0.250631, I think it is reasonable considering the problem's scale.

I'm glad that fixed it. WIth MPI and OpenMP, I found that often times the environment and launch flags are as important (if not more) as the code optimizations.
 
> By the way, I did nothing about workset size. 660 seems like the elements number on process, which was set automatically by Albany.

Ok, thanks for the clarification.

I'm closing, since this seems to be solved.
