### ISSUE TITLE
Make error with Albany Solver

### ISSUE THREAD

**Issue by Tread84** [SNLComputation/Albany#633]
I was in the process of making Albany when this morning, when it generated an error at Albany_SolverFactory.cpp,o process. It says that it is due to an unfinished job, which in my experience with Trilinos and other numerical libraries most likely there is a linkage error to somewhere. I noticed that there are some "errors" coming out trying to link with Tpetra. 

I have attached both the configure screen output and the make screen output. Thank you for your help in advance.
[Albany Make Screen.txt](https://github.com/SNLComputation/Albany/files/5233790/Albany.Make.Screen.txt)
[Albany Configure Screen.txt](https://github.com/SNLComputation/Albany/files/5233791/Albany.Configure.Screen.txt)

**Comment by bartgol** [comment]
We ran into this issue in the past, where the template arguments were not correct. In that case, it boiled down to some issue with Tpetra having changed the static graph template arguments, but we were still using the old ones.

Just to be sure, how old is your trilinos installation? And if it's not old, did you purge the install folder before the last install?

**Comment by bartgol** [comment]
Closing for lack of response.
