### ISSUE TITLE
PR merged in caused CISM-Albany tests to all fail

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#635]
Looks like the PR that was merged in yesterday caused all the CISM-Albany tests to fail with FPEs (e.g., https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=6918 ).  @mperego , is MPAS-Albany OK according to those nightlies?  I will try to triage this later today.

**Comment by mperego** [comment]
@ikalash Thanks! MALI failed but because I forgot to enable Panzer Dof Manager.
