### ISSUE TITLE
Create example comparing ML vs. MueLu performance for FELIX problem

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#64]
This is an action item stemming from issue #63 .

**Comment by ikalash** [comment]
I am continuing the discussion in Issue #63 that is specific to FELIX here.  

Attached is a report written to Tobias Wiesner (MueLu developer) documenting ML vs. MueLu performance for FELIX problems back in August 2015.  [report.pdf](https://github.com/gahansen/Albany/files/762172/report.pdf)  The main performance issue was the Block Relaxation in the LineSmoothing in Ifpack/Ifpack2. According to Tobias, there is a student working with @csiefer2 working to improve that.  Also, according to Ray Tuminaro, line smoothers in Ifpack2 may be improved as a part of the ATDM project.  

I have obtained input files from Tobias with equivalent ML and MueLu options and will do a comparison run on Edison at NERSC on an Antarctica problem to document current performance (though it will be nowhere as detailed at Tobias' report).

**Comment by csiefer2** [comment]
Discussed this with @tawiesn .  He said he'd contact @brian-kelley about getting an up-to-date performance report on the Ifpack2 BlockRelaxation (changes were checked in around December).

**Comment by mperego** [comment]
@ikalash Are you planning to do a one-time comparison, or to come up with an example to put in Albany examples? If the latter, then Antarctica problem size might be to big. Do we need to go to large scale to properly compare ML and MueLu?

**Comment by ikalash** [comment]
@mperego .  I was debating b/w these 2 options too.  I was thinking to first try a coarse resolution Antarctica and just document the result right now (again, it will be nowhere as detailed as @tawiesn's report).  The Antarctica problems are way too big to check in, so I was not going to check it in - just put it on software maybe (unless we create another repo for larger problems).  Then I was going to look at extending those results to a small problem like shelf for example, which has sliding and should require the ML/MueLu preconditioner.  The differences may not be profound there -- we will have to check.  The confined shelf test uses the STK mesh generation capability, so that one could be made arbitrarily big in theory.  Anyway, having the "real" Antarctica problem somewhere ready to run when necessary and with performance documented would be worthwhile in my opinion.

**Comment by ikalash** [comment]
@ibaned , I was wondering if you could remind me what we decided could be the maximum size of a file checked in to the Albany examples repo?  I have a coarse Antarctica problem towards this issue that I am thinking to check into the repo, but I would like to make sure that the size is OK.

**Comment by ibaned** [comment]
We aren't going to impose strict limits until after the cleanup, but for now I would say maybe 10MB is the reasonable limit on new additions. After the cleanup, there will probably be a separate repo for "big" files, and performance tests like this one may get moved to the second repo.

**Comment by ikalash** [comment]
I see.   My files should be OK to check in then.  They are <=2.7MB in size.  Thanks, @ibaned .

**Comment by ikalash** [comment]
Attached are some slides summarizing relative ML vs. MueLu performance on several different AIS problems back in March 2017 (for documentation).  These will be updated soon following the FPE fix occurring with MueLu for some AIS tests.
[ais_ml_vs_muelu2.pdf](https://github.com/gahansen/Albany/files/1195045/ais_ml_vs_muelu2.pdf)

**Comment by tawiesn** [comment]
See issue #1542 to track progress on the FPE problem

**Comment by ikalash** [comment]
This issue was brought up at the Albany meeting today so I wanted to summarize the status of ML vs. MueLu performance based on my knowledge and runs done in August 2017 (summarized from ais_ml_vs_muelu2.pdf above).  These are for Antarctica problems ranging from 8km to 2km resolution. 

- Without hinges removed, the best MueLu performance on the 2km problem is worse than the best ML performance.  I would like to understand better why there seem to be different "optimal" settings for ML and MueLu. 
- With hinges removed, MueLu can be comparable to ML on the finest problem (2km), but the "optimal" settings (necessary for MueLu to win) are different than ML.  Again, I'd like to understand why different settings are needed to get the best performance out of MueLu than ML.  It could just be due to different defaults.
- When using 3RBMs, a floating point exception (FPE) is encountered on the finer problems (4km, 2km) with MueLu, which does not happen with ML.  My recollection is we were waiting for a fix in another part of Trilinos to resolve this.

Tagging @rstumin and @jhux2.

**Comment by ikalash** [comment]
I have rerun the test cases where we were getting FPEs with MueLu, and unfortunately the issues are there.  Here is a summary:
- MueLu + 2RBMs: all variants run on all resolution AIS problems except one variant gets the following error on the 2km problem run on 1024 procs: 
```````````````````````````````
Throw test that evaluated to true: bIsZeroNSColumn == true
``````````````````````````````
I think we've encountered this before and it was not critical.
- MueLu + 3RBMs: for the coarsest problem (8km) run on 16 procs, everything is good.  FPEs are encountered on the 2 finer problems (4km on 128 procs, 2km on 1024 procs).  So the FPE issue remains, and we need someone from the MueLu team to help fix it.

**Comment by ibaned** [comment]
@ikalash thanks for confirming! Is this tracked by a Trilinos GitHub issue? If not we should open one

**Comment by ikalash** [comment]
This is a question for @rstumin, @jhux2, or @csiefer2 .  I agree that this should be come a Trilinos issue if it is not one already.

**Comment by ibaned** [comment]
https://github.com/trilinos/Trilinos/issues/2187

**Comment by ikalash** [comment]
I have an update on this issue.  Recently @rstumin pushed some changes to Trilinos, which make MueLu competitive for AIS problems finally (code does not crash, and is faster with MueLu than ML - see attached slide for some performance numbers).  This is with the so-called long parameter list syntax in MueLu.  @lucbv will be working on some refactors in MueLu to enable specifying the same MueLu options using a shorter parameter list syntax.  
[ais_ml_vs_muelu_oct2018.pdf](https://github.com/gahansen/Albany/files/2458331/ais_ml_vs_muelu_oct2018.pdf)

We would like to stress-test the MueLu preconditioner some more to make sure it is performant/robust on some additional AIS problems (dynamic problems in MALI; problems with unstructured tet meshes) and/or other test cases with sliding with the help of @mperego.

**Comment by ibaned** [comment]
@ikalash could you clarify what AIS means?

**Comment by ikalash** [comment]
Sorry Antarctic Ice Sheet.  These problems need the special AMG preconditioner because of the floating ice BC.

**Comment by mperego** [comment]
That's great! Thanks @ikalash and @rstumin !

**Comment by bartgol** [comment]
Can we close this?

**Comment by ikalash** [comment]
I'm not sure...  the title of this issue has been done.  However we are still investigating ways to improve the performance of MueLu to make it comparable to ML.  The fact that that has not been resolved was the reason for keeping the issue open.

**Comment by bartgol** [comment]
Ok, so how about closing this issue (which has, technically, been addressed), and open another, more focused one for the performance monitoring?

**Comment by ikalash** [comment]
Ok, we can close it.  Ray and I (and other involved) know that the performance discrepancies is an ongoing issue, and are looking into it, so probably a separate issue is not necessary at this time.  I may open it later.
