### ISSUE TITLE
Various failures on dashboard

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#646]
https://sems-cdash-son.sandia.gov/cdash/index.php?project=Albany
I think the GPU failures are caused by the required dependency on ROL (we don't build with ROL). See https://github.com/trilinos/Trilinos/issues/8431

The analysis performance tests on blake seem to be timeout issues:
https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=9595
Maybe these just need to be adjusted based on new settings? 

Finally, there seems to be an issue with memoization for analysis problems:
https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=688788&build=9580
It uses "Use MDField Memoization For Parameters" which can be easily broken. It looks like it's only happening on one machine which is odd.

@ikalash @mperego @kliegeois

**Comment by kliegeois** [comment]
Thanks @jewatkins  for pointing to that. I will correct that asap.

**Comment by mperego** [comment]
@jewatkins @ikalash I think we should add the dependency on ROL, because we are swithching to that for sensitivities. Sorry I forgot to anticipate that.

**Comment by jewatkins** [comment]
> @jewatkins @ikalash I think we should add the dependency on ROL, because we are swithching to that for sensitivities. Sorry I forgot to anticipate that.

I think it's just the GPU build that doesn't build with ROL. I'm assuming it builds okay? It's probably good to start testing at least.

**Comment by mperego** [comment]
> > @jewatkins @ikalash I think we should add the dependency on ROL, because we are swithching to that for sensitivities. Sorry I forgot to anticipate that.
> 
> I think it's just the GPU build that doesn't build with ROL. I'm assuming it builds okay? It's probably good to start testing at least.

B.t.w this https://github.com/trilinos/Trilinos/pull/8432 should fix the issue with ROL.
It is still OK not to add ROL as a dependency, and it will be for a long while, so no rush with that. My message above was not quite right. That been said it would probably be nice to start solving analysis problems on GPUs

**Comment by jewatkins** [comment]
@mperego Any ideas as to why this case is timing out?

Before 50s: https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=682568&build=9481
After >10min: https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=689456&build=9595
Input file: https://github.com/ikalash/ali-perf-tests/blob/master/perf_tests/green-3-20km/input_albany_BasalFrictionInit_SingleWorkset.yaml

The convergence looks the same. It looks like there's more stuff happening though.
Old:
```
************************************************************************
-- Nonlinear Solver Step 15 -- 
||F|| = 1.948e-04  step = 1.000e+00  dx = 1.302e-03 (Converged!)
************************************************************************

************************************************************************
-- Final Status Test Results --
Converged....OR Combination -> 
  Converged....F-Norm = 2.097e-07 < 1.000e-05
               (Length-Scaled Two-Norm, Absolute Tolerance)
  ??...........Number of Iterations = -1 < 50
************************************************************************
ROL::ThyraProductME_Objective::gradient
  
  *******************************************************
  ***** Belos Iterative Solver:  Block Gmres 
  ***** Maximum Iterations: 200
  ***** Block Size: 1
  ***** Residual Test: 
  *****   Test 1 : Belos::StatusTestImpResNorm<>: (2-Norm Res Vec) / (2-Norm Prec Res0), tol = 1e-08
  *******************************************************
  Iter   0, [ 1] :    1.000000e+00
  Iter  14, [ 1] :    7.841120e-09
         Response[0] = 1.16119320e+02  

Quasi-Newton Method with Limited-Memory BFGS
Line Search: Cubic Interpolation satisfying Strong Wolfe Conditions
  iter  value          gnorm          snorm          #fval     #grad     ls_#fval  ls_#grad  
  0     1.161193e+02   4.617657e+00   
ROL::ThyraProductME_Objective::update, The Parameter Changed
ROL::ThyraProductME_Objective::value
log_basal_friction has changed!
```
New:
```
************************************************************************
-- Nonlinear Solver Step 15 -- 
||F|| = 1.948e-04  step = 1.000e+00  dx = 1.302e-03 (Converged!)
************************************************************************

************************************************************************
-- Final Status Test Results --
Converged....OR Combination -> 
  Converged....F-Norm = 2.097e-07 < 1.000e-05
               (Length-Scaled Two-Norm, Absolute Tolerance)
  ??...........Number of Iterations = -1 < 50
************************************************************************
ROL::ThyraProductME_Constraint_SimOpt::update_1, The State Changed
ROL::ThyraProductME_Objective_SimOpt::update, Either The State Or The Parameters Changed
ROL::ThyraProductME_Objective_SimOpt::value
ROL::ThyraProductME_Objective_SimOpt::gradient_1
ROL::ThyraProductME_Constraint_SimOpt::applyInverseAdjointJacobian_1
  
  *******************************************************
  ***** Belos Iterative Solver:  Block Gmres 
  ***** Maximum Iterations: 200
  ***** Block Size: 1
  ***** Residual Test: 
  *****   Test 1 : Belos::StatusTestImpResNorm<>: (2-Norm Res Vec) / (2-Norm Prec Res0), tol = 1e-08
  *******************************************************
  Iter   0, [ 1] :    1.000000e+00
  Iter  14, [ 1] :    7.841120e-09
ROL::ThyraProductME_Objective_SimOpt::gradient_2
ROL::ThyraProductME_Constraint_SimOpt::applyAdjointJacobian_2

Quasi-Newton Method with Limited-Memory BFGS
Line Search: Cubic Interpolation satisfying Strong Wolfe Conditions
  iter  value          gnorm          snorm          #fval     #grad     ls_#fval  ls_#grad  
  0     1.161193e+02   4.617657e+00   
ROL::ThyraProductME_Constraint_SimOpt::update_2, The Parameter Changed
ROL::ThyraProductME_Constraint_SimOpt::update_2, Signaling That Parameter Changed
ROL::ThyraProductME_Constraint_SimOpt::solve
 log_basal_friction has changed!
```

**Comment by mperego** [comment]
@jewatkins No, apparently something in the algorithm changed, but I don't think this was expected, so it's good to have this failure. Not sure I have time to look into it today, though.

**Comment by kliegeois** [comment]
@mperego do you think that it could be related to the reduced Hessian PR? If yes, I can look into that. At first sight, it does not seem to be the case to me.

**Comment by jewatkins** [comment]
> @jewatkins No, apparently something in the algorithm changed, but I don't think this was expected, so it's good to have this failure. Not sure I have time to look into it today, though.

Okay no problem, the Trilinos git commit ids are there too. It happened sometime between 12/4 and 12/6 I think.

**Comment by mperego** [comment]
@kliegeois I also don't understand how it happened, but given that the failure happend after the merge of that PR, I  think it is likely related to that.

**Comment by kliegeois** [comment]
I will look into that tomorrow. It is strange that there are more `ThyraProductME_Constraint_SimOpt` and `ThyraProductME_Objective_SimOpt` operations.

**Comment by kliegeois** [comment]
@jewatkins I tried to reproduce the test on my Blake account and my computer; however, Albany cannot find some of the input data files and I ran into errors such as:
```
IOSS WARNING: ERROR: Unable to open input database 'mesh-vel-tet/gis_basal_populated.exo' of type 'exodusII'
```

Where can I find the required files to reproduce the performance issue?

**Comment by jewatkins** [comment]
The populated meshes need to be constructed from the 2D meshes which you may not have access to. They're here: `/home/projects/albany/ali-perf-tests-meshes/`. @ikalash could you add `knliege` to `wg-albany`?

Once you have access, the easiest way is to use the configuration file: `ali-perf-tests/doc/do-configure-blake` to construct the distributed 2D mesh, then run `ali-perf-tests/perf_tests/green-3-20km/input_albany_Velocity_PopulateMesh_Tetrahedron.yaml` to create the populated meshes.

Alternatively, once you get access to the project space, I could copy over the files you'll need.

**Comment by jewatkins** [comment]
I put the meshes here: `/home/projects/albany/ali-perf-tests-meshes/mesh-vel-tet` in case you already have access. It's already decomposed so it will only run on 8 blake nodes.

**Comment by mperego** [comment]
Commit  https://github.com/ikalash/ali-perf-tests/commit/874cf9ba370119c02e000d2d218a81c4c3232aa0 should fix the time outs.

**Comment by kliegeois** [comment]
Thanks @mperego !

**Comment by jewatkins** [comment]
> Commit [ikalash/ali-perf-tests@874cf9b](https://github.com/ikalash/ali-perf-tests/commit/874cf9ba370119c02e000d2d218a81c4c3232aa0) should fix the time outs.

Results look great now, thanks! There's also this test case that seems to be failing:
https://github.com/SNLComputation/Albany/blob/master/tests/small/LandIce/FO_GIS/input_fo_gis_analysis_stiffening_memT.yaml

Some of the other ones might be timing out too.

**Comment by mperego** [comment]
@jewatkins Just pushed a fix for that as well.

**Comment by jewatkins** [comment]
Great thanks, will close if I see all tests pass tomorrow.

**Comment by jewatkins** [comment]
Looks like everything passes now. I looked at the test time over time for a few tests and the performance looks better than before too so I'm going to close this. Thanks all!

**Comment by mperego** [comment]
Great, thanks. Sorry it took me a while to fix this. I'm not sure why the last test I fixed was not timing out before.. it had a crazy small tolerance for the nonlinear constraint solved by ROL. The  rest of the fixes made sense to me, given the changes in Piro/ROL.
