### ISSUE TITLE
CUDA build errors in nightly

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#656]
It looks like the cuda builds are down:
```
/.../build/TrilinosInstall/include/Cuda/Kokkos_Cuda_Parallel.hpp(480): error: calling a __host__ function("std::sort<int *> ") from a __device__ function("Kokkos::Impl::ParallelFor< ::,  ::Kokkos::RangePolicy< ::Kokkos::Cuda > ,  ::Kokkos::Cuda> ::operator () const") is not allowed
/.../build/TrilinosInstall/include/Cuda/Kokkos_Cuda_Parallel.hpp(480): error: identifier "std::sort<int *> " is undefined in device code
2 errors detected in the compilation of "/tmp/tmpxft_0000ef94_00000000-6_Albany_Hessian.cpp1.ii".
```
@mperego @kliegeois 
It looks like a std::sort is used which can't be used on device. If you want that bit of code on device, I think you can try using Kokkos::sort.

**Comment by kliegeois** [comment]
Sorry @jewatkins, I did not try it with Cuda. This is definitely an error.

**Comment by kliegeois** [comment]
Should I create a PR with just this modification?

**Comment by jewatkins** [comment]
Go ahead and push directly to master, assuming your local build/tests pass.
