### ISSUE TITLE
Error having to do with Albany_Hessian.cpp in GCC warning-free build on Blake

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#662]
It looks like there is an error in the GCC warning-free build on Blake:

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=12476

``
Albany/src/utility/Albany_Hessian.cpp:36:29: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
```

The blake builds have been broken for a few weeks so I'm not sure when it started.  @kliegeois could you please have a look? I'm guessing this is related to some of your recent PRs.

**Comment by mperego** [comment]
@ikalash  Commit f41be292a755ab7a69f5fa16eb8d7fa5d29818da should fix that.

**Comment by ikalash** [comment]
Thanks @mperego !  I will check tomorrow that things are good and if they are will close the issue.
