### ISSUE TITLE
How to assign Spatially Dependent Material Property?

### ISSUE THREAD

**Issue by JustinClough** [SNLComputation/Albany#665]
I'm trying to assign a temperature field that depends on both time and position. So far I followed [these lines](https://github.com/SNLComputation/Albany/blob/f751dc66a94129ea5d4b8ad27bab3cbfda45fb82/src/evaluators/pde/PHAL_NSMaterialProperty_Def.hpp#L225-L248) as an example to get a time dependence but have not been able to get the physical x,y,z values of the quadrature point. 

I tried using `coordVec()`  (based on the STOKHOS code that was nearby) so that the code block looks like:
```
  else if (matPropType == my_matPropType) 
  {
    RealType time = workset.current_time;

    for (std::size_t cell=0; cell < workset.numCells; ++cell)  {
      for (std::size_t qp=0; qp < dims[1]; ++qp) {
        auto x = Sacado::ScalarValue<MeshScalarT>::eval(coordVec(cell,qp,0));  
	auto y = Sacado::ScalarValue<MeshScalarT>::eval(coordVec(cell,qp,1));
        auto z = Sacado::ScalarValue<MeshScalarT>::eval(coordVec(cell,qp,2));

        // whatever function of t,x,y,z here:
        matprop(cell,qp) = time+x+y+z;
      }
    }
  }
```
But this yields a segmentation fault when trying to evaluate first the `coordVec()` statement.

I did also try using `physPointsCell()` based on how `physPointsSide()` is [used here](https://github.com/SNLComputation/Albany/blob/f751dc66a94129ea5d4b8ad27bab3cbfda45fb82/src/evaluators/bc/PHAL_Neumann_Def.hpp#L721-L723) but the x,y, and z values always returned as exactly zero. 

More generally, my question is how to get the physical coordinates when iterating through cells and quadrature points?

**Comment by bartgol** [comment]
It seems to me that `coordVec` is never created (and added as dependent field) in NSMaterialProperty_Def.hpp. You could try to create and add it in the ctor; you should then be able to use it in the evaluation phase.

**Comment by JustinClough** [comment]
Thanks @bartgol, I was able to solve my problem and get my space-dependent field set up. 

I'll close this issue now and post a link to  the working code once I push it to SCOREC's fork in case anyone need it in the future.

**Comment by JustinClough** [comment]
Here is a link to the commit: f6b4a8de7f4ce40d6ed43429a0d64ea53f072e45
