### ISSUE TITLE
Compilation error due to missing FROSch header

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#670]
A bunch of my nightlies on my machine camobap failed last night with a missing FROSch header error: 

``
/nightlyCDash/repos/Albany/src/Albany_SolverFactory.cpp:32:10: fatal error: Stratimikos_FROSchXpetra.hpp: No such file or directory
``
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=13416 

I thought there were missing ifdef guards, but they are there, and FROSch is on in my Trilinos.  I suspect you may need something other than ``-D Trilinos_ENABLE_ShyLU_DDFROSch:BOOL=ON `` on in Trilinos to get the Stratimikos stuff for FROSch?  @mperego could you please have a look?

**Comment by mperego** [comment]
@ikalash Thanks for pointing this out. It should be fixed now.

**Comment by ikalash** [comment]
Thanks @mperego .
