### ISSUE TITLE
Build failures in warning-free build

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#676]
The warning-free build on branch began failing to build due to some of the recent PRs merged in: 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=14019

I'm not sure who is the culprit here, I suspect @bartgol.  Could you please fix the errors?

**Comment by bartgol** [comment]
It's possible. I'll hop on vpn and take a look at the logs.

**Comment by ikalash** [comment]
Thanks @bartgol .

**Comment by bartgol** [comment]
c513241d0 should take care of those errors. We'll see tomorrow, and if no errors show up, we'll close this.

**Comment by ikalash** [comment]
Sounds good thanks @bartgol !
