### ISSUE TITLE
Question about possible changes t o FECrsMatrix in Trilinos

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#677]
I received a notification today from Tim Fuller (Tpetra developer) that they are thinking of changing the interface to FECrsMatrix a bit.  After the change, the usage of the matrix object would be like:

FECrsMatrix matrix(graph);

matrix.beginAssembly();
// do assembly
matrix.endAssembly();

matrix.beginModify();
// apply boundary conditions locally
matrix.endModify();

The previous beginFill, resumeFill, endFill will need to be updated to use beginAssembly, endAssembly, beginModify, endModify.

Tim is asking if this would that be too drastic a change for Albany.  I did a bit of grepping through the code and I don't think it should be too bad, but wanted to poll others (@mperego , @bartgol , @mcarlson801 , @jewatkins , @kliegeois ).

**Comment by ikalash** [comment]
Tagging @tjfulle as an interested party.

**Comment by tjfulle** [comment]
Thanks @ikalash!

The changes we are working on are to better support insertion of boundary conditions after assembly is complete.  The idiom pasted above is not set in stone and we are open to making other changes to make the FE assembly and bc insertion process easier.

**Comment by bartgol** [comment]
@tjfulle what's the distinguishing factor between assembly and modify? I thought maybe Assembly adds entries, while Modify changes the values, but Crs graphs are static, so all entries are already there. Could you help us understand the underlying difference?
