### ISSUE TITLE
Albany Tempus logic

### ISSUE THREAD

**Issue by mperego** [SNLComputation/Albany#682]
Tempus is required for some tests, but we do not enforce its presence at configuration time. We should either throw an error at configuration time if it is not enabled in Trilinos, or alternatively disable the tests that  needs it.
@ikalash

**Comment by bartgol** [comment]
I think we should move Tempus to the list of Albany's _required_ packages. I believe it's not in there, cause we used to support Rythmos as primary time-stepping package. It's time to update cmake logic, I think.

**Comment by ikalash** [comment]
Sorry, I missed this issue earlier.  I agree @mperego .  I will try to get to this soon.

**Comment by ikalash** [comment]
I will add logic to require Tempus for Albany.  I think this is not unreasonable and Tempus is not huge to build.  If anyone disagrees, please voice your objection here.

**Comment by mperego** [comment]
Thanks @ikalash !

**Comment by ikalash** [comment]
Sure - sorry a bout the delay.  Really swamped right now with all the proposals...
