### ISSUE TITLE
Broken warning-free build

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#686]
Looks like merging of the most recent PR broke the warning-free Albany build on Blake: 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=15501

**Comment by mcarlson801** [comment]
> Looks like merging of the most recent PR broke the warning-free Albany build on Blake:
> 
> https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=15501

I'll fix it first thing in the morning. I forgot to check for warnings, sorry.

**Comment by ikalash** [comment]
Thanks @mcarlson801 !

**Comment by ikalash** [comment]
Thanks for fixing this Max!
