### ISSUE TITLE
Breaking change to Tpetra::FE*

### ISSUE THREAD

**Issue by tjfulle** [SNLComputation/Albany#687]
`Tpetra::FE*` objects are being modified to remove the `beginFill`, `endFill`, and `resumeFill` methods.  They are being replaced with `beginAssembly`, `endAssembly`, `beginModify`, and `endModify`.  An open PR is tracking the progress: https://github.com/trilinos/Trilinos/pull/9000.

Additionally, all of the methods for modifying a `FE` entity have been modified as follows:

- Insert, sum, replace, etc. *global* values is only allowed in the assembly phase
- Insert, sum, replace, etc. *local* values is allowed in the assembly and modify phases

Where your code has something like:

```c++
Tpetra::FECrsMatrix<> matrix(...);
matrix.beginFill();
// Do assembly and fill the thing
matrix.endFill();

matrix.resumeFill();
// Apply BCs
matrix.endFill();
```

```c++
Tpetra::FECrsMatrix<> matrix(...);
matrix.beginAssembly();
// Do assembly and fill the thing
matrix.endAssembly();

matrix.beginModify();
// Apply BCs
matrix.endModify();
```

@bartgol - @mperego suggested I tag you to discuss timelines for modifying Albany so that https://github.com/trilinos/Trilinos/pull/9000 can be merged.

**Comment by bartgol** [comment]
@tjfulle I read one of your comment on the PR:

> replaceGlobalValues does not allow replacing global values during the modify phase because globalAssemble is not called after endModify like it is after endAssembly.

Does this mean that endModify will not ship the shared rows to the correct processor (the doOwnedPlusSharedToOwned)? So in your example,  with 'Apply BCs' you meant "local" bcs (like Dirichlet), right?

So is calling begin/end Modify equivalent to call CrsMatrix::resumeFill?

**Comment by ikalash** [comment]
@bartgol : would you be willing/able to make changes to Albany to go hand-in-hand with this Tpetra PR, so that we have a PR ready to go once the changes in Trilinos are merged in?  I am really swamped right now with several proposals, and I think you likely are in the best position to make the changes given some of your recent work pertaining to restructuring the code for block data structures.

**Comment by bartgol** [comment]
Yeah, I can try to do that. Heads up though: I'm off all next week, so if that PR goes in then, I won't be able to merge the PR (and check nightlies) till May 10th.

**Comment by ikalash** [comment]
@tjfulle : any way we can hold off merging the Tpetra changes until after May 10?

**Comment by bartgol** [comment]
Hi all, I'm finally back from vacation. I'm working on an Albany branch for this today.

**Comment by ikalash** [comment]
Thanks great, thanks @bartgol !

**Comment by bartgol** [comment]
Update: I have a branch where all tests pass, except for FO_GIS_CoupledThickness (both Tpetra and Epetra, which is weird), which fail due to a floating point exception. This is without funky scalar type cmake options.

I'm tracking it down, and hopefully get it done by COB today.

**Comment by mperego** [comment]
Thanks @bartgol! Is your branch up to date with master? I think that test used to fail at some point becasue of the issue with the collapsed side-set storage.

**Comment by bartgol** [comment]
Ah, good call. Let me check.

**Comment by bartgol** [comment]
That fixed it! 

Thanks @mperego ! As a token of my gratitude, I'll add you as a reviewer for the PR. :)

**Comment by ikalash** [comment]
I think we can close this.  If I'm mistaken, please reopen.
