### ISSUE TITLE
Rebuild TPLs on Skybridge to fix Skybridge nightlies

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#692]
It looks like we were relying on TPLs in Dan Ibanez's home directory on skybridge.  These recently got deleted and the TPLs need to be rebuilt to get the skybridge nightlies b ack up.

**Comment by bartgol** [comment]
Ugh, that's annoying. Thanks for taking care of this. Hopefully by now most of the TPLs are available via modules...

**Comment by ikalash** [comment]
Yeah, I can't remember the rationale for not using modules anymore.  @ibaned , do you remember?  Were they just not available at the time, or there was something the modules were missing?  Or maybe not all users had access to all modules, so we built our own?

**Comment by ibaned** [comment]
I would try using SEMS modules. They've improved significantly in the past year and there is a system for submitting support tickets to them. They really care about supporting these modules so that would be the right way to go.

**Comment by ikalash** [comment]
Thanks @ibaned - that was my plan.
