### ISSUE TITLE
Failing CALI tests 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#697]
It looks like the CALI tests are failing starting today with the following error: 

```
terminate called after throwing an instance of 'Teuchos::Exceptions::InvalidParameterName'
  what():  Error!  The parameter "Mu Field Name" does not exist
in the parameter (sub)list "Albany Parameters->Problem->LandIce BCs->BC 0->Basal Friction Coefficient".

The current parameters set in (sub)list "Albany Parameters->Problem->LandIce BCs->BC 0->Basal Friction Coefficient" are:

  {
    "Type" : string = Given Field
    "Given Field Variable Name" : string = basal_friction
  }


Throw number = 1
```
https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=1191806&build=17517

It appears the syntax for the PL list has changed and needs to be propagated into the CALI tests.

**Comment by mperego** [comment]
Oh.. right, sorry I had in mind to fix the cism interface and then I forgot. I'll push a fix today

**Comment by ikalash** [comment]
@mperego : thanks for fixing the CALI tests.  There is one more that was broken (the CISM vs. Albany comparison one).  It appears Effective Pressure Type and Effective Pressure are now required inputs to the land-ice BCs.  I put the following in my input file and it appears to work

```
    Effective Pressure Type: Constant
    Effective Pressure: 1.0
```

Is it indeed the right thing to use?

**Comment by mperego** [comment]
@ikalash that works, or instead of 
```
          Type: Power Law
          Mu Field Name: basal_friction
          Power Exponent: 1.0
          Effective Pressure Type: Constant
          Effective Pressure: 1.0
```
you can simply have
```
          Type: Field
          Beta Field Name: basal_friction
```

**Comment by ikalash** [comment]
@mperego : ah ok, I see.  I will simplify it per your suggestion.
