### ISSUE TITLE
Warning-free blake build broke

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#701]
It looks like the recent PR also broke the warning-free build on blake: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=18275 .  @bartgol could you please look at this as well?

**Comment by bartgol** [comment]
Sorry about that. I pushed a commit that should take care of the two warnings on that build.

**Comment by ikalash** [comment]
Thank you @bartgol !  I'll verify tomorrow that things are fixed.
