### ISSUE TITLE
BlockDiscretization_Jacobian_Unit_Test failing on machines w/o numpy/scipy

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#703]
It looks like the recently-added BlockDiscretization_Jacobian_Unit_Test is failing on machines w/o numpy/scipy (blake, skybridge, mockba): https://sems-cdash-son.sandia.gov/cdash/index.php?project=Albany .   One fix is to disable the test if numpy/scipy are not found.  @kliegeois is looking into this.

Question for @jewatkins : is there a way to get numpy/scipy through modules on blake (and similarly skybridge)?  It seems strange to me that there is a python module but not one for numpy/scipy.  Maybe I'm just not finding it?

**Comment by jewatkins** [comment]
`module load python/3.7.3` seems to already have numpy, scipy on blake but I might have installed it locally. You could try:
```
module load python/3.7.3
pip install numpy --user
pip install scipy --user
```
I'm not sure about the other clusters. It sometimes won't work (even locally) due to permissions depending on the package. @mcarlson801 is going to look into getting blake/weaver working with other python packages for autotuning so he may already have more information

**Comment by kliegeois** [comment]
I just finished the modification. I am testing in on Blake and I create the PR.

**Comment by kliegeois** [comment]
> `module load python/3.7.3` seems to already have numpy, scipy on blake but I might have installed it locally. 

@jewatkins I just verified, it comes with numpy but not scipy (which can be installed locally either with pip as you said or with  easy_instal).

**Comment by jewatkins** [comment]
okay, @ikalash you could probably add something like what's suggested [here ](https://askubuntu.com/a/1211956) to the blake module file to ensure these packages are always installed.

**Comment by ikalash** [comment]
@jewatkins : thanks, your suggestion worked!

**Comment by ikalash** [comment]
Just for documentation (i.e., so I don't forget), to install libs using pip on some of the SRN machines and bypass proxies/SSL certificates, one needs to execute the following command:

```pip3 install numpy --trusted-host=pypi.org --trusted-host=files.pythonhosted.org --user```

**Comment by kliegeois** [comment]
If I may add, on IBM machines (at least weaver), you need to specify a bit older numpy (such as 1.19.2) otherwise, when building up to date numpy, it fails to compile.

**Comment by jewatkins** [comment]
Thanks for the suggestions. It should help for future python workflow.

**Comment by kliegeois** [comment]
Just for documentation, on Weaver, to install matplotlib we need to install pillow as follows:
`pip install --user pillow --global-option="build_ext" --global-option="--disable-jpeg"`

**Comment by kliegeois** [comment]
(We probably need to start compiling those lines of code into a wiki at some point)

**Comment by jewatkins** [comment]
> (We probably need to start compiling those lines of code into a wiki at some point)

Feel free to start compiling a list on a "Python on Blake/Weaver" wiki page and post the link on this issue

**Comment by kliegeois** [comment]
Done: https://github.com/SNLComputation/Albany/wiki/PyAlbany

It can be accessed from the Sidebar under "Python and Albany".
