### ISSUE TITLE
Lots of failing tests in Blake GCC warning-free build

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#708]
It looks like after the FECrsMatrix PR went in yesterday, there are a bunch of tests failing on Blake in the GCC warning-free build:

https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=19046

The error looks like this:

```

************************************************************************
-- Nonlinear Solver Step 0 -- 
||F|| = 1.037e+03  step = 0.000e+00  dx = 0.000e+00
************************************************************************


p=3: *** Caught standard std::exception of type 'Thyra::Exceptions::IncompatibleVectorSpaces' :

 /home/projects/albany/nightlyCDashTrilinosBlake/build/TrilinosSerialInstallGccNoWarn/include/Thyra_ModelEvaluatorHelpers.hpp:711:
 
 Throw number = 1
 
 Throw test that evaluated to true: !l_isCompatible
 
 Thyra::DefaultModelEvaluatorWithSolveFactory{thyraModel='Albany::ModelEvaluator',W_factory='Thyra::AztecOOLinearOpWithSolveFactory{precFactory=Thyra::Ifpack2PreconditionerFactory}'}
 
 Error, the following vector spaces are not compatible:
 
  *outArgs.get_W_op()->range() : Thyra::TpetraVectorSpace<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >{globalDim=7602,localSubDim=1878,localOffset=5724,comm=Teuchos::MpiComm<long>{size=4,rank=3,rawMpiComm=0x718b80}}
 
  *model.get_f_space() : Thyra::TpetraVectorSpace<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >{globalDim=7311,localSubDim=1812,localOffset=5499,comm=Teuchos::MpiComm<long>{size=4,rank=3,rawMpiComm=0x718b80}}
 

p=1: *** Caught standard std::exception of type 'Thyra::Exceptions::IncompatibleVectorSpaces' :

 /home/projects/albany/nightlyCDashTrilinosBlake/build/TrilinosSerialInstallGccNoWarn/include/Thyra_ModelEvaluatorHelpers.hpp:711:
 
 Throw number = 1
 
 Throw test that evaluated to true: !l_isCompatible
 
 Thyra::DefaultModelEvaluatorWithSolveFactory{thyraModel='Albany::ModelEvaluator',W_factory='Thyra::AztecOOLinearOpWithSolveFactory{precFactory=Thyra::Ifpack2PreconditionerFactory}'}
 
 Error, the following vector spaces are not compatible:
 
  *outArgs.get_W_op()->range() : Thyra::TpetraVectorSpace<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >{globalDim=7602,localSubDim=1848,localOffset=2016,comm=Teuchos::MpiComm<long>{size=4,rank=1,rawMpiComm=0x718b80}}
 
  *model.get_f_space() : Thyra::TpetraVectorSpace<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >{globalDim=7311,localSubDim=1725,localOffset=2016,comm=Teuchos::MpiComm<long>{size=4,rank=1,rawMpiComm=0x718b80}}
 ```
Just to be clear, I don't think this has anything to do with the build being warning free.  One thing that is unique about it relative to the other builds on blake is it's a debug build.  However, it is curious that this problem does not show up in the other debug builds we have in the nightlies.

@mperego , @bartgol , @tjfulle, any thoughts on the cause here?

**Comment by tjfulle** [comment]
Huh.  The Tpetra changes were really just to change `(begin|end)Fill` to `(begin|end)Assembly` and add the `(begin|end)Modify`.  Otherwise, the internals remained largely unchanged.

were there any other new commits besides the Tpetra commits?

**Comment by ikalash** [comment]
Good question.  Well, we had an MR go into Albany that went hand-in-hand with the Tpetra changes.  I am thinking that might be the cause of the issues.

**Comment by ikalash** [comment]
It looks like the residual f and the Jacobian W_op have different sizes - that is bizarre!

**Comment by mperego** [comment]
Um.. unfortunately Luca, who worked on the PR, is on vacation until July 23rd.

**Comment by ikalash** [comment]
Right...  we might have to wait for him to return.

**Comment by bartgol** [comment]
I'm back. Let's catch up during the telecon tomorrow.

**Comment by mperego** [comment]
@bartgol welcome back Luca! 
We saved ths issue for you, so that you don't feel replaceable ;-)

**Comment by bartgol** [comment]
I think I found the culprit, but the fix seems a bit overly complicated, so I'm gonna ask @tjfulle for confirmation.

Tim, when we create a FE matrix using a FE graph that has already been "closed", the resulting FE matrix will still be in "assembly" mode, right? Is there a way to create an "assembled" matrix that is less cumbersome than the following?

```
      // Here, my_fe_graph is closed, in the sense that I already called 'my_fe_graph->endAssembly`.
      auto fe_matrix = Teuchos::rcp (new Tpetra_FECrsMatrix(my_fe_graph));
      fe_matrix->beginAssembly();  // LINE A
      fe_matrix->endAssembly();     // LINE B
      fe_matrix->beginModify();
      fe_matrix->setAllToScalar(zero);
      fe_matrix->endModify();
```
Without lines A and B, the matrix appears to be still in owned+shared mode. Without line A, line B errors out, saying that we can't be finishing assembly, since the matrix is already Closed.

My naive feeling: if FECrsMatrix is created already in "assembly" mode, even if the input fe graph is "closed", then the matrix should not be marked as "closed", but rather be marked as "open". If the matrix is "closed", then I expect the maps of the matrix to be the "owned" ones.

Am I missing something?

**Comment by bartgol** [comment]
Assuming my bug fix is indeed the culprit, I am wondering why are only certain tests failing. It's my understanding that most of the tpetra tests are still passing, right? How is that possible, given that we were clearly creating matrices with the wrong domain/range maps distribution?

**Comment by ikalash** [comment]
Thanks for looking into this Luca!  I think the tests that are passing are actually either all Epetra or Serial Tpetra (I spot checked a few of the Tpetra tests that pass and they are on 1 proc: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlypassed&buildid=20571 ).  Lets wait what @tjfulle says regarding your question above.  What I've been scratching my head about is why this is only showing up in the blake gcc warning free build.  We have other builds that should be similar including debug builds.

**Comment by tjfulle** [comment]
Sorry for the delay @bartgol - I was away all weekend with no internet service.

What was in your code before?  Did you have `beginFill` and/or `resumeFill`?

**Comment by mperego** [comment]
@tjfulle I think the code before was like this
      auto fe_matrix = Teuchos::rcp (new Tpetra_FECrsMatrix(my_fe_graph));
      fe_matrix->setAllToScalar(zero);
      fe_matrix->endFill();

**Comment by bartgol** [comment]
Yes, that's how the code was before the change I posted.

@ikalash It is indeed odd. All debug builds should run the teuchos exception tests, so they should all crap out.

**Comment by mperego** [comment]
@ikalash do the other debug builds have Trilinos compiled in debug mode?

**Comment by tjfulle** [comment]
@bartgol - does the assembly code work if if you do:

```c++
      auto fe_matrix = Teuchos::rcp (new Tpetra_FECrsMatrix(my_fe_graph));
      fe_matrix->beginModify();
      fe_matrix->setAllToScalar(zero);
      fe_matrix->endModify();
```

**Comment by tjfulle** [comment]
I don't know that `begin/endAssembly` is needed in this case.  `begin/endModify` are needed because the matrix has the state flag set to `closed` on construction.

**Comment by bartgol** [comment]
> @bartgol - does the assembly code work if if you do:
> 
> ```c++
>       auto fe_matrix = Teuchos::rcp (new Tpetra_FECrsMatrix(my_fe_graph));
>       fe_matrix->beginModify();
>       fe_matrix->setAllToScalar(zero);
>       fe_matrix->endModify();
> ```

My bad. That's exactly what it was before the fix. I only added the begin/end assembly between the ctor and the call to beginModify.

**Comment by bartgol** [comment]
I explicitly added some cout of the row map local sizes, and right after the ctor it showed local sizes corresponding to an owned+shared partition:

```
      auto fe_matrix = Teuchos::rcp (new Tpetra_FECrsMatrix(m_graph->t_graph));
      auto rowMap = fe_matrix->getRowMap();
      auto rank = rowMap->getComm()->getRank();
      std::cout << "num local rows on rank " << rank << ": " << rowMap->getNodeNumElements() << "\n";
      fe_matrix->beginModify();
      fe_matrix->setAllToScalar(zero);
      fe_matrix->endModify();
      ...
```
Output:
```
num local rows on rank 1: 51
num local rows on rank 0: 51
```
The mesh is a 1d mesh, with 100 elements (so 101 global nodes).

**Comment by tjfulle** [comment]
Ahhhh, ok

```c++
      auto fe_matrix = Teuchos::rcp (new Tpetra_FECrsMatrix(my_fe_graph));
      fe_matrix->beginAssembly();
      fe_matrix->setAllToScalar(zero);
      fe_matrix->endAssembly();
```

instead of `begin/endModify` should give identical behavior as before.  The `beginAssembly` doesn't do anything but set the state flag to `assembly` mode which allows global operations (`sumIntoGlobalValues`, etc).  `endAssembly` closes the state flag and then does `endFill`.

**Comment by bartgol** [comment]
Yes, I think that should work (I am testing now).

However, if I can give some feedback, I find the current behavior a bit confusing. In particular, if the input graph of the ctor is already assembled, I would expect the fe matrix to be in "owned" mode. In other words, I would expect that when the active matrix is the owned+shared, then the state is open (assembly mode), and viceversa. The fact that right after construction you have the matrix in open+shared state but with closed fillState is confusing.

**Comment by ikalash** [comment]
> @ikalash do the other debug builds have Trilinos compiled in debug mode?

Oh yes - the one on my workstation camobap has a debug Trilinos and Albany (+ FPE checking enabled).

**Comment by bartgol** [comment]
> > @ikalash do the other debug builds have Trilinos compiled in debug mode?
> 
> Oh yes - the one on my workstation camobap has a debug Trilinos and Albany (+ FPE checking enabled).

And tests pass on your workstation? That's quite disturbing...

**Comment by ikalash** [comment]
@bartgol : yes - this is the build I was referring to: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlypassed&buildid=20647 .  I don't get it either...

**Comment by ikalash** [comment]
The CEE debug build is also clean: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlypassed&buildid=20625

**Comment by tjfulle** [comment]
@bartgol - I think I am understanding.

```c++
{
  auto matrix = rcp(new FECrsMatrix(row_map, col_map, ...));
  // active matrix is owned+shared
  // expect matrix to have FECrsMatrix::fillState_ == open
}
{
  auto graph = rcp(new FECrsGraph(...));
  graph->beginAssembly();
  // ...
  graph->endAssembly();
  auto matrix = rcp(new FECrsMatrix(graph));
  // expect matrix is owned
  // expect matrix to have FECrsMatrix::fillState_ == modify
}
```

Does that describe what you are suggesting?  I can see the confusion probably came about from `FECrsMatrix` development being largely driven by ALEGRA - which doesn't create the matrix from a pre-populated graph.  That case was an afterthought.

Either way, one of the design decisions was to make entering the assembly and modify phases explicit.

**Comment by bartgol** [comment]
@tjfulle Yes, that's roughly what I would expect. Actually, in the second case, I would even expect the fillState to be closed, so that one has to explicitly open it for modification. E.g., consider this

```
RCP<FECrsMatrix> createMat (RCP<FECrsGraph> graph); // creates a mat from a pre-assembled graph
void enterValues(FECrsMatrix& mat); // inserts values in the matrix
```
The second routine, is probably expecting the matrix always in the same state (open, modify or closed), regardless of where the matrix comes from (newly created or old recycled one). In my case, I'm thinking of a Thyra ModelEvaluator, with a matrix extracted from a Thyra::LinearOp:

```
void MyEvaluator::evalImpl (InArgs in, OutArgs out) 
   auto W = out.get_W_op ();
   auto A = Teuchos::rcp_dynamic_cast<Tpetra::FECrsMatrix>(W);
   A->beginModify();    // Should I do this? Or is A already in modify state cause it was newly created?
   set_jacobian_to_blah(A);
   A->endModify();
```
In general, I think it's best if a newly created matrix from a closed graph is marked with fillState = closed. That allows to always assume the same state every time a matrix is passed, whether it's the 1st iteration (with a newly created matrix) or the 100th one. The modify/assembly state should always be _requested_ by the user, rather than implicitly given. Which, as you suggested, was one of the reason why you guys added the assembly/modify guards.

**Comment by bartgol** [comment]
@tjfulle Another point in favor of having A's state `closed` or `modify`, if the input graph is closed. Right now, I have to do:

```
auto A = rcp(new FECrsMatrix(graph));
A->beginAssembly();
A->setAllToScalar(0);
A->endAssembly();
```
which costs me a pointless global assembly. If instead A was created with the active matrix equal to the owned only (since that's the state of the input graph), I would be able to skip this pointless global communication...

If you want, we can move this discussion to an issue in trilinos...

**Comment by tjfulle** [comment]
@bartgol - sorry the notification for you last comment got lost in a sea of email.

Yes, please open an issue on GitHub.com/trilinos/Trilinos and we can see about making those modifications
