### ISSUE TITLE
An error occurred in MPI_Allreduce

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#710]
This started happening in the nightly performance tests starting 7/8:
** Trilinos git commit id - 6ebdaf5 
** Albany git commit id --- a0e65cf
...
*** An error occurred in MPI_Allreduce

It seems to happen on blake with green-1-10km_vel_muk_tet_np384 and blake/weaver with green-1-7km_muk_ls_mem_np384. Previous passing commits:
** Trilinos git commit id - e06fadb
** Albany git commit id --- 65ca5d6

Latest failure:
https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=1293169&build=19222
I'm not sure what the issue is. First step might be to look at the before/after commits to see if there's anything suspicious.

**Comment by jewatkins** [comment]
I think https://github.com/trilinos/Trilinos/pull/9458 fixed this issue. Discussion here: https://github.com/trilinos/Trilinos/issues/9455 although the error was not the same.

This also fixed my issue at scale. Logging the error I saw for reference:
```
Fatal error in MPIDI_Cray_shared_mem_coll_tree_reduce: Other MPI error, error stack:
MPIDI_Cray_shared_mem_coll_tree_reduce(190): message sizes do not match across processes in the collective routine: Received 4 but expected 8
```

**Comment by mperego** [comment]
@jewatkins great!
