### ISSUE TITLE
[ERROR] FROSch::Amesos2SolverTpetra: mode!=NO_TRANS on weaver

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#711]
FO_Thermo_Wet_Bed_FROSch GPU test failing on weaver:
https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=1291684&build=19200
with the following error:
[ERROR] FROSch::Amesos2SolverTpetra: mode!=NO_TRANS

This started happening starting 7/9:
** Trilinos git commit id - 505f6e1
** Albany git commit id --- 18c8cd6

And passed on 7/8 (I can't see the commit ids but I'm assuming it's similar to the other ones):
** Trilinos git commit id - 6ebdaf5
** Albany git commit id --- a0e65cf
I'm not sure what the issue is, will have to look at the commits.

**Comment by mperego** [comment]
@jewatkins I don't understand why this is failing only on GPU. FROSch is complaning that it's asked to solve a transposed system but it shouldn't be the case. It might be some subtle issue w/ RCP of references not correclty handled. 
Do you have a chance to test if this https://github.com/trilinos/Trilinos/pull/9415  fixes it? Alternatively we can wait for tonight nightly tests, after the PR is merged.

**Comment by jewatkins** [comment]
Yes, we can wait to see if the PR fixes it. If not, we can look more into it tomorrow.

**Comment by mperego** [comment]
I think I understand what's going on. ROL is not enabled in this build. We now rely on ROL for sensitivities as well but we left the non-ROL code for backward compatibility. I need to update the non-ROL code in Piro.

After this is fixed, I think we should enable ROL in the CUDA build as well.

**Comment by jewatkins** [comment]
Okay sounds good, I can do that once it's fixed.

**Comment by mperego** [comment]
@jewatkins  this has been fixed. It's probably good to have at least one cuda build that enables ROL.

**Comment by jewatkins** [comment]
Great thanks! I'll try adding ROL to weaver. We have still have ride, we can leave it off there if you want to continue testing without it. I can turn FROSch on there too so that it hits this case.

**Comment by mperego** [comment]
Yeah, that's probably a better solution, that is, having FROSch enabled on both and ROL only on one of the builds.
