### ISSUE TITLE
Tempus error: "Predictor Name" not found

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#722]
There's two tests failing (Thermal1D_with_Source, Thermal2D_BackwardEuler_with_Source), I think due to input parameter changes in Tempus?
https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=19893
https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=1337757&build=19893

@ikalash Did you want to take a look since you're most familiar with Tempus?

**Comment by ikalash** [comment]
This was due to a change in Tempus.  I have fixed the issue - thank you for calling it to my attention.
