### ISSUE TITLE
CALI test failing after #729

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#731]
See:
https://sems-cdash-son.sandia.gov/cdash/testDetails.php?test=1406432&build=20898
and
#729 

It looks like it might have something to do with the default workset changes. I'll look into later today.

**Comment by jewatkins** [comment]
I actually think this might get fixed with #725 so I'm going to wait on this.

**Comment by ikalash** [comment]
Looks like this issue has been fixed.  Closing.
