### ISSUE TITLE
Fad-related errors in Albany spack build

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#737]
The nightly Albany spack build is failing now with the following error:

```
 >> 295    /tmp/ikalash/spack-stage/spack-stage-albany-develop-62nlkmwvlr67fok
            xavqlzafce6u2qiea/spack-src/src/PHAL_Utilities.cpp:37:26: error: 'i
            s_statically_sized' is not a member of 'Sacado::Fad::DFad<double>::
            StorageType {aka Sacado::Fad::DynamicStorage<double, double>}'
     296           FadT::StorageType::is_statically_sized && (FadT::StorageType
            ::static_size < dDims),
     297                              ^
  >> 298    /tmp/ikalash/spack-stage/spack-stage-albany-develop-62nlkmwvlr67fok
            xavqlzafce6u2qiea/spack-src/src/PHAL_Utilities.cpp:37:69: error: 's
            tatic_size' is not a member of 'Sacado::Fad::DFad<double>::StorageT
            ype {aka Sacado::Fad::DynamicStorage<double, double>}'
     299           FadT::StorageType::is_statically_sized && (FadT::StorageType
            ::static_size < dDims),
     300
              ^
```
I know @jewatkins you made some Fad-related changes - is this related?  Do I need to add/change a compilation option now to avoid the error?

**Comment by jewatkins** [comment]
Thanks for the heads up, yes that's related to my push. It looks like your build is using the old sacado structs. If I remember correctly, this should be pulling the latest trilinos, correct? The new sacado structs are on by default so you may be explicitly turning it off: `SACADO_NEW_FAD_DESIGN_IS_DEFAULT=OFF`

**Comment by ikalash** [comment]
Yes, it's develop VOTD.  Last night's build had this sha for Trilinos: 353c286554055695c8a306ffc999288a7e562e9a .  Hmmm, I don't think I'd be explicitly turning it off, as I had never heard of this option, but let me investigate.

**Comment by jewatkins** [comment]
If you point me to the trilinos config, I could investigate too. It could be some other option that might be turning it off.

**Comment by ikalash** [comment]
Turns out the build had ```SACADO_NEW_FAD_DESIGN_IS_DEFAULT=OFF'''.  Setting it to ON fixed the problem.  Thanks for letting me know about this, @jewatkins !
